// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

export type TableName = "messages" | "users";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_messages {
    _id: Id<"messages">;
    _creationTime: number;
    channelId: Id<"channels">;
    text: string;
}

export interface Doc_users {
    _id: Id<"users">;
    _creationTime: number;
    email: string;
    name: string;
}

export interface DataModel {
    messages: Doc_messages;
    users: Doc_users;
}

export type Doc<T extends keyof DataModel> = DataModel[T];
