// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import * as cirrus_messages_0 from "../messages.js";

export { action, mutation, query } from "@cirrus/server";
export type { ActionCtx, MutationCtx, QueryCtx } from "@cirrus/server";

export type { DataModel, Doc, Id } from "./dataModel.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredCirrusFunction {
    kind: "action" | "mutation" | "query";
    args: Record<string, unknown>;
    handler: (context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown;
}

/**
 * Static dispatch table. The key matches the `__cirrusRef` the client
 * emits (`api[namespace][fn].__cirrusRef === "namespace:fn"`).
 */
export const CIRRUS_FUNCTIONS: Record<string, RegisteredCirrusFunction> = {
    "messages:list": cirrus_messages_0.list as unknown as RegisteredCirrusFunction,
    "messages:send": cirrus_messages_0.send as unknown as RegisteredCirrusFunction,
};

/**
 * Resolve and invoke a registered function. Throws a CirrusError-shaped
 * object (404) when the path is unknown — the runtime's structural error
 * mapper turns that into the right HTTP status.
 */
export const dispatchCirrusFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw Object.assign(new Error(`function not registered: ${functionPath}`), {
            name: "CirrusError",
            code: "FUNCTION_NOT_FOUND",
            status: 404,
        });
    }

    return registered.handler(context, args);
};
