// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    messages: {
        board: FunctionReference<"query", { limit?: number }, { messages: import("./dataModel.js").Doc_messages[]; newestAt: number; total: number }>;
        send: FunctionReference<"mutation", { author: string; body: string }, Id<"messages">>;
    };
}

export const api: ApiTypes = {
    messages: {
        board: { __lunoraRef: "messages:board" },
        send: { __lunoraRef: "messages:send" },
    },
};
