// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const messages = sqliteTable("messages", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    author: text("author").notNull(),
    body: text("body").notNull(),
    postedAt: real("postedAt").notNull(),
}, (t) => ({
    by_posted: index("by_posted").on(t.postedAt),
}));
