export { createLunoraClient } from "./create-lunora-client";
export type { AuthHeadersFactory, CreateLunoraClientOptions } from "./types";

// `@lunora/react-native` is the React Native / Expo entry to Lunora. The hooks,
// provider, and auth gates are the exact same client-side React building blocks
// as `@lunora/react` — they call `useState`/`useEffect`/`use(...)` and own a
// live WebSocket, and they never touch `react-dom` or a browser-only global — so
// they run unchanged under React Native. Rather than fork them, this package
// re-exports the `@lunora/react` surface and adds the two things a native app
// needs on top: a React-Native-tuned client factory (AsyncStorage-backed
// offline queue + credentialed fetch/WebSocket) and, from the `./auth` subpath,
// a one-call better-auth Expo client.
//
// The list is explicit rather than `export * from "@lunora/react"` because that
// star pulled in the payment surface — `CheckoutButton`, `CustomerPortalButton`
// and `useCheckout` render a DOM `<button>` and navigate via
// `globalThis.location`, neither of which exists on a phone, so every one of
// them threw at render/call time on the platform this package targets. Payments
// in a native app go through the platform's own purchase flow (or a WebView on
// the web checkout URL), not through these components.
//
// `__tests__/react-surface-parity.test.ts` asserts this list stays exactly
// `@lunora/react`'s barrel minus the payment exports, so a new hook added there
// cannot silently go missing here.

export type {
    ActionHook,
    AdminAuthListResult,
    AgentChatMessage,
    AgentLiveEvent,
    AgentProgressEvent,
    AgentThreadRecord,
    AgentThreadStatus,
    AgentTokenDelta,
    AgentToolEvent,
    ArgsOf,
    AuthImpersonation,
    AuthPage,
    AuthSession,
    AuthState,
    AuthUser,
    ClientQueryRef,
    FlagContext,
    FlagValue,
    FunctionReference,
    HeartbeatReference,
    HttpStreamArgsOf,
    HttpStreamChunkOf,
    HttpStreamRef,
    ListPresentReference,
    LunoraClient,
    LunoraErrorCode,
    LunoraProviderProps,
    LunoraQueryOptions,
    MutationHook,
    MutatorHandle,
    MutatorHook,
    MutatorTransaction,
    OptimisticLocalStore,
    OptimisticUpdate,
    PageItemOf,
    PaginatedArgs,
    PaginationResult,
    PaginationStatus,
    Preloaded,
    ReturnOf,
    SubscriptionError,
    SubscriptionErrorCallback,
    UploadMethod,
    UploadRestrictions,
    UploadResult,
    UseAgentApi,
    UseAgentChatApi,
    UseAgentChatOptions,
    UseAgentChatResult,
    UseAgentOptions,
    UseAgentResult,
    UseAgentStateApi,
    UseAgentStateOptions,
    UseAgentStateResult,
    UseAgentToolEventsApi,
    UseAgentToolEventsOptions,
    UseAgentToolEventsResult,
    UseAuthResult,
    UseAuthSessionsOptions,
    UseAuthUsersOptions,
    UseChunkedRestUploadOptions,
    UseChunkedRestUploadReturn,
    UseFileInputOptions,
    UseFileInputReturn,
    UseHttpStreamOptions,
    UseHttpStreamResult,
    UseImpersonateResult,
    UseInfiniteQueryOptions,
    UseInfiniteQueryResult,
    UseMultipartUploadOptions,
    UseMultipartUploadReturn,
    UseMutationCallOptions,
    UseOrganizationsOptions,
    UsePaginatedQueryOptions,
    UsePaginatedQueryResult,
    UsePasteUploadOptions,
    UsePasteUploadReturn,
    UsePresenceOptions,
    UsePresenceResult,
    UseQueryOptions,
    User,
    UseRateLimitOptions,
    UseRateLimitResult,
    UseStreamOptions,
    UseStreamResult,
    UseStreamStatus,
    UseSubscriptionResult,
    UseTusUploadOptions,
    UseTusUploadReturn,
    UseUploadOptions,
    UseUploadReturn,
    UseVoiceAgentOptions,
    UseVoiceAgentResult,
    VoiceAudioFormat,
    VoiceReference,
    VoiceStatus,
} from "@lunora/react";
export {
    Authenticated,
    AuthLoading,
    createClientQuery,
    getErrorCode,
    getRetryAfterMs,
    hydratePreloaded,
    isConflictError,
    isForbiddenError,
    isRateLimitedError,
    isUnauthorizedError,
    LunoraProvider,
    lunoraQueryOptions,
    RestrictionError,
    Unauthenticated,
    UploadControl,
    UploadError,
    useAction,
    useAgent,
    useAgentChat,
    useAgentState,
    useAgentToolEvents,
    useAuth,
    useAuthSessions,
    useAuthState,
    useAuthUsers,
    useChunkedRestUpload,
    useClientQuery,
    useConnectionStatus,
    useFileInput,
    useFlag,
    useFlags,
    useHttpStream,
    useImpersonate,
    useInfiniteQuery,
    useLunora,
    useMultipartUpload,
    useMutation,
    useMutator,
    useOrganizations,
    usePaginatedQuery,
    usePasteUpload,
    usePreloadedQuery,
    usePresence,
    useQuery,
    useRateLimit,
    useStream,
    useSubscription,
    useTusUpload,
    useUpload,
    useVoiceAgent,
} from "@lunora/react";
