/**
 * Public types for `@cirrus/workflow`. Everything here is Node-safe — the
 * Cloudflare Workflows runtime types are mirrored STRUCTURALLY (the `*Like`
 * interfaces) so this module needs no `@cloudflare/workers-types` and stays
 * importable from codegen, `@cirrus/config`, and app unit tests. The shapes are
 * kept in lockstep with `@cloudflare/workers-types`' `Workflow` /
 * `WorkflowInstance` / `WorkflowStep` / `WorkflowEvent` declarations.
 */

/**
 * Opaque reference to a Cirrus function. Mirrors the `FunctionReference` shape
 * emitted by `@cirrus/codegen` (and consumed by `@cirrus/client`). We avoid a
 * direct dependency to keep this package usable from the codegen pipeline
 * itself — identical rationale to `@cirrus/scheduler`'s copy.
 *
 * The runtime identifier lives in `__cirrusRef` — this MUST stay in lockstep
 * with the codegen emit + `@cirrus/client`'s `FunctionReference`.
 */
export interface FunctionReference {
    readonly __cirrusRef: string;
    /** Marker phantom type — discriminates queries / mutations / actions. */
    readonly _kind?: "query" | "mutation" | "action";
}

export type ArgsOf<F extends FunctionReference> = F extends { _args?: infer A } ? A : Record<string, unknown>;

// --- Structural mirror of the Cloudflare Workflows runtime ----------------

/** A workflow instance's lifecycle status. Mirrors `WorkflowInstanceStatus`. */
export type WorkflowInstanceStatus = "complete" | "errored" | "paused" | "queued" | "running" | "terminated" | "unknown" | "waiting" | "waitingForPause";

/** Result of `WorkflowInstance.status()`. Mirrors Cloudflare's `InstanceStatus`. */
export interface WorkflowStatusResult {
    error?: { message: string; name: string };
    output?: unknown;
    status: WorkflowInstanceStatus;
}

/** Options accepted by `Workflow.create`. Mirrors `WorkflowInstanceCreateOptions`. */
export interface WorkflowCreateOptions<Params = Record<string, unknown>> {
    /** Unique-within-the-workflow instance id. Generated by Cloudflare when omitted. */
    id?: string;
    /** The event payload the instance is triggered with — surfaced as `event.payload`. */
    params?: Params;
    /** Instance retention policy (defaults to the account maximum). */
    retention?: { errorRetention?: string; successRetention?: string };
}

/** A live handle to a single workflow instance. Mirrors `WorkflowInstance`. */
export interface WorkflowInstanceLike {
    readonly id: string;
    pause: () => Promise<void>;
    restart: () => Promise<void>;
    resume: () => Promise<void>;
    sendEvent: (event: { payload: unknown; type: string }) => Promise<void>;
    status: () => Promise<WorkflowStatusResult>;
    terminate: () => Promise<void>;
}

/**
 * The subset of the Cloudflare `Workflow` binding the package consumes.
 * `createBatch` is a non-optional method on the real binding (Cloudflare's
 * `Workflow` class declares it unconditionally), so it is required here too —
 * the handle never has to guard for its absence.
 */
export interface WorkflowBindingLike<Params = Record<string, unknown>> {
    create: (options?: WorkflowCreateOptions<Params>) => Promise<WorkflowInstanceLike>;
    createBatch: (batch: ReadonlyArray<WorkflowCreateOptions<Params>>) => Promise<WorkflowInstanceLike[]>;
    get: (id: string) => Promise<WorkflowInstanceLike>;
}

/** The `event` argument a workflow `run` receives. Mirrors `WorkflowEvent&lt;T>`. */
export interface WorkflowEventLike<Params = Record<string, unknown>> {
    readonly instanceId: string;
    readonly payload: Readonly<Params>;
    readonly timestamp: Date;
    readonly workflowName: string;
}

/** Per-step durability config. Mirrors the `WorkflowStepConfig.retries` shape. */
export interface WorkflowStepConfigLike {
    retries?: {
        backoff?: "constant" | "exponential" | "linear";
        delay?: number | string;
        limit: number;
    };
    timeout?: number | string;
}

/**
 * The durable step API Cloudflare hands the workflow body. Mirrors
 * `WorkflowStep` — `do` memoizes + retries its callback, `sleep`/`sleepUntil`
 * are durable delays, and `waitForEvent` hibernates until an external event.
 */
export interface WorkflowStepLike {
    do: <T>(name: string, configOrCallback: WorkflowStepConfigLike | (() => Promise<T>), callback?: () => Promise<T>) => Promise<T>;
    sleep: (name: string, duration: number | string) => Promise<void>;
    sleepUntil: (name: string, timestamp: Date | number) => Promise<void>;
    waitForEvent: <T = unknown>(name: string, options: { timeout?: number | string; type: string }) => Promise<{ payload: Readonly<T>; type: string }>;
}

// --- The Cirrus-flavored workflow authoring surface ------------------------

/** Minimal structured logger handed to the workflow body. */
export interface WorkflowLogger {
    debug: (message: string, ...rest: unknown[]) => void;
    error: (message: string, ...rest: unknown[]) => void;
    info: (message: string, ...rest: unknown[]) => void;
    warn: (message: string, ...rest: unknown[]) => void;
}

/** Per-call options for {@link WorkflowRunFunction}. */
export interface RunFunctionOptions {
    /** Routing hint forwarded to the Worker so the call lands on the right shard. */
    shardKey?: string;
}

/**
 * Calls a Cirrus query / mutation / action from inside a workflow and resolves
 * with its result. Wrap it in {@link WorkflowStepLike.do} to make the call a
 * durable, memoized, retried step:
 *
 * ```ts
 * const charge = await ctx.step.do("charge", () => ctx.run(api.payments.charge, { id }));
 * ```
 */
export type WorkflowRunFunction = <F extends FunctionReference>(function_: F, args?: ArgsOf<F>, options?: RunFunctionOptions) => Promise<unknown>;

/**
 * The context object passed to a `defineWorkflow` handler. Bundles the native
 * Cloudflare durability primitives (`step`, `event`) with the Cirrus runner
 * (`run`), the Worker `env`, and a logger.
 */
export interface WorkflowRunContext<Params = Record<string, unknown>> {
    /** The Worker environment bindings. */
    readonly env: Record<string, unknown>;
    /** The triggering event (id, payload, timestamp, workflow name). */
    readonly event: WorkflowEventLike<Params>;
    /** Structured logger surfaced in `wrangler tail` / Studio logs. */
    readonly log: WorkflowLogger;
    /** Convenience alias for `event.payload`. */
    readonly params: Readonly<Params>;
    /** Invoke a Cirrus function; wrap in `step.do(...)` for durability. */
    readonly run: WorkflowRunFunction;
    /** The native Cloudflare Workflows durable-step API. */
    readonly step: WorkflowStepLike;
}

/** The workflow body. Receives a {@link WorkflowRunContext}, returns the output. */
export type WorkflowHandler<Params = Record<string, unknown>, Output = unknown> = (context: WorkflowRunContext<Params>) => Output | Promise<Output>;

/** Author-supplied config for `defineWorkflow`. */
export interface WorkflowConfig<Params = Record<string, unknown>, Output = unknown> {
    /** The workflow body — the multi-step durable program. */
    handler: WorkflowHandler<Params, Output>;

    /**
     * Optional override for the deployed workflow name — the `workflows[].name`
     * written to `wrangler.jsonc`. Defaults to a kebab-cased form of the
     * `cirrus/workflows.ts` export name (`orderPipeline` → `order-pipeline`).
     * This does NOT change the binding name, which is always derived from the
     * export name (`orderPipeline` → `WORKFLOW_ORDER_PIPELINE`).
     */
    name?: string;
}

/**
 * A `defineWorkflow` result — the config plus the runtime brand codegen and the
 * config layer use to discover it. The phantom `__params` / `__output` carry
 * the inferred types to the generated `ctx.workflows` handle.
 */
export interface WorkflowDefinition<Params = Record<string, unknown>, Output = unknown> extends WorkflowConfig<Params, Output> {
    /** Phantom marker for the output type — never present at runtime. */
    readonly __output?: Output;
    /** Phantom marker for the params type — never present at runtime. */
    readonly __params?: Params;
    /** Runtime brand check (see `isWorkflowDefinition`). */
    readonly isCirrusWorkflow: true;
}

// --- The `ctx.workflows` action/mutation surface ---------------------------

/**
 * A typed handle to one declared workflow, addressable from `ctx.workflows`.
 * Thin pass-through over the Cloudflare `Workflow` binding.
 */
export interface WorkflowHandle<Params = Record<string, unknown>> {
    /** Start a new instance (optionally with an id + params). */
    create: (options?: WorkflowCreateOptions<Params>) => Promise<WorkflowInstanceLike>;
    /** Start many instances in one batched RPC. */
    createBatch: (batch: ReadonlyArray<WorkflowCreateOptions<Params>>) => Promise<WorkflowInstanceLike[]>;
    /** Get a handle to an existing instance by id. */
    get: (id: string) => Promise<WorkflowInstanceLike>;
}

/**
 * The `ctx.workflows` surface available on `MutationCtx` and `ActionCtx`. Each
 * declared workflow is reachable by its `cirrus/workflows.ts` export name.
 */
export interface Workflows {
    /** Resolve the handle for a declared workflow by export name. */
    get: <Params = Record<string, unknown>>(name: string) => WorkflowHandle<Params>;
}

/** Options for `createWorkflows`. */
export interface CirrusWorkflowsOptions {
    /**
     * Map of `cirrus/workflows.ts` export name → its Cloudflare `Workflow`
     * binding. Codegen builds this from `env` (`{ orderPipeline:
     * env.WORKFLOW_ORDER_PIPELINE }`); for manual wiring construct it yourself.
     */
    bindings: Record<string, WorkflowBindingLike>;
}
