// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/client";
import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    cleanup: {
        purgeStaleDrafts: FunctionReference<"mutation", {}, { deleted: number; }>;
    };
    drafts: {
        listMine: FunctionReference<"query", {}, { _id: Id<"drafts">; authorId: Id<"users">; body: string; title: string; updatedAt: number }[]>;
        save: FunctionReference<"mutation", { id?: Id<"drafts">; title: string; body: string }, Id<"drafts">>;
    };
    posts: {
        get: FunctionReference<"query", { id: Id<"posts"> }, null | { _id: Id<"posts">; authorId: Id<"users">; body: string; imageKey?: string; publishedAt: number; title: string }>;
        list: FunctionReference<"query", {}, { _id: Id<"posts">; authorId: Id<"users">; body: string; imageKey?: string; publishedAt: number; title: string }[]>;
        publish: FunctionReference<"mutation", { title: string; body: string; imageKey?: string }, Id<"posts">>;
        requestImageUpload: FunctionReference<"action", { contentType: string }, { key: string; url: string; }>;
        search: FunctionReference<"query", { text: string; topK?: number }, { id: Id<"posts">; score: number; title: string; }[]>;
    };
}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {}

export const internal = anyApi as unknown as InternalApiTypes;
