// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export type TableName = "users" | "posts" | "drafts";

/**
 * The tables **this app declared** — every {@link TableName} except those an add-on
 * contributed through `defineSchema(...).extend(...)`.
 *
 * An add-on's tables are real tables and stay in `TableName` (they are queryable,
 * they appear in `DataModel`), but an app enumerating "my tables" should not have to
 * know they exist: an account-deletion sweep, an export, a migration allowlist, or a
 * helper generic over a table union is about the app's own data, and every add-on
 * added or removed would otherwise silently change the correct answer.
 *
 * ```ts
 * // Doesn't need to mention `ratelimit_buckets`, and won't drift when an add-on lands.
 * const EXPORTED: readonly AppTableName[] = ["nodes", "tagColors"];
 * ```
 */
export type AppTableName = "users" | "posts" | "drafts";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_users {
    _id: Id<"users">;
    _creationTime: number;
    email: string;
    name: string;
    passwordHash: string;
}

export interface Doc_posts {
    _id: Id<"posts">;
    _creationTime: number;
    authorId: Id<"users">;
    title: string;
    body: string;
    imageKey?: string;
    publishedAt: number;
}

export interface Doc_drafts {
    _id: Id<"drafts">;
    _creationTime: number;
    authorId: Id<"users">;
    title: string;
    body: string;
    updatedAt: number;
}

export interface DataModel {
    users: Doc_users;
    posts: Doc_posts;
    drafts: Doc_drafts;
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. `never` for tables without secondary indexes.
 * Used by `TableReader.withIndex()` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
    users: "by_email";
    posts: "by_published";
    drafts: "by_updated";
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. `never` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
    users: never;
    posts: never;
    drafts: never;
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Per-table rank-index name union. `never` for tables without a rankIndex. */
export interface RankIndexNamesByTable {
    users: never;
    posts: never;
    drafts: never;
}

export type RankIndexName<T extends keyof DataModel> = RankIndexNamesByTable[T];

/** Per-table geo-index name union. `never` for tables without a geoIndex. */
export interface GeoIndexNamesByTable {
    users: never;
    posts: never;
    drafts: never;
}

export type GeoIndexName<T extends keyof DataModel> = GeoIndexNamesByTable[T];

/** Union of declared vector index names. `never` when none are declared. */
export type VectorIndexName = "posts_search";

export interface Insert_users {
    _id?: Id<"users">;
    _creationTime?: number;
    email: string;
    name: string;
    passwordHash: string;
}

export interface Insert_posts {
    _id?: Id<"posts">;
    _creationTime?: number;
    authorId: Id<"users">;
    title: string;
    body: string;
    imageKey?: string;
    publishedAt: number;
}

export interface Insert_drafts {
    _id?: Id<"drafts">;
    _creationTime?: number;
    authorId: Id<"users">;
    title: string;
    body: string;
    updatedAt: number;
}

/** Per-table insert shape, accepted by `ctx.db.<table>.insert(...)`. */
export interface InsertModel {
    users: Insert_users;
    posts: Insert_posts;
    drafts: Insert_drafts;
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the `with` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. `{}` for tables with none. */
export interface Relations {
    users: {};
    posts: {};
    drafts: {};
}

