// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const posts = sqliteTable("posts", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    authorId: text("authorId").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    imageKey: text("imageKey"),
    publishedAt: real("publishedAt").notNull(),
}, (t) => ({
    by_published: index("by_published").on(t.publishedAt),
}));

export const drafts = sqliteTable("drafts", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    authorId: text("authorId").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_updated: index("by_updated").on(t.updatedAt),
}));
