// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

export interface ApiTypes {
    documents: {
        summarise: FunctionReference<"action", { prompt: string }, { completed: string; parsed: string; }>;
    };
}

export const api: ApiTypes = {
    documents: {
        summarise: { __lunoraRef: "documents:summarise" },
    },
};
