// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "@lunora/client";
import type { FunctionReference } from "@lunora/client";

export interface ApiTypes {
    notes: {
        add: FunctionReference<"mutation", { body: string; boardId: string }, unknown>;
        list: FunctionReference<"query", { boardId: string }, unknown>;
    };
}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {}

export const internal = anyApi as unknown as InternalApiTypes;
