// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const messages = sqliteTable("messages", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    text: text("text").notNull(),
    author: text("author").notNull(),
    createdAt: real("createdAt").notNull(),
}, (t) => ({
    by_creation: index("by_creation").on(t.createdAt),
}));

export const ratelimit_buckets = sqliteTable("ratelimit_buckets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    value: real("value").notNull(),
    ts: real("ts").notNull(),
    prev: real("prev"),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));
