// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import { anyApi } from "@cirrus/server/types";
import type { FunctionReference } from "@cirrus/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    todos: {
        add: FunctionReference<"mutation", { text: string }, Id<"todos">>;
        list: FunctionReference<"query", {}, unknown>;
        remove: FunctionReference<"mutation", { id: Id<"todos"> }, void>;
        toggle: FunctionReference<"mutation", { id: Id<"todos">; done: boolean }, void>;
    };
}

export const api = anyApi as unknown as ApiTypes;
