// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import type { AdvisoryFinding, DatabaseWriterLike, DataMigrationLike, LogSink, MigrationRunResult, RunShardApplyCdcArgs, RunShardMigrationArgs, RlsPoliciesResult, RunShardRankBeforeArgs, RunShardRankPageArgs, RunShardWriteArgs, RunShardWriteResult, SchedulerLike, SchemaLike, ShardDOState, ShardRankPageResult, SqlExec, StorageRulesResult, SystemReaderStorageLike } from "@cirrus/do";
import { applyCdcChanges, createShardCtxDb, runDataMigration, runShardMigrations, ShardDO as ShardDOBase } from "@cirrus/do";
import { bindOrm, bindTableFacade } from "@cirrus/server";

import schema from "../schema.js";
import { CIRRUS_FUNCTIONS, CIRRUS_MIGRATIONS } from "./functions.js";

type FunctionKind = "action" | "mutation" | "query";

interface FunctionReference {
    __cirrusRef: string;
}

/** Foreign-key columns per table (`v.id("target")` fields) for the data browser. */
const CIRRUS_TABLE_REFS: Record<string, Record<string, string>> = {};

/** Declared indexes per table (secondary, search, rank, vector) for the schema viewer. */
const CIRRUS_TABLE_INDEXES: Record<string, Array<{ fields: string[]; name: string; type: "index" | "rank" | "search" | "vector"; unique?: boolean }>> = {
    "todos": [
        {
            "fields": [
                "createdAt"
            ],
            "name": "by_creation",
            "type": "index"
        }
    ]
};

/** Storage-key columns per table (`v.storage(...)` fields) for the file browser's records↔files join. */
const CIRRUS_STORAGE_COLUMNS: Record<string, string[]> = {};

/** Static schema advisories (computed by @cirrus/advisor at codegen time) served via `__cirrus_admin__:getAdvisories`. */
const CIRRUS_ADVISORIES: AdvisoryFinding[] = [];

/** Read-only RLS metadata (policies + roles discovered from `.use(rls(...))` chains) served via `__cirrus_admin__:rlsPolicies` for the studio's RLS inspector. */
const CIRRUS_RLS_METADATA: RlsPoliciesResult = {
    "policies": [],
    "roles": []
};

/** Read-only storage access-rule metadata (discovered from `.use(storageRules(...))` chains) served via `__cirrus_admin__:storageRules` for the studio's access-rules view. */
const CIRRUS_STORAGE_RULES: StorageRulesResult = {
    "rules": []
};

export interface ShardDOConfig {
    /** Opt into change-data-capture: records a post-image to `__cdc_log` on every write (backs streaming export + replay-PITR). */
    cdc?: boolean;
    /** Optional telemetry sink. When supplied, each `ctx.log.*` call is forwarded to `sink.onLog`. Pass the SAME sink you give `createWorker({ observability })` (which drives `onRpc`) to route both RPC and log events. */
    observability?: (env: Record<string, unknown>) => LogSink | undefined;
    scheduler?: (env: Record<string, unknown>) => unknown;
    storage?: (env: Record<string, unknown>) => unknown;
}

const schedulerStub = {
    cancel: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAfter: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAt: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
};

const storageStub = {
    delete: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    download: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getMetadata: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getSignedUrl: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getUrl: () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    list: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    upload: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
};

// Bound in-process `ctx.run*` composition depth so a self- or cyclically-
// referencing call fails loudly with a clear error instead of overflowing the
// stack. Tracked across the awaited handler chain (one DO invocation is
// single-threaded), so the counter reflects true nesting depth.
const MAX_RUN_DEPTH = 32;
let runDepth = 0;

const dispatchRun = async (expected: FunctionKind, functionPath: string, args: Record<string, unknown>, ctx: unknown): Promise<unknown> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw new Error(`unknown function: ${functionPath}`);
    }

    if (registered.kind !== expected) {
        throw new Error(`ctx.run${expected[0]!.toUpperCase()}${expected.slice(1)}: "${functionPath}" is registered as a ${registered.kind}, not a ${expected}`);
    }

    if (runDepth >= MAX_RUN_DEPTH) {
        throw Object.assign(new Error(`ctx.run*: composition depth limit (${MAX_RUN_DEPTH}) exceeded — likely a cyclic runQuery/runMutation`), {
            name: "CirrusError",
            code: "RUN_DEPTH_EXCEEDED",
            status: 500,
        });
    }

    runDepth += 1;

    try {
        return await registered.handler(ctx, args);
    } finally {
        runDepth -= 1;
    }
};

/**
 * Build the project's shard Durable Object. Export the result as `ShardDO`
 * from the worker entry so wrangler binds it by name.
 */
export const createShardDO = (config: ShardDOConfig = {}): new (state: ShardDOState, env: unknown) => ShardDOBase =>
    class extends ShardDOBase {
        private migrated = false;

        public override async handleRpc(functionPath: string, args: Record<string, unknown>): Promise<unknown> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            // Internal functions are reachable server-side only: via `ctx.run*`
            // composition, or a trusted system dispatch (scheduler/cron, marked by
            // `isSystemDispatch()`). A client RPC never carries that flag, so its
            // internals stay not-found and never leak across the external boundary.
            if (!registered || (registered.visibility === "internal" && !this.isSystemDispatch())) {
                throw Object.assign(new Error(`function not registered: ${functionPath}`), {
                    name: "CirrusError",
                    code: "FUNCTION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            return registered.handler(this.buildCtx({ functionPath }), args);
        }

        protected override async executeSubscription(functionPath: string, args: Record<string, unknown>): Promise<{ result: unknown; tables: Set<string> } | null> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "query" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            const tables = new Set<string>();
            const ctx = this.buildCtx({ functionPath, onRead: (table) => tables.add(table) });
            const result = await registered.handler(ctx, args);

            return { result, tables };
        }

        protected override executeStream(functionPath: string, args: Record<string, unknown>): null | { iterator: (signal: AbortSignal) => AsyncIterable<unknown> } {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "stream" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            return {
                iterator: (signal) => (registered.handler as (context: unknown, args: Record<string, unknown>, signal: AbortSignal) => AsyncIterable<unknown>)(this.buildCtx({ functionPath }), args, signal),
            };
        }

        protected override tableRefs(table: string): Record<string, string> | undefined {
            return CIRRUS_TABLE_REFS[table];
        }

        protected override tableIndexes(table: string): Array<{ fields: string[]; name: string; type: "index" | "rank" | "search" | "vector"; unique?: boolean }> {
            return CIRRUS_TABLE_INDEXES[table] ?? [];
        }

        protected override storageColumns(): Record<string, string[]> {
            return CIRRUS_STORAGE_COLUMNS;
        }

        protected override rlsMetadata(): RlsPoliciesResult {
            return CIRRUS_RLS_METADATA;
        }

        protected override storageRulesMetadata(): StorageRulesResult {
            return CIRRUS_STORAGE_RULES;
        }

        protected override advisories(): AdvisoryFinding[] {
            return CIRRUS_ADVISORIES;
        }

        protected override async runShardDataMigration(args: RunShardMigrationArgs): Promise<MigrationRunResult> {
            const migration = CIRRUS_MIGRATIONS[args.id];

            if (!migration) {
                throw Object.assign(new Error(`data migration "${args.id}" is not registered`), {
                    name: "CirrusError",
                    code: "MIGRATION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            return runDataMigration({
                batchSize: args.batchSize,
                direction: args.direction,
                dryRun: args.dryRun,
                maxBatches: args.maxBatches,
                migration: migration as unknown as DataMigrationLike,
                // Flush after each batch so live migrationStatus subscribers see
                // progress mid-run (the base method records the reserved state
                // table the raw-SQL progress write is invisible to the tracker).
                onBatch: () => this.flushMigrationProgress(),
                sql: this.sql as SqlExec,
                writer,
            });
        }

        protected override async runShardWrite(args: RunShardWriteArgs): Promise<RunShardWriteResult> {
            const definition = (schema as unknown as SchemaLike).tables[args.table];

            if (!definition) {
                throw Object.assign(new Error(`unknown table: ${args.table}`), { name: "CirrusError", code: "UNKNOWN_TABLE", status: 404 });
            }

            // `.global()` tables live in D1, not this DO's SQLite — editing them
            // here would corrupt nothing but would fail confusingly, so reject up
            // front with a clear code the studio can surface.
            if (definition.shardMode?.kind === "global") {
                throw Object.assign(new Error(`table "${args.table}" is global; edit it through D1, not the shard`), {
                    name: "CirrusError",
                    code: "GLOBAL_TABLE_NOT_EDITABLE",
                    status: 400,
                });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            if (args.op === "insert") {
                const id = await writer.insert(args.table, args.doc ?? {});

                return { id, op: "insert" };
            }

            if (args.op === "delete") {
                await writer.delete(args.id ?? "");

                return { id: args.id ?? null, op: "delete" };
            }

            if (args.op === "replace") {
                await writer.replace(args.id ?? "", args.doc ?? {});

                return { id: args.id ?? null, op: "replace" };
            }

            await writer.patch(args.id ?? "", args.doc ?? {});

            return { id: args.id ?? null, op: "patch" };
        }

        protected override async deleteRowThroughWriter(table: string, id: string): Promise<void> {
            const definition = (schema as unknown as SchemaLike).tables[table];

            if (!definition) {
                throw Object.assign(new Error(`unknown table: ${table}`), { name: "CirrusError", code: "UNKNOWN_TABLE", status: 404 });
            }

            // `.global()` tables live in D1, not this DO's SQLite — the same
            // guard `runShardWrite` applies to single-row edits.
            if (definition.shardMode?.kind === "global") {
                throw Object.assign(new Error(`table "${table}" is global; edit it through D1, not the shard`), {
                    name: "CirrusError",
                    code: "GLOBAL_TABLE_NOT_EDITABLE",
                    status: 400,
                });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // Routes through the writer (not raw SQL) so FTS / aggregate / rank
            // shadow tables stay in sync and `onDelete` cascades fire — the
            // bounded loop lives in the base `runShardBulkDelete`.
            await writer.delete(id);
        }

        protected override async runShardRankBefore(args: RunShardRankBeforeArgs): Promise<{ before: number; total: number }> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // `rankBefore` is optional on `DatabaseWriterLike` (the D1 twin omits it),
            // but the shard writer from `createShardCtxDb` always defines it.
            if (!writer.rankBefore) {
                throw Object.assign(new Error("rankBefore is unavailable on the shard writer"), { name: "CirrusError", code: "NOT_IMPLEMENTED", status: 500 });
            }

            return writer.rankBefore(args.table, args.index, {
                partitionKey: args.partitionKey,
                rowId: args.rowId,
                sortValues: args.sortValues,
            });
        }

        protected override async runShardRankPage(args: RunShardRankPageArgs): Promise<ShardRankPageResult> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // `rankPageRows` is optional on `DatabaseWriterLike` (the D1 twin omits it),
            // but the shard writer from `createShardCtxDb` always defines it. The sort
            // directions live in the schema's rankIndex, so the shard reads them itself;
            // `args.directions` is only the coordinator's comparator hint and isn't forwarded.
            if (!writer.rankPageRows) {
                throw Object.assign(new Error("rankPage is unavailable on the shard writer"), { name: "CirrusError", code: "NOT_IMPLEMENTED", status: 500 });
            }

            return writer.rankPageRows(args.table, args.index, {
                after: args.after,
                cursor: args.cursor,
                partitionKey: args.partitionKey,
                take: args.take,
            });
        }

        protected override async runShardApplyCdc(args: RunShardApplyCdcArgs): Promise<{ applied: number }> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            await applyCdcChanges(writer, args.changes);

            return { applied: args.changes.length };
        }

        protected override ensureMigrated(): void {
            if (this.migrated) {
                return;
            }

            runShardMigrations(this.sql as SqlExec, schema as unknown as SchemaLike, { cdc: config.cdc ?? false });
            this.migrated = true;
        }

        private buildCtx(options: { functionPath?: string; onRead?: (table: string) => void } = {}): unknown {
            const env = (this.env ?? {}) as Record<string, unknown>;
            const userId = this.getCurrentUserId();
            const identity = this.getCurrentIdentity();

            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            // Build the storage adapter once and share it between `ctx.storage`
            // and `ctx.db.system._storage` so both read the same R2 binding. The
            // `storageStub` fallback satisfies SystemReaderStorageLike structurally
            // (its `list`/`getMetadata` throw the "no storage configured" error).
            const storage = (config.storage?.(env) ?? storageStub) as unknown as SystemReaderStorageLike;
            const db: DatabaseWriterLike = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                onIndexUse: this.getCtxDbIndexUseHook(),
                onRead: options.onRead ?? this.getCtxDbReadHook(),
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
                storage,
            });

            const facade = db as unknown as Record<string, ReturnType<typeof bindTableFacade>>;
            facade["todos"] = bindTableFacade(db, "todos");

            // `ctx.log`: each call is captured + attributed to the executing
            // function and routed to the optional `observability` sink. The DO base
            // also buffers it (studio Logs panel) and emits a structured console
            // event the dev-server formats in the terminal.
            const observability = config.observability?.(env);
            const logFunctionPath = options.functionPath ?? "";
            const log = {
                debug: (...args: unknown[]) => { this.recordUserLog(logFunctionPath, "debug", args, observability); },
                error: (...args: unknown[]) => { this.recordUserLog(logFunctionPath, "error", args, observability); },
                info: (...args: unknown[]) => { this.recordUserLog(logFunctionPath, "info", args, observability); },
                log: (...args: unknown[]) => { this.recordUserLog(logFunctionPath, "log", args, observability); },
                warn: (...args: unknown[]) => { this.recordUserLog(logFunctionPath, "warn", args, observability); },
            };

            const ctx: Record<string, unknown> = {
                auth: {
                    getIdentity: async () => identity ?? null,
                    userId: userId ?? null,
                },
                db,
                fetch: globalThis.fetch.bind(globalThis),
                log,
                orm: bindOrm(facade),
                scheduler,
                storage,
            };

            ctx.runAction = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("action", reference.__cirrusRef, fnArgs, ctx);
            ctx.runMutation = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("mutation", reference.__cirrusRef, fnArgs, ctx);
            ctx.runQuery = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("query", reference.__cirrusRef, fnArgs, ctx);

            return ctx;
        }
    };
