// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    tasks: {
        create: FunctionReference<"mutation", { title: string; status?: "todo" | "in-progress" | "done" | "archived" }, Id<"tasks">>;
        list: FunctionReference<"query", {}, import("./dataModel.js").Doc_tasks[]>;
        move: FunctionReference<"mutation", { id: Id<"tasks">; status: "todo" | "in-progress" | "done" | "archived"; index: number }, void>;
        remove: FunctionReference<"mutation", { id: Id<"tasks"> }, void>;
        rename: FunctionReference<"mutation", { id: Id<"tasks">; title: string }, void>;
    };
}

export const api: ApiTypes = {
    tasks: {
        create: { __lunoraRef: "tasks:create" },
        list: { __lunoraRef: "tasks:list" },
        move: { __lunoraRef: "tasks:move" },
        remove: { __lunoraRef: "tasks:remove" },
        rename: { __lunoraRef: "tasks:rename" },
    },
};
