// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const tasks = sqliteTable("tasks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    title: text("title").notNull(),
    status: text("status", { mode: "json" }).$type<"todo" | "in-progress" | "done" | "archived">().notNull(),
    order: text("order").notNull(),
}, (t) => ({
    by_status_and_order: index("by_status_and_order").on(t.status, t.order),
}));

export const ratelimit_buckets = sqliteTable("ratelimit_buckets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    value: real("value").notNull(),
    ts: real("ts").notNull(),
    prev: real("prev"),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));
