// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, sqliteTable, text } from "lunorash/server/drizzle";

export const tasks = sqliteTable("tasks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    title: text("title").notNull(),
    status: text("status", { mode: "json" }).$type<"todo" | "in-progress" | "done" | "archived">().notNull(),
    order: text("order").notNull(),
}, (t) => ({
    by_status_and_order: index("by_status_and_order").on(t.status, t.order),
}));
