// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/client";
import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    feedback: {
        addComment: FunctionReference<"mutation", { feedbackId: Id<"feedback">; authorName: string; authorEmail?: string; content: string; isOfficial?: boolean }, Id<"comments">>;
        comments: FunctionReference<"query", { feedbackId: Id<"feedback"> }, import("./dataModel.js").Doc_comments[]>;
        create: FunctionReference<"mutation", { title: string; description: string; authorName: string; authorEmail?: string; tags?: Array<string> }, Id<"feedback">>;
        get: FunctionReference<"query", { id: Id<"feedback"> }, import("./dataModel.js").Doc_feedback | null>;
        list: FunctionReference<"query", { status?: "open" | "under-review" | "planned" | "in-progress" | "completed" | "closed"; sortBy?: "votes" | "recent" }, import("./dataModel.js").Doc_feedback[]>;
        myVotes: FunctionReference<"query", { voterEmail: string }, Id<"feedback">[]>;
        remove: FunctionReference<"mutation", { id: Id<"feedback"> }, void>;
        setStatus: FunctionReference<"mutation", { id: Id<"feedback">; status: "open" | "under-review" | "planned" | "in-progress" | "completed" | "closed" }, void>;
        toggleVote: FunctionReference<"mutation", { feedbackId: Id<"feedback">; voterEmail: string }, { voted: boolean; }>;
    };
    summaries: {
        generate: FunctionReference<"action", { limit?: number }, Id<"summaries"> | null>;
        list: FunctionReference<"query", {}, import("./dataModel.js").Doc_summaries[]>;
        remove: FunctionReference<"mutation", { id: Id<"summaries"> }, void>;
    };
}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {
    summaries: {
        store: FunctionReference<"mutation", { title: string; summary: string; feedbackIds: Array<Id<"feedback">> }, Id<"summaries">>;
    };
}

export const internal = anyApi as unknown as InternalApiTypes;
