// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text, uniqueIndex } from "lunorash/server/drizzle";
import type { AnySQLiteColumn } from "lunorash/server/drizzle";
import type { Id } from "./dataModel.js";

export const feedback = sqliteTable("feedback", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    status: text("status", { mode: "json" }).$type<"open" | "under-review" | "planned" | "in-progress" | "completed" | "closed">().notNull(),
    authorName: text("authorName").notNull(),
    authorEmail: text("authorEmail"),
    upvoteCount: real("upvoteCount").notNull(),
    commentCount: real("commentCount").notNull(),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
}, (t) => ({
    by_upvotes: index("by_upvotes").on(t.upvoteCount),
    by_status: index("by_status").on(t.status),
}));

export const votes = sqliteTable("votes", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    feedbackId: text("feedbackId").references((): AnySQLiteColumn => feedback._id).notNull(),
    voterEmail: text("voterEmail").notNull(),
}, (t) => ({
    by_voter: index("by_voter").on(t.voterEmail),
    by_feedback_and_voter: uniqueIndex("by_feedback_and_voter").on(t.feedbackId, t.voterEmail),
}));

export const comments = sqliteTable("comments", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    feedbackId: text("feedbackId").references((): AnySQLiteColumn => feedback._id).notNull(),
    authorName: text("authorName").notNull(),
    authorEmail: text("authorEmail"),
    content: text("content").notNull(),
    isOfficial: integer("isOfficial", { mode: "boolean" }).notNull(),
}, (t) => ({
    by_feedback: index("by_feedback").on(t.feedbackId),
}));

export const summaries = sqliteTable("summaries", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    title: text("title").notNull(),
    summary: text("summary").notNull(),
    feedbackIds: text("feedbackIds", { mode: "json" }).$type<Array<Id<"feedback">>>().notNull(),
    generatedAt: real("generatedAt").notNull(),
}, (t) => ({
    by_generated: index("by_generated").on(t.generatedAt),
}));
