// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const announcements = sqliteTable("announcements", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    body: text("body").notNull(),
    sentAt: real("sentAt").notNull(),
    title: text("title").notNull(),
}, (t) => ({
    by_sent: index("by_sent").on(t.sentAt),
}));
