// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_push_0 from "../push.js";

import { DEFER_VALIDATION as DEFER, installCompiledValidatorMap } from "lunorash/values";
import { LunoraError } from "lunorash/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";
import type { Id } from "./dataModel.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "push:announce": lunora_push_0.announce as unknown as RegisteredLunoraFunction,
    "push:broadcast": lunora_push_0.broadcast as unknown as RegisteredLunoraFunction,
    "push:listAnnouncements": lunora_push_0.listAnnouncements as unknown as RegisteredLunoraFunction,
    "push:registerDevice": lunora_push_0.registerDevice as unknown as RegisteredLunoraFunction,
};

/**
 * AOT-compiled argument validators (Worker-safe, no `eval`). Each is installed
 * onto its function's live `.args` object and consulted by the interpreted
 * parser as a zero-allocation fast path; anything it can't model is deferred.
 */
installCompiledValidatorMap(lunora_push_0.announce.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["body"] !== "string") return DEFER;
if (typeof source["title"] !== "string") return DEFER;
return { "body": source["body"], "title": source["title"] };
});
installCompiledValidatorMap(lunora_push_0.broadcast.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["body"] !== "string") return DEFER;
if (typeof source["title"] !== "string") return DEFER;
return { "body": source["body"], "title": source["title"] };
});
installCompiledValidatorMap(lunora_push_0.registerDevice.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
return { "subscription": source["subscription"] };
});

/**
 * Connection-lifecycle manifest: the function paths the generated ShardDO
 * dispatches when a client's WebSocket connects (`connect`) or disconnects
 * (`disconnect`). Each path also resolves through {@link LUNORA_FUNCTIONS}; the
 * DO runs every hook under the socket's verified identity via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[] } = {
    connect: [],
    disconnect: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    push: {
        announce: (args: { body: string; title: string }) => Promise<Id<"announcements">>;
        broadcast: (args: { body: string; title: string }) => Promise<{ failed: number; pruned: number; sent: number; total: number; }>;
        listAnnouncements: (args?: {}) => Promise<{ _id: Id<"announcements">; body: string; sentAt: number; title: string }[]>;
        registerDevice: (args: { subscription: unknown }) => Promise<void>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    push: {
        announce: (args) => callRegistered(context, "push:announce", args),
        broadcast: (args) => callRegistered(context, "push:broadcast", args),
        listAnnouncements: (args) => callRegistered(context, "push:listAnnouncements", args),
        registerDevice: (args) => callRegistered(context, "push:registerDevice", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
