// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/client";
import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    games: {
        get: FunctionReference<"query", { gameId: Id<"games"> }, import("./dataModel.js").Doc_games | null>;
        listActive: FunctionReference<"query", {}, import("./dataModel.js").Doc_games[]>;
        makeMove: FunctionReference<"mutation", { gameId: Id<"games">; from: string; to: string; promotion?: string }, { finished: boolean; }>;
        mine: FunctionReference<"query", {}, import("./dataModel.js").Doc_games[]>;
        moves: FunctionReference<"query", { gameId: Id<"games"> }, import("./dataModel.js").Doc_moves[]>;
        offerDraw: FunctionReference<"mutation", { gameId: Id<"games"> }, void>;
        resign: FunctionReference<"mutation", { gameId: Id<"games"> }, void>;
        respondToDraw: FunctionReference<"mutation", { gameId: Id<"games">; accept: boolean }, void>;
        start: FunctionReference<"mutation", { lobbyId: Id<"lobbies"> }, Id<"games">>;
    };
    lobby: {
        create: FunctionReference<"mutation", { isPrivate: boolean }, Id<"lobbies">>;
        join: FunctionReference<"mutation", { lobbyId: Id<"lobbies">; inviteCode?: string }, void>;
        joinByCode: FunctionReference<"mutation", { inviteCode: string }, Id<"lobbies">>;
        leave: FunctionReference<"mutation", { lobbyId: Id<"lobbies"> }, void>;
        listOpen: FunctionReference<"query", {}, import("./dataModel.js").Doc_lobbies[]>;
        mine: FunctionReference<"query", {}, (import("./dataModel.js").Doc_lobbies & { isHost: boolean; }) | null>;
        quickMatch: FunctionReference<"mutation", {}, Id<"lobbies">>;
    };
    players: {
        claim: FunctionReference<"mutation", { displayName?: string }, void>;
        leaderboard: FunctionReference<"query", {}, import("./dataModel.js").Doc_profiles[]>;
        list: FunctionReference<"query", {}, import("./dataModel.js").Doc_profiles[]>;
        me: FunctionReference<"query", {}, import("./dataModel.js").Doc_profiles | null>;
    };
}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {}

export const internal = anyApi as unknown as InternalApiTypes;
