import { createConfig } from "@anolilab/eslint-config";

// Self-contained flat config for @cirrus/auth. Each package owns its own
// setup (no shared local preset); rules build on @anolilab/eslint-config.
export default createConfig(
    {
        ignores: [
            "**/dist/**",
            "**/node_modules/**",
            "**/.next/**",
            "**/.source/**",
            "**/_generated/**",
            "**/__fixtures__/**",
            "**/fixtures/**",
            "**/test-results/**",
            "**/coverage/**",
            "**/.wrangler/**",
            "**/.history/**",
            "**/CHANGELOG.md",
            // Code fences inside markdown (e.g. DESIGN.md) are extracted as
            // virtual .ts files that aren't in any tsconfig, so type-aware
            // linting can't parse them — don't lint doc snippets as source.
            "**/*.md/**",
            "**/vitest.config.ts",
            "**/packem.config.ts",
            "**/vite.config.ts",
            "**/wrangler.jsonc",
            "**/package.json",
            "**/tsconfig*.json",
            "**/README.md",
            "**/prettier.config.js",
            "**/eslint.config.js",
        ],
    },
    // Base TypeScript overrides for all package sources. These rules are turned
    // off (or downgraded to warnings) while the Cirrus codebase adopts the
    // visulima style guide — each is a deferred refactor, active in CI as a
    // warning so current code passes lint.
    {
        files: ["**/*.{ts,tsx}"],
        rules: {
            "@stylistic/indent": "off",
            "@stylistic/jsx-one-expression-per-line": "off",
            "@stylistic/max-statements-per-line": "off",
            "@stylistic/multiline-ternary": "off",
            "@stylistic/no-extra-parens": "off",
            "@stylistic/operator-linebreak": "off",
            "@stylistic/quotes": "off",
            "@typescript-eslint/array-type": "off",
            "@typescript-eslint/explicit-member-accessibility": "off",
            "@typescript-eslint/member-ordering": "off",
            "@typescript-eslint/method-signature-style": "warn",
            "@typescript-eslint/naming-convention": "warn",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-confusing-void-expression": "warn",
            "@typescript-eslint/no-empty-object-type": "off",
            "@typescript-eslint/no-import-type-side-effects": "warn",
            "@typescript-eslint/no-misused-promises": "warn",
            "@typescript-eslint/no-non-null-assertion": "warn",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-shadow": "warn",
            "@typescript-eslint/no-this-alias": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-arguments": "warn",
            "@typescript-eslint/no-unnecessary-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-use-before-define": "warn",
            "@typescript-eslint/prefer-nullish-coalescing": "warn",
            "@typescript-eslint/prefer-optional-chain": "warn",
            "@typescript-eslint/prefer-promise-reject-errors": "warn",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-plus-operands": "warn",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "warn",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "warn",
            "arrow-body-style": "off",
            "class-methods-use-this": "off",
            "compat/compat": "off",
            "consistent-return": "warn",
            "e18e/prefer-static-regex": "off",
            "func-style": "off",
            "import/consistent-type-specifier-style": "off",
            "import/exports-last": "off",
            "import/no-commonjs": "off",
            "import/no-named-as-default-member": "off",
            "import/no-namespace": "off",
            "import/no-unresolved": "off",
            "import/prefer-default-export": "off",
            "jsdoc/check-indentation": "off",
            "jsdoc/escape-inline-tags": "off",
            "jsdoc/lines-before-block": "off",
            "jsdoc/match-description": "off",
            "jsdoc/no-undefined-types": "off",
            "jsdoc/require-param-type": "off",
            "jsdoc/text-escaping": "off",
            "markdown/heading-increment": "off",
            "max-classes-per-file": "off",
            "n/no-unsupported-features/es-builtins": "off",
            "n/no-unsupported-features/es-syntax": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "no-alert": "warn",
            "no-await-in-loop": "warn",
            "no-bitwise": "off",
            "no-confusing-arrow": "off",
            "no-dupe-keys": "warn",
            "no-empty-pattern": "warn",
            "no-param-reassign": "off",
            "no-promise-executor-return": "off",
            "no-restricted-syntax": "warn",
            "no-secrets/no-secrets": "warn",
            "no-underscore-dangle": "off",
            "no-useless-assignment": "warn",
            "no-void": "off",
            "perfectionist/sort-exports": "warn",
            "perfectionist/sort-interfaces": "warn",
            "perfectionist/sort-jsx-props": "off",
            "perfectionist/sort-object-types": "warn",
            "perfectionist/sort-objects": "off",
            "preserve-caught-error": "off",
            "promise/always-return": "warn",
            "promise/catch-or-return": "warn",
            "promise/param-names": "warn",
            "regexp/no-super-linear-backtracking": "warn",
            "regexp/no-unused-capturing-group": "warn",
            "regexp/optimal-quantifier-concatenation": "warn",
            "simple-import-sort/exports": "warn",
            "simple-import-sort/imports": "warn",
            "sonarjs/cognitive-complexity": "warn",
            "sonarjs/deprecation": "warn",
            "sonarjs/function-return-type": "warn",
            "sonarjs/no-alphabetical-sort": "off",
            "sonarjs/no-extra-arguments": "warn",
            "sonarjs/no-hardcoded-passwords": "warn",
            "sonarjs/no-nested-conditional": "warn",
            "sonarjs/no-nested-functions": "off",
            "sonarjs/no-unused-vars": "warn",
            "sonarjs/prefer-read-only-props": "warn",
            "sonarjs/pseudo-random": "off",
            "sonarjs/slow-regex": "warn",
            "sonarjs/void-use": "off",
            "unicorn/catch-error-name": "warn",
            "unicorn/filename-case": "off",
            "unicorn/no-anonymous-default-export": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-await-expression-member": "off",
            "unicorn/no-immediate-mutation": "warn",
            "unicorn/no-null": "off",
            "unicorn/no-object-as-default-parameter": "warn",
            "unicorn/no-process-exit": "off",
            "unicorn/no-this-assignment": "off",
            "unicorn/number-literal-case": "warn",
            "unicorn/numeric-separators-style": "warn",
            "unicorn/prefer-add-event-listener": "warn",
            "unicorn/prefer-code-point": "warn",
            "unicorn/prefer-global-this": "off",
            "unicorn/prefer-top-level-await": "off",
            "unicorn/prevent-abbreviations": "off",
            "unused-imports/no-unused-vars": "warn",
            "vars-on-top": "off",
            "vitest/consistent-test-it": "off",
            "vitest/expect-expect": "warn",
            "vitest/require-to-throw-message": "off",
        },
    },
    // Fixtures: allow `any` and loose typing.
    {
        files: ["**/__fixtures__/**/*.{ts,tsx}"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
        },
    },
    // Test files: relax rules.
    {
        files: ["**/__tests__/**/*.{ts,tsx}", "**/__bench__/**/*.{ts,tsx}", "**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}", "**/*.bench.{ts,tsx}"],
        rules: {
            "@stylistic/no-tabs": "off",
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/require-await": "off",
            "compat/compat": "off",
            "e18e/ban-dependencies": "off",
            "import/no-extraneous-dependencies": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "perfectionist/sort-objects": "off",
            "promise/always-return": "off",
            "sonarjs/no-control-regex": "off",
            "sonarjs/no-nested-functions": "off",
            "unicorn/no-null": "off",
            "vitest/no-conditional-expect": "off",
            "vitest/prefer-strict-equal": "off",
        },
    },
    // Markdown code blocks: don't enforce language tags.
    {
        files: ["**/*.md", "**/*.md/**"],
        rules: {
            "markdown/fenced-code-language": "off",
        },
    },
);
