import type { ShardNamespaceLike } from "lunorash/runtime";
// The handler `@sveltejs/adapter-cloudflare` emits for SvelteKit's SSR + routes.
// Resolves after the first `vite build`; `lunora dev` proxies SvelteKit's dev
// server, so it's only needed for the build.
// @ts-expect-error -- generated by `@sveltejs/adapter-cloudflare` at build time
import svelteKitWorker from "../.svelte-kit/cloudflare/_worker.js";

import { defineApp } from "../lunora/_generated/app.js";

interface Env extends Record<string, unknown> {
    SHARD: ShardNamespaceLike;
}

/**
 * Single-worker entry (PLAN4 §3, class-B), composed with the generated
 * `defineApp` builder. `.buildFrameworkWorker(svelteKitWorker)` folds the
 * adapter-emitted SvelteKit handler in as the framework host: the reserved
 * `/_lunora/{rpc,ws,admin}` endpoints route into Lunora (forwarded to the
 * `SHARD` Durable Object) and everything else — pages, endpoints, same-origin
 * `+page.ts` loaders — delegates to SvelteKit. One worker, one deploy, one
 * `ShardDO` namespace. Add `.storage()` / `.auth()` / `.global()` etc. as you
 * adopt those packages (codegen surfaces the methods automatically).
 */
const app = defineApp<Env>()
    .shard((env) => env.SHARD)
    // Demo/local default: this app has no auth, so shard access is left OPEN
    // (any caller may target any shard) and data is protected by per-row RLS.
    // A PRODUCTION sharded app must gate this instead — e.g.
    // `.extend(() => ({ authorizeShard: (identity, shardKey) => identity?.userId === ownerOf(shardKey) }))`.
    .extend(() => ({ allowUnauthenticatedShardAccess: true }))
    .buildFrameworkWorker(svelteKitWorker);

export const ShardDO = app.ShardDO;
export default app;
