import type { ShardNamespaceLike } from "lunorash/runtime";

import { defineApp } from "../lunora/_generated/app.js";
import vinextPagesWorker from "./vinext-pages";

interface Env extends Record<string, unknown> {
    ASSETS: Fetcher;
    SHARD: ShardNamespaceLike;
}

/**
 * Single-worker entry for Next.js Pages Router (vinext) + Lunora realtime,
 * composed with the generated `defineApp` builder.
 * `.buildFrameworkWorker(vinextPagesWorker)` folds vinext's generated Pages
 * worker in as the framework host: the reserved `/_lunora/{rpc,ws,admin}`
 * endpoints route into Lunora (forwarded to the `SHARD` Durable Object) and
 * everything else — pages, API routes, middleware — delegates to vinext's Pages
 * request pipeline. One worker, one deploy, one `ShardDO` namespace. Add
 * `.storage()` / `.auth()` / `.global()` etc. as you adopt those packages
 * (codegen surfaces the methods automatically).
 *
 * `worker/vinext-pages.ts` is generated by vinext (`vinext init --platform=cloudflare`);
 * it imports vinext's build-time virtual modules, so this entry must be built by
 * `vinext build` (which resolves them) — see package.json `build`/`deploy`.
 */
const app = defineApp<Env>()
    .shard((env) => env.SHARD)
    .buildFrameworkWorker(vinextPagesWorker);

export const ShardDO = app.ShardDO;
export default app;
