"""Lunora Python SDK — a minimal, protocol-conformant client for a Lunora deployment.

See ``protocol/README.md`` for the language-independent wire protocol this
implements, and ``sdks/python/README.md`` for usage.
"""

from .client import (
    LunoraClient,
    build_connect_frame,
    build_rpc_body,
    build_shape_subscribe_frame,
    build_subscribe_frame,
    build_unsubscribe_frame,
    parse_commit_cursor,
    parse_rpc_response,
)
from .errors import LunoraError, SubscriptionError
from .offline import (
    ABSENT_IDENTITY,
    CLIENT_CLOSED,
    OFFLINE_IDENTITY_CHANGED,
    OFFLINE_PRECONDITION_FAILED,
    OFFLINE_QUEUE_OVERFLOW,
    OFFLINE_WRITE_UNENCODABLE,
    Discarded,
    OfflineError,
    OfflineQueue,
    PersistenceAdapter,
    QueuedMutation,
    identity_allows_replay,
    is_stale_version,
    random_id,
)
from .optimistic import (
    OptimisticHandle,
    OptimisticLayer,
    OptimisticLocalStore,
    apply_optimistic_layer,
    confirm_all,
    drop_confirmed_layers,
    fold_optimistic,
    notify_subscription,
    rollback_all,
)
from .submit import (
    MAX_BATCH_ENTRIES,
    TRANSIENT_ERROR_CODES,
    FlushReport,
    MutationOutcome,
    MutationSettled,
    SubmitOptions,
)
from .wire import (
    TAG,
    UNDEFINED,
    WireBigInt,
    WireBytes,
    WireDate,
    WireError,
    WireFormatError,
    WireMap,
    WireSet,
    WireUrl,
    decode_wire,
    encode_wire,
    stable_stringify,
    stable_wire_key,
)

__all__ = [
    "ABSENT_IDENTITY",
    "CLIENT_CLOSED",
    "MAX_BATCH_ENTRIES",
    "OFFLINE_IDENTITY_CHANGED",
    "OFFLINE_PRECONDITION_FAILED",
    "OFFLINE_QUEUE_OVERFLOW",
    "OFFLINE_WRITE_UNENCODABLE",
    "TAG",
    "TRANSIENT_ERROR_CODES",
    "UNDEFINED",
    "Discarded",
    "FlushReport",
    "LunoraClient",
    "LunoraError",
    "MutationOutcome",
    "MutationSettled",
    "OfflineError",
    "OfflineQueue",
    "OptimisticHandle",
    "OptimisticLayer",
    "OptimisticLocalStore",
    "PersistenceAdapter",
    "QueuedMutation",
    "SubmitOptions",
    "SubscriptionError",
    "WireBigInt",
    "WireBytes",
    "WireDate",
    "WireError",
    "WireFormatError",
    "WireMap",
    "WireSet",
    "WireUrl",
    "apply_optimistic_layer",
    "build_connect_frame",
    "build_rpc_body",
    "build_shape_subscribe_frame",
    "build_subscribe_frame",
    "build_unsubscribe_frame",
    "confirm_all",
    "decode_wire",
    "drop_confirmed_layers",
    "encode_wire",
    "fold_optimistic",
    "identity_allows_replay",
    "is_stale_version",
    "notify_subscription",
    "parse_commit_cursor",
    "parse_rpc_response",
    "random_id",
    "rollback_all",
    "stable_stringify",
    "stable_wire_key",
]

__version__ = "0.1.0"
