/**
 * Compile `packages/cli/skills/<name>/SKILL.md` into a module the Worker can
 * import — plan 335 §D4 and W4.
 *
 * Why a build step at all: the skills are the framework's maintained knowledge
 * corpus and must stay the single source of truth (D4 rejects a second,
 * hand-written prompt corpus outright). But a Worker has no filesystem, so the
 * markdown has to be inlined at build time. This script is that inlining, and
 * its output is committed so a build never depends on a sibling package's
 * layout at runtime.
 *
 * What it deliberately does NOT do is summarise or rewrite. The instruction text
 * a skill ships is the text the agent gets; the moment this script starts
 * editing it, the corpus has two versions again.
 *
 * Run: `pnpm --filter "@lunora/builder" run build:skills`
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = join(here, "..");
const skillsRoot = join(appRoot, "..", "..", "packages", "cli", "skills");

/**
 * The skills the builder loads, and the trigger that selects each one.
 *
 * Not "every skill in the directory": the corpus covers the whole CLI surface,
 * and an agent that scaffolds apps has no use for the migration-helper or the
 * performance-audit playbook. Each entry pairs a skill with the words in a
 * user's request that make it relevant, which is the per-turn selection W4 asks
 * for — cheap, inspectable, and easy to correct when an eval shows it picking
 * wrong.
 */
const SELECTED = [
    { always: true, name: "lunora-functions", triggers: [] },
    { always: false, name: "lunora-quickstart", triggers: ["new", "scaffold", "start", "create"] },
    { always: false, name: "lunora-realtime", triggers: ["live", "realtime", "subscribe", "presence", "sync"] },
    { always: false, name: "lunora-setup-auth", triggers: ["auth", "login", "sign in", "sign-in", "signup", "account", "user"] },
    { always: false, name: "lunora-setup-storage", triggers: ["upload", "file", "image", "avatar", "storage", "r2"] },
    { always: false, name: "lunora-setup-mail", triggers: ["email", "mail", "invite", "notification", "verification"] },
    { always: false, name: "lunora-setup-scheduler", triggers: ["cron", "schedule", "recurring", "reminder", "later"] },
    { always: false, name: "lunora-deploy", triggers: ["deploy", "publish", "ship", "production", "wrangler"] },
];

/** Leading YAML frontmatter block, hoisted so it is compiled once. */
const FRONTMATTER = /^---\r?\n[\s\S]*?\r?\n---\r?\n/u;

/**
 * Strip the YAML frontmatter. `skillFromMarkdown` parses it at runtime; the
 * budget figure below should count instruction text, not the metadata header.
 * @param {string} markdown The raw SKILL.md contents.
 * @returns {string} The body with any frontmatter removed.
 */
const bodyOf = (markdown) => {
    const match = FRONTMATTER.exec(markdown);

    return match === null ? markdown : markdown.slice(match[0].length);
};

const read = (name) => {
    const path = join(skillsRoot, name, "SKILL.md");

    try {
        return readFileSync(path, "utf8");
    } catch {
        const available = readdirSync(skillsRoot, { withFileTypes: true })
            .filter((entry) => entry.isDirectory())
            .map((entry) => entry.name)
            .join(", ");

        throw new Error(`build-skills: no SKILL.md for "${name}". Available: ${available}`);
    }
};

const entries = SELECTED.map((selection) => {
    const markdown = read(selection.name);

    return { ...selection, chars: bodyOf(markdown).length, markdown };
});

const total = entries.reduce((sum, entry) => sum + entry.chars, 0);

const output = `/**
 * GENERATED by \`scripts/build-skills.mjs\` — do not edit.
 *
 * Source: \`packages/cli/skills/<name>/SKILL.md\`. Re-run
 * \`pnpm --filter "@lunora/builder" run build:skills\` after the corpus changes.
 *
 * ${entries.length} skills, ${total} characters of instruction text in total.
 */
export const SKILL_SOURCES = ${JSON.stringify(
    entries.map((entry) => {
        return { always: entry.always, markdown: entry.markdown, name: entry.name, triggers: entry.triggers };
    }),
    undefined,
    4,
)};
`;

writeFileSync(join(appRoot, "lunora", "skills.generated.ts"), output);

// eslint-disable-next-line no-console -- this is a CLI script; its output is the point
console.log(`build-skills: wrote ${entries.length} skills (${total} chars) to lunora/skills.generated.ts`);
