// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {
    billing: {
        processWebhook: FunctionReference<"action", { body: string; headers: Record<string, string> }, { applied: boolean; status: number; }>;
    };
}

export const internal: InternalApiTypes = {
    billing: {
        processWebhook: { __lunoraRef: "billing:processWebhook" },
    },
};
