import type { FunctionIR, IndexIR, MigrationIR, SchemaIR, TableIR, ValidatorIR } from "./ir.js";
import { sanitizeNamespace } from "./paths.js";

export const GENERATED_HEADER = "// GENERATED by @cirrus/codegen — do not edit.\n// Run `cirrus codegen` to regenerate.\n\n";

/** Map a {@link ValidatorIR} kind to its TS type. */
const validatorToType = (validator: ValidatorIR): string => {
    switch (validator.kind) {
        case "any": {
            return "unknown";
        }
        case "array": {
            return `Array<${validator.inner ? validatorToType(validator.inner) : "unknown"}>`;
        }
        case "bigint": {
            return "bigint";
        }
        case "boolean": {
            return "boolean";
        }
        case "bytes": {
            return "ArrayBuffer";
        }
        case "date":
        case "timestamp": {
            // Epoch-millisecond numbers; the distinction is semantic only.
            return "number";
        }
        case "id": {
            return `Id<"${validator.tableName ?? "_unknown_"}">`;
        }
        case "literal": {
            // `literalValue` is the verbatim source text (e.g. `"admin"`, `42`,
            // `true`, `null`) — already a valid TS literal type.
            return validator.literalValue ?? "unknown";
        }
        case "null": {
            return "null";
        }
        case "number": {
            return "number";
        }
        case "object": {
            if (!validator.shape) {
                return "Record<string, unknown>";
            }

            const fields = Object.entries(validator.shape)
                .map(([key, child]) => `${key}: ${validatorToType(child)}`)
                .join("; ");

            return `{ ${fields} }`;
        }
        case "optional": {
            return `${validator.inner ? validatorToType(validator.inner) : "unknown"} | undefined`;
        }
        case "record": {
            const key = validator.keyType ? validatorToType(validator.keyType) : "string";
            const value = validator.valueType ? validatorToType(validator.valueType) : "unknown";

            return `Record<${key}, ${value}>`;
        }
        case "string": {
            return "string";
        }
        case "union": {
            return validator.members && validator.members.length > 0 ? validator.members.map((member) => validatorToType(member)).join(" | ") : "never";
        }
        default: {
            return "unknown";
        }
    }
};

const renderArgsType = (args: Record<string, ValidatorIR>): string => {
    const entries = Object.entries(args);

    if (entries.length === 0) {
        return "{}";
    }

    return `{ ${entries
        .map(([key, validator]) => {
            if (validator.kind === "optional") {
                // Emit `key?: Inner` rather than `key?: Inner | undefined`.
                const inner = validator.inner ? validatorToType(validator.inner) : "unknown";

                return `${key}?: ${inner}`;
            }

            return `${key}: ${validatorToType(validator)}`;
        })
        .join("; ")} }`;
};

/**
 * A field is optional on **insert** when it is `v.optional(...)` or declares a
 * `.default()`/`.$defaultFn()` (codegen records the latter as `column.hasDefault`).
 */
const isOptionalOnInsert = (validator: ValidatorIR): boolean => validator.kind === "optional" || Boolean(validator.column?.hasDefault);

/**
 * Render an `Insert_<table>` interface: the document shape as accepted by
 * `ctx.db.<table>.insert(...)`. System fields (`_id`, `_creationTime`) are
 * always optional (minted by the runtime); user fields follow
 * {@link isOptionalOnInsert}.
 */
const renderInsertInterface = (table: TableIR): string => {
    const fields = Object.entries(table.shape)
        .map(([fieldName, validator]) => {
            const inner = validator.kind === "optional" && validator.inner ? validator.inner : validator;
            const type = validatorToType(inner);

            return isOptionalOnInsert(validator) ? `    ${fieldName}?: ${type};` : `    ${fieldName}: ${type};`;
        })
        .join("\n");
    const body = fields ? `\n${fields}\n` : "";

    return `export interface Insert_${table.name} {\n    _id?: Id<"${table.name}">;\n    _creationTime?: number;${body}}`;
};

/** Emit `_generated/dataModel.ts` — `Doc<"name">` + `Id<"name">` for every table. */
export const emitDataModel = (schema: SchemaIR): string => {
    const tableNames = schema.tables.map((table) => `"${table.name}"`).join(" | ") || "never";

    const docs = schema.tables
        .map((table) => {
            const fields = Object.entries(table.shape)
                .map(([fieldName, validator]) => {
                    if (validator.kind === "optional") {
                        const inner = validator.inner ? validatorToType(validator.inner) : "unknown";

                        return `    ${fieldName}?: ${inner};`;
                    }

                    return `    ${fieldName}: ${validatorToType(validator)};`;
                })
                .join("\n");
            const body = fields ? `\n${fields}\n` : "";

            return `export interface Doc_${table.name} {\n    _id: Id<"${table.name}">;\n    _creationTime: number;${body}}`;
        })
        .join("\n\n");

    const docMap = schema.tables.map((table) => `    ${table.name}: Doc_${table.name};`).join("\n");

    // Per-table index name union — surfaced as `IndexName<"messages">` so
    // `TableReader.withIndex(name)` can be typed without a hand-rolled
    // overload per table.
    const indexNamesByTable = schema.tables
        .map((table) => {
            const names = table.indexes.map((index) => `"${index.name}"`).join(" | ");

            return `    ${table.name}: ${names || "never"};`;
        })
        .join("\n");

    const searchIndexNamesByTable = schema.tables
        .map((table) => {
            const names = table.searchIndexes.map((index) => `"${index.name}"`).join(" | ");

            return `    ${table.name}: ${names || "never"};`;
        })
        .join("\n");

    const vectorIndexNames = schema.vectorIndexes.map((index) => `"${index.name}"`).join(" | ") || "never";

    const insertInterfaces = schema.tables.map((table) => renderInsertInterface(table)).join("\n\n");
    const insertMap = schema.tables.map((table) => `    ${table.name}: Insert_${table.name};`).join("\n");

    // Per-table relation descriptor map. Every table gets an entry (`{}` when it
    // declares none) so `Relations[T]` is always defined for the `with` machinery.
    const relationsMap = schema.tables
        .map((table) => {
            const entries = table.relations
                .map((relation) => `        ${relation.name}: ${relation.kind === "one" ? "OneRelation" : "ManyRelation"}<"${relation.table}">;`)
                .join("\n");

            return entries ? `    ${table.name}: {\n${entries}\n    };` : `    ${table.name}: {};`;
        })
        .join("\n");

    return `${GENERATED_HEADER}export type TableName = ${tableNames};

export type Id<TName extends string> = string & { readonly __table: TName };

${docs}

export interface DataModel {
${docMap}
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. \`never\` for tables without secondary indexes.
 * Used by \`TableReader.withIndex()\` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
${indexNamesByTable}
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. \`never\` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
${searchIndexNamesByTable}
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Union of declared vector index names. \`never\` when none are declared. */
export type VectorIndexName = ${vectorIndexNames};

${insertInterfaces}

/** Per-table insert shape, accepted by \`ctx.db.<table>.insert(...)\`. */
export interface InsertModel {
${insertMap}
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/** Field-level operators for the typed \`where\` DSL (see \`@cirrus/do\`'s compiler). */
export interface WhereOperators<T> {
    contains?: string;
    eq?: T;
    gt?: T;
    gte?: T;
    in?: T[];
    isNull?: boolean;
    lt?: T;
    lte?: T;
    ne?: T;
    notIn?: T[];
}

/** A typed \`where\` tree over a document's columns. */
export type Where<TDoc> = {
    [K in keyof TDoc]?: TDoc[K] | WhereOperators<TDoc[K]>;
} & {
    AND?: Array<Where<TDoc>>;
    NOT?: Where<TDoc>;
    OR?: Array<Where<TDoc>>;
};

/** One \`{ field: "asc" | "desc" }\` ordering entry; \`orderBy\` is an ordered list. */
export type OrderBy<TDoc> = Partial<Record<keyof TDoc, "asc" | "desc">>;

export interface QueryArgs<TDoc> {
    cursor?: null | string;
    limit?: number;
    orderBy?: Array<OrderBy<TDoc>>;
    where?: Where<TDoc>;
}

export interface QueryPage<TDoc> {
    continueCursor: null | string;
    isDone: boolean;
    page: TDoc[];
}

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the \`with\` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. \`{}\` for tables with none. */
export interface Relations {
${relationsMap}
}

/**
 * The \`with\` argument for table \`T\`: each relation can be \`true\` (load with no
 * refinements) or an object. \`many\` relations accept \`where\`/\`orderBy\`/\`limit\`
 * plus a nested \`with\`; \`one\` relations accept only a nested \`with\`. The
 * reserved \`_count\` key requests per-relation aggregate counts.
 */
export type WithArg<T extends keyof DataModel> = {
    [K in keyof Relations[T]]?: Relations[T][K] extends ManyRelation<infer Target>
        ? boolean | (QueryArgs<Doc<Target>> & { with?: WithArg<Target> })
        : Relations[T][K] extends OneRelation<infer Target>
            ? boolean | { with?: WithArg<Target> }
            : never;
} & {
    _count?: { [K in keyof Relations[T]]?: true };
};

/** The nested \`with\` sub-argument inside a relation's with-value, or \`{}\`. */
type NestedWithArg<WK> = WK extends { with: infer NW } ? NW : {};

/** Resolve a single relation descriptor + its with-value to the loaded type. */
type LoadRelation<R, WK> = R extends OneRelation<infer Target>
    ? LoadWith<Target, NestedWithArg<WK>> | null
    : R extends ManyRelation<infer Target>
        ? Array<LoadWith<Target, NestedWithArg<WK>>>
        : never;

/** The relation keys of \`W\` that were actually requested (not \`false\`/\`undefined\`). */
type LoadedRelations<T extends keyof DataModel, W> = {
    [K in keyof W as K extends keyof Relations[T] ? (W[K] extends false | undefined ? never : K) : never]: K extends keyof Relations[T]
        ? LoadRelation<Relations[T][K], W[K]>
        : never;
};

/** The \`_count\` projection of \`W\`, if any. */
type LoadedCount<W> = W extends { _count: infer C } ? { _count: { [K in keyof C]: number } } : {};

/** \`Doc<T>\` narrowed to exactly the relations requested in the with-arg \`W\`. */
export type LoadWith<T extends keyof DataModel, W> = Doc<T> & LoadedRelations<T, W> & LoadedCount<W>;

/** Reducer applied by an aggregate (\`avg\`/\`count\`/\`max\`/\`min\`/\`sum\`). */
export type AggregateOp = "avg" | "count" | "max" | "min" | "sum";

/**
 * Query-options shape shared by every aggregate reader. The RLS-aware ctx
 * (§3.2) populates \`baseWhere\` so it composes here without a hard import.
 * \`restrictsCounts: true\` flips \`count()\` into a thrown \`COUNT_RLS_UNSUPPORTED\`
 * \`CirrusError\` rather than silently undercount.
 */
export interface RestrictableQueryOptions<TDoc> {
    baseWhere?: Where<TDoc>;
    restrictsCounts?: boolean;
    where?: Where<TDoc>;
}

/** Args for \`ctx.db.<table>.aggregate({ op, field?, where? })\`. */
export interface TableAggregateOptions<TDoc> extends RestrictableQueryOptions<TDoc> {
    field?: keyof TDoc & string;
    op: AggregateOp;
}

/** Args for \`ctx.db.<table>.groupBy({ by, agg?, where? })\`. */
export interface TableGroupByOptions<TDoc> extends RestrictableQueryOptions<TDoc> {
    agg?: { field?: keyof TDoc & string; op: AggregateOp };
    by: ReadonlyArray<keyof TDoc & string>;
}

/** One entry returned by \`groupBy\` — the group's by-tuple plus the reducer value. */
export interface GroupByEntry<TDoc> {
    key: Partial<TDoc>;
    value: null | number;
}

/** Args for \`ctx.db.<table>.rank(name, args)\`. \`row\` is either an id or a row doc. */
export interface TableRankOptions<TDoc> extends RestrictableQueryOptions<TDoc> {
    row: Id<keyof DataModel & string> | TDoc | string;
}

/** Result of \`rank\` — 1-based position within the partition + partition total. */
export interface RankResult {
    position: number;
    total: number;
}

/** Args for \`ctx.db.<table>.rankPage(name, args)\`. */
export interface TableRankPageOptions<TDoc> extends RestrictableQueryOptions<TDoc> {
    cursor?: null | string;
    take?: number;
}

/** One page returned by \`rankPage\`. */
export interface RankPage<TDoc> {
    continueCursor: null | string;
    isDone: boolean;
    page: TDoc[];
}

/** Read-only typed table accessor exposed on \`QueryCtx.db.<table>\`. */
export interface TableReaderFacade<T extends keyof DataModel> {
    /**
     * Reduce rows in this table to a scalar (\`avg\`/\`max\`/\`min\`/\`sum\` — \`count\`
     * lives on its own method). Routes through a declared \`aggregateIndex\` when
     * the planner can prove the request is answerable; otherwise scans.
     */
    aggregate: (options: TableAggregateOptions<Doc<T>>) => Promise<null | number>;
    /**
     * Count rows. The planner routes \`where\` keys that match a declared
     * \`aggregateIndex.by\` set to the indexed counter (no scan); otherwise
     * falls back to a SCAN. Accepts either a bare \`where\` tree or the broader
     * \`RestrictableQueryOptions\` shape; the latter is the seam the RLS layer
     * uses to inject \`baseWhere\` and \`restrictsCounts\`.
     */
    count: (where?: RestrictableQueryOptions<Doc<T>> | Where<Doc<T>>) => Promise<number>;
    findFirst: <W extends WithArg<T> = {}>(args?: QueryArgs<Doc<T>> & { with?: W }) => Promise<LoadWith<T, W> | null>;
    findFirstOrThrow: <W extends WithArg<T> = {}>(args?: QueryArgs<Doc<T>> & { with?: W }) => Promise<LoadWith<T, W>>;
    findMany: <W extends WithArg<T> = {}>(args?: QueryArgs<Doc<T>> & { with?: W }) => Promise<QueryPage<LoadWith<T, W>>>;
    get: (id: Id<T>) => Promise<Doc<T> | null>;
    /**
     * Group rows by the named keys and apply \`agg\` per group (defaults to
     * \`count\`). Answered from the counter table when an aggregate index's
     * \`by\` matches \`options.by\` exactly; otherwise scans.
     */
    groupBy: (options: TableGroupByOptions<Doc<T>>) => Promise<ReadonlyArray<GroupByEntry<Doc<T>>>>;
    /**
     * Return the 1-based position of \`options.row\` within its partition
     * under the declared rankIndex \`indexName\`, plus the partition's total
     * row count. \`null\` when the row isn't in the index. Honors the same
     * \`baseWhere\` / \`restrictsCounts\` RLS seam as \`count()\`.
     */
    rank: (indexName: string, options: TableRankOptions<Doc<T>>) => Promise<null | RankResult>;
    /**
     * Walk the rank companion in declared sort order — sorted pagination
     * accelerator. \`options.where\` may pin the partition; \`cursor\`/\`take\`
     * follow the Convex-style keyset shape.
     */
    rankPage: (indexName: string, options?: TableRankPageOptions<Doc<T>>) => Promise<RankPage<Doc<T>>>;
}

/** Read-write typed table accessor exposed on \`MutationCtx.db.<table>\` / \`ActionCtx.db.<table>\`. */
export interface TableWriterFacade<T extends keyof DataModel> extends TableReaderFacade<T> {
    delete: (id: Id<T>) => Promise<void>;
    insert: (values: Insert<T>) => Promise<Id<T>>;
    patch: (id: Id<T>, values: Partial<Insert<T>>) => Promise<void>;
    replace: (id: Id<T>, values: Insert<T>) => Promise<void>;
}

/** Per-table read facade — \`ctx.db.<table>\` on a \`QueryCtx\`. */
export type DatabaseReaderFacade = {
    readonly [T in keyof DataModel]: TableReaderFacade<T>;
};

/** Per-table read-write facade — \`ctx.db.<table>\` on a \`MutationCtx\` / \`ActionCtx\`. */
export type DatabaseWriterFacade = {
    readonly [T in keyof DataModel]: TableWriterFacade<T>;
};

/** Insert builder returned by \`ctx.orm.insert(table)\`. */
export interface OrmInsertBuilder<T extends keyof DataModel> {
    values: (values: Insert<T>) => Promise<Id<T>>;
}

/** Replace builder returned by \`ctx.orm.replace(table, id)\` — swaps the whole document. */
export interface OrmReplaceBuilder<T extends keyof DataModel> {
    with: (values: Insert<T>) => Promise<void>;
}

/** Update builder returned by \`ctx.orm.update(table, id)\` — patches the named fields. */
export interface OrmUpdateBuilder<T extends keyof DataModel> {
    set: (values: Partial<Insert<T>>) => Promise<void>;
}

/** Read-only ORM surface — \`ctx.orm\` on a \`QueryCtx\`. Mirrors \`ctx.db\` reads under a kitcn-style \`query\` namespace. */
export interface OrmReader {
    query: DatabaseReaderFacade;
}

/** Read-write ORM surface — \`ctx.orm\` on a \`MutationCtx\` / \`ActionCtx\`. Writes are addressed by id, like \`ctx.db\`. */
export interface OrmWriter extends OrmReader {
    delete: <T extends keyof DataModel>(table: T, id: Id<T>) => Promise<void>;
    insert: <T extends keyof DataModel>(table: T) => OrmInsertBuilder<T>;
    replace: <T extends keyof DataModel>(table: T, id: Id<T>) => OrmReplaceBuilder<T>;
    update: <T extends keyof DataModel>(table: T, id: Id<T>) => OrmUpdateBuilder<T>;
}
`;
};

/**
 * Rewrite `import("…")` qualifiers inside a return-type string so they resolve
 * from `_generated/api.ts` rather than from the function's source file.
 *
 * ts-morph prints types relative to where they were *read* (the handler
 * arrow), so a function at `cirrus/foo.ts` importing
 * `./_generated/dataModel.js` produces `import("./_generated/dataModel.js").X`
 * in the rendered text. Inlined verbatim into `cirrus/_generated/api.ts`,
 * that path is one level too deep — tsc raises TS2307.
 *
 * Fix: strip the leading `./_generated/` segment so types resolve from inside
 * `_generated/`. Cirrus's only relative `import("…")` qualifier comes from
 * `_generated/dataModel.ts`, so this targeted rewrite is enough; absolute
 * imports (e.g. `import("@cirrus/server")`) are left untouched.
 */
const relocateGeneratedImports = (returnType: string): string =>
    returnType.replaceAll(/import\("(?<spec>(?:\.\/)?_generated\/[^"]+)"\)/gu, (_match, spec: string) => {
        const stripped = spec.replace(/^\.\/_generated\//u, "./").replace(/^_generated\//u, "./");

        return `import("${stripped}")`;
    });

/**
 * Render the grouped-by-namespace body of an api interface for a subset of
 * functions. Returns `""` when the subset is empty so the caller can emit an
 * empty `{}` interface.
 */
const renderApiBody = (functions: ReadonlyArray<FunctionIR>): string => {
    const namespaces = new Map<string, FunctionIR[]>();

    for (const fn of functions) {
        const list = namespaces.get(fn.filePath) ?? [];

        list.push(fn);
        namespaces.set(fn.filePath, list);
    }

    const renderNamespace = ([file, list]: [string, FunctionIR[]]): string => {
        const members = list
            .map((fn) => {
                // We emit `FunctionReference<Kind, ArgsObj, Return>` so the
                // generated `api.*` references plug directly into
                // `useQuery`/`useMutation` from `@cirrus/react` (and
                // `client.query` / `client.mutation` from `@cirrus/client`).
                // The phantom `Kind`/`Args`/`Return` parameters carry the
                // info downstream hooks need to infer call signatures.
                const argsType = renderArgsType(fn.args);
                const returnType = relocateGeneratedImports(fn.returnType);

                return `        ${fn.exportName}: FunctionReference<"${fn.kind}", ${argsType}, ${returnType}>;`;
            })
            .join("\n");

        return `    ${sanitizeNamespace(file)}: {\n${members}\n    };`;
    };

    return [...namespaces.entries()]
        .sort(([a], [b]) => a.localeCompare(b))
        .map((entry) => renderNamespace(entry))
        .join("\n");
};

/**
 * Emit `_generated/api.ts` — the typed `api.*` registry (public functions) plus
 * the `internal.*` registry. Both are the same `anyApi` proxy at runtime (the
 * `__cirrusRef` is identical); visibility is enforced server-side at dispatch,
 * not in the reference. Splitting the *types* keeps internal functions off the
 * client-facing `api` surface.
 */
export const emitApi = (functions: ReadonlyArray<FunctionIR>): string => {
    const publicFunctions = functions.filter((fn) => fn.visibility !== "internal");
    const internalFunctions = functions.filter((fn) => fn.visibility === "internal");

    const publicBody = renderApiBody(publicFunctions);
    const internalBody = renderApiBody(internalFunctions);

    // Import only the dataModel helpers the rendered arg/return types actually
    // reference: `Doc` appears when a function returns documents, `Id` when it
    // takes or returns an id. Importing an unused one trips noUnusedLocals.
    const combinedBody = `${publicBody}\n${internalBody}`;
    const dataModelImports = (["Doc", "Id"] as const).filter((name) => new RegExp(String.raw`\b${name}<`, "u").test(combinedBody));
    const dataModelImportLine = dataModelImports.length > 0 ? `\nimport type { ${dataModelImports.join(", ")} } from "./dataModel.js";\n` : "";

    const apiBlock = publicBody ? `\n${publicBody}\n` : "";
    const internalBlock = internalBody ? `\n${internalBody}\n` : "";

    return `${GENERATED_HEADER}import { anyApi } from "@cirrus/server/types";
import type { FunctionReference } from "@cirrus/client";
${dataModelImportLine}
export interface ApiTypes {${apiBlock}}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via \`ctx.run*\`, never from a client. */
export interface InternalApiTypes {${internalBlock}}

export const internal = anyApi as unknown as InternalApiTypes;
`;
};

/**
 * Convert a raw file path into a JS-identifier-safe alias used as the
 * imported namespace inside `_generated/server.ts`. Keeps the path
 * recognisable in the generated source while satisfying the lexer.
 */
const moduleAlias = (filePath: string, index: number): string => `cirrus_${sanitizeNamespace(filePath)}_${index}`;

/**
 * Render the typed `Caller` interface and the `createCaller` object body for a
 * set of functions, both grouped by namespace. The caller surfaces **every**
 * registered function — public *and* internal — because server-to-server calls
 * legitimately reach internal functions (mirroring `ctx.run*`). Each leaf is
 * `(args) => Promise<Return>`; `args` is optional only when the function takes
 * none. The runtime leaves dispatch through `callRegistered`, which infers the
 * return type from the interface's contextual type.
 */
const renderCaller = (functions: ReadonlyArray<FunctionIR>): { implementation: string; types: string } => {
    const namespaces = new Map<string, FunctionIR[]>();

    for (const fn of functions) {
        const list = namespaces.get(fn.filePath) ?? [];

        list.push(fn);
        namespaces.set(fn.filePath, list);
    }

    const ordered = [...namespaces.entries()].sort(([a], [b]) => a.localeCompare(b));

    const types = ordered
        .map(([file, list]) => {
            const members = list
                .map((fn) => {
                    const argsType = renderArgsType(fn.args);
                    const optional = argsType === "{}" ? "?" : "";
                    const returnType = relocateGeneratedImports(fn.returnType);

                    return `        ${fn.exportName}: (args${optional}: ${argsType}) => Promise<${returnType}>;`;
                })
                .join("\n");

            return `    ${sanitizeNamespace(file)}: {\n${members}\n    };`;
        })
        .join("\n");

    const implementation = ordered
        .map(([file, list]) => {
            const namespace = sanitizeNamespace(file);
            const leaves = list.map((fn) => `        ${fn.exportName}: (args) => callRegistered(context, "${namespace}:${fn.exportName}", args),`).join("\n");

            return `    ${namespace}: {\n${leaves}\n    },`;
        })
        .join("\n");

    return { implementation, types };
};

/**
 * Emit `_generated/server.ts` — re-exports of the user-facing factories
 * **plus** a static dispatch table that maps `${namespace}:${fnName}` keys
 * to the registered handler objects (and a `CIRRUS_MIGRATIONS` registry keyed
 * by migration id). A `ShardDO` subclass can plug these straight into
 * `handleRpc(functionPath, args)` / the data-migration runner.
 */
export const emitServer = (functions: ReadonlyArray<FunctionIR>, migrations: ReadonlyArray<MigrationIR> = []): string => {
    // One import alias per distinct source file. Functions are registered
    // first (preserving the prior alias numbering), then migration-only files
    // pick up the next indices — deterministic across runs.
    const aliasByPath = new Map<string, string>();

    const registerPath = (filePath: string): void => {
        if (!aliasByPath.has(filePath)) {
            aliasByPath.set(filePath, moduleAlias(filePath, aliasByPath.size));
        }
    };

    for (const fn of functions) {
        registerPath(fn.filePath);
    }

    for (const migration of migrations) {
        registerPath(migration.filePath);
    }

    const importLines = [...aliasByPath.entries()].map(([filePath, alias]) => `import * as ${alias} from "../${filePath}.js";`).join("\n");

    // Functions arrive pre-sorted by `${filePath}:${exportName}`, so same-file
    // entries stay contiguous and the alias lookup is always populated.
    const dispatchEntries = functions
        .map(
            (fn) =>
                `    "${sanitizeNamespace(fn.filePath)}:${fn.exportName}": ${aliasByPath.get(fn.filePath) ?? ""}.${fn.exportName} as unknown as RegisteredCirrusFunction,`,
        )
        .join("\n");

    const migrationEntries = migrations
        .map(
            (migration) =>
                `    ${JSON.stringify(migration.id)}: ${aliasByPath.get(migration.filePath) ?? ""}.${migration.exportName} as unknown as RegisteredDataMigration,`,
        )
        .join("\n");

    const dispatchBody = dispatchEntries.length > 0 ? `\n${dispatchEntries}\n` : "";
    const migrationBody = migrationEntries.length > 0 ? `\n${migrationEntries}\n` : "";
    const importBlock = importLines.length > 0 ? `${importLines}\n\n` : "";

    const caller = renderCaller(functions);
    const callerTypes = caller.types ? `\n${caller.types}\n` : "";
    const callerImpl = caller.implementation ? `\n${caller.implementation}\n` : "";

    // Pull the `Doc`/`Id` aliases the caller's arg/return types actually
    // reference into the existing dataModel import (importing an unused one
    // trips noUnusedLocals). The `export type` re-export below is separate — it
    // re-exports without creating a local binding, so it can't satisfy these.
    const callerDataModelImports = (["Doc", "Id"] as const).filter((name) => new RegExp(String.raw`\b${name}<`, "u").test(caller.types));
    const dataModelImportTail = callerDataModelImports.length > 0 ? `, ${callerDataModelImports.join(", ")}` : "";

    // `callRegistered` (and thus `context`) is only referenced when at least one
    // function exists; otherwise it would be an unused local / parameter.
    const callerParameter = functions.length > 0 ? "context" : "_context";
    const callRegisteredHelper
        = functions.length > 0
            ? `const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw Object.assign(new Error(\`function not registered: \${functionPath}\`), {
            name: "CirrusError",
            code: "FUNCTION_NOT_FOUND",
            status: 404,
        });
    }

    return (await registered.handler(context, args ?? {})) as R;
};

`
            : "";

    return `${GENERATED_HEADER}${importBlock}import {
    action as actionBase,
    internalAction as internalActionBase,
    internalMutation as internalMutationBase,
    internalQuery as internalQueryBase,
    mutation as mutationBase,
    query as queryBase,
} from "@cirrus/server";
import type {
    ActionCtx as ActionCtxBase,
    ArgsValidator,
    DatabaseReader,
    DatabaseWriter,
    InferArgs,
    MutationCtx as MutationCtxBase,
    QueryCtx as QueryCtxBase,
    RegisteredAction,
    RegisteredMutation,
    RegisteredQuery,
} from "@cirrus/server";

import type { DatabaseReaderFacade, DatabaseWriterFacade${dataModelImportTail}, OrmReader, OrmWriter } from "./dataModel.js";

export type { DataModel, Doc, Id } from "./dataModel.js";

/**
 * Project-typed contexts. The base contexts from \`@cirrus/server\` are
 * untyped against the schema; here \`db\` is widened to the generated per-table
 * facade (\`ctx.db.<table>.findMany(...)\`) while keeping the legacy structural
 * \`db.get\`/\`db.query\` surface for back-compat.
 */
export interface QueryCtx extends Omit<QueryCtxBase, "db"> {
    readonly db: DatabaseReader & DatabaseReaderFacade;
    readonly orm: OrmReader;
}

export interface MutationCtx extends Omit<MutationCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

export interface ActionCtx extends Omit<ActionCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

/** \`query()\` bound to this project's typed {@link QueryCtx}. */
export const query = queryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** \`mutation()\` bound to this project's typed {@link MutationCtx}. */
export const mutation = mutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** \`action()\` bound to this project's typed {@link ActionCtx}. */
export const action = actionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/** \`internalQuery()\` bound to this project's typed {@link QueryCtx} — never exposed on \`api\`. */
export const internalQuery = internalQueryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** \`internalMutation()\` bound to this project's typed {@link MutationCtx} — never exposed on \`api\`. */
export const internalMutation = internalMutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** \`internalAction()\` bound to this project's typed {@link ActionCtx} — never exposed on \`api\`. */
export const internalAction = internalActionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/**
 * Single registered function, narrowed to the shape \`handleRpc\` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to \`unknown\` so a single map can host every
 * registered function.
 */
export interface RegisteredCirrusFunction {
    kind: "action" | "mutation" | "query";
    args: Record<string, unknown>;
    handler: (context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown;
    /** \`"internal"\` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the \`__cirrusRef\` the client
 * emits (\`api[namespace][fn].__cirrusRef === "namespace:fn"\`).
 */
export const CIRRUS_FUNCTIONS: Record<string, RegisteredCirrusFunction> = {${dispatchBody}};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * CirrusError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchCirrusFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw Object.assign(new Error(\`function not registered: \${functionPath}\`), {
            name: "CirrusError",
            code: "FUNCTION_NOT_FOUND",
            status: 404,
        });
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's \`ctx\` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied \`context\`, exactly like \`ctx.runQuery\`/\`runMutation\`/
 * \`runAction\` but without re-stating the function path.
 */
export interface Caller {${callerTypes}}

${callRegisteredHelper}/** Build a {@link Caller} bound to \`context\` (typically a handler's \`ctx\`). */
export const createCaller = (${callerParameter}: CallerCtx): Caller => ({${callerImpl}});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. \`up\`/\`down\` are erased to a structural transform; the authoring
 * validation lives in \`defineMigration\`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by \`defineMigration\`'s \`id\`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const CIRRUS_MIGRATIONS: Record<string, RegisteredDataMigration> = {${migrationBody}};
`;
};

/**
 * Emit `_generated/shard.ts` — a `createShardDO(config)` factory returning a
 * concrete `ShardDO` subclass. Dispatch runs through `CIRRUS_FUNCTIONS` from
 * `./server.js`; the live schema is imported from `../schema.js`.
 *
 * The file stays dependency-light: it always imports `@cirrus/do`, and only
 * imports `@cirrus/vectors` when the schema declares at least one vector index.
 * `scheduler`/`storage` arrive via optional config thunks (so the generated
 * file never hard-imports `@cirrus/scheduler` / `@cirrus/storage`); when a
 * thunk is omitted an error stub is wired in its place.
 */
export const emitShard = (schema: SchemaIR): string => {
    const hasVectors = schema.vectorIndexes.length > 0;
    const hasGlobalTables = schema.tables.some((table) => table.shardMode === "global");
    const hasTables = schema.tables.length > 0;

    const doTypeImports = [
        ...hasTables ? ["AggregateOptions", "GroupByOptions"] : [],
        "DatabaseWriterLike",
        "DataMigrationLike",
        "MigrationRunResult",
        "QueryArgs",
        ...hasTables ? ["RankOptions", "RankPageOptions", "RestrictableQueryOptions"] : [],
        "RunShardMigrationArgs",
        "SchedulerLike",
        "SchemaLike",
        "ShardDOState",
        "SqlExec",
        "WhereInput",
        ...hasVectors ? ["WriteHook"] : [],
    ];

    const importLines = [
        `import type { ${doTypeImports.join(", ")} } from "@cirrus/do";`,
        `import { createShardCtxDb, runDataMigration, runShardMigrations, ShardDO as ShardDOBase } from "@cirrus/do";`,
    ];

    if (hasVectors) {
        importLines.push(
            `import type { SchemaLike as VectorSchemaLike, VectorizeIndexLike, VectorSearchLike } from "@cirrus/vectors";`,
            `import { createCtxVectors, createVectors, createVectorSyncHook } from "@cirrus/vectors";`,
        );
    }

    importLines.push(``, `import schema from "../schema.js";`, `import { CIRRUS_FUNCTIONS, CIRRUS_MIGRATIONS } from "./server.js";`);

    const vectorsConfigField = hasVectors ? `\n    vectors?: (env: Record<string, unknown>) => Record<string, VectorizeIndexLike>;` : "";

    // `.global()` tables live in D1, not the DO's SQLite. The runtime D1 binding
    // arrives via an optional `d1` config thunk; when omitted (or for projects
    // with no global tables), reads/writes to a global table hit `globalDbStub`
    // and throw a descriptive error.
    const d1ConfigField = hasGlobalTables ? `\n    d1?: (env: Record<string, unknown>) => DatabaseWriterLike;` : "";

    const globalDbStub = hasGlobalTables
        ? `
const globalDbStub: DatabaseWriterLike = {
    aggregate: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    count: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    delete: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    findFirst: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    findFirstOrThrow: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    findMany: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    get: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    groupBy: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    insert: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    patch: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    query: () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
    replace: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass \`d1\` to createShardDO().");
    },
};
`
        : "";

    const vectorsStub = hasVectors
        ? `
const vectorsStub: VectorSearchLike = {
    deleteByIds: async () => {
        throw new Error("ctx.vectors: no vectors configured. Pass \`vectors\` to createShardDO().");
    },
    getByIds: async () => {
        throw new Error("ctx.vectors: no vectors configured. Pass \`vectors\` to createShardDO().");
    },
    query: async () => {
        throw new Error("ctx.vectors: no vectors configured. Pass \`vectors\` to createShardDO().");
    },
    upsert: async () => {
        throw new Error("ctx.vectors: no vectors configured. Pass \`vectors\` to createShardDO().");
    },
    upsertNow: async () => {
        throw new Error("ctx.vectors: no vectors configured. Pass \`vectors\` to createShardDO().");
    },
};
`
        : "";

    const vectorsBuild = hasVectors
        ? `
            let vectors: VectorSearchLike;
            let onWrite: WriteHook | undefined;

            if (config.vectors) {
                const cirrus = createVectors({ indexes: config.vectors(env) });

                vectors = createCtxVectors(cirrus);
                onWrite = createVectorSyncHook({ schema: schema as unknown as VectorSchemaLike, vectors });
            } else {
                vectors = vectorsStub;
                onWrite = undefined;
            }
`
        : "";

    const dbOptions = hasVectors
        ? `{
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                onRead: options.onRead,
                onWrite,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            }`
        : `{
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                onRead: options.onRead,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            }`;

    const vectorsCtxField = hasVectors ? `\n                vectors,` : "";

    // `ctx.orm` mirrors the per-table facade under a kitcn-style namespace; it
    // only exists when the project declares tables (otherwise `facade` is unbuilt).
    const ormCtxField = hasTables ? `\n                orm: bindOrm(facade),` : "";

    // The per-table facade (`ctx.db.<table>.findMany(...)`) is a thin binding
    // over the structural `DatabaseWriterLike`: it pins `tableName` so callers
    // don't repeat it. `delete`/`get`/`patch`/`replace` address rows by id, so
    // they pass straight through.
    const bindTableHelper = hasTables
        ? `
const bindTable = (writer: DatabaseWriterLike, tableName: string) => ({
    aggregate: (options: AggregateOptions) => writer.aggregate(tableName, options),
    count: (where?: RestrictableQueryOptions | WhereInput) => writer.count(tableName, where),
    delete: (id: string) => writer.delete(id),
    findFirst: (args?: QueryArgs) => writer.findFirst(tableName, args),
    findFirstOrThrow: (args?: QueryArgs) => writer.findFirstOrThrow(tableName, args),
    findMany: (args?: QueryArgs) => writer.findMany(tableName, args),
    get: (id: string) => writer.get(id),
    groupBy: (options: GroupByOptions) => writer.groupBy(tableName, options),
    insert: (values: Record<string, unknown>) => writer.insert(tableName, values),
    patch: (id: string, values: Record<string, unknown>) => writer.patch(id, values),
    rank: (indexName: string, options: RankOptions) => writer.rank(tableName, indexName, options),
    rankPage: (indexName: string, options?: RankPageOptions) => writer.rankPage(tableName, indexName, options),
    replace: (id: string, values: Record<string, unknown>) => writer.replace(id, values),
});

const bindOrm = (facade: Record<string, ReturnType<typeof bindTable>>) => {
    const resolve = (table: string): ReturnType<typeof bindTable> => {
        const bound = facade[table];

        if (!bound) {
            throw new Error(\`unknown table: \${table}\`);
        }

        return bound;
    };

    return {
        delete: (table: string, id: string) => resolve(table).delete(id),
        insert: (table: string) => ({ values: (values: Record<string, unknown>) => resolve(table).insert(values) }),
        query: facade,
        replace: (table: string, id: string) => ({ with: (values: Record<string, unknown>) => resolve(table).replace(id, values) }),
        update: (table: string, id: string) => ({ set: (values: Record<string, unknown>) => resolve(table).patch(id, values) }),
    };
};
`
        : "";

    // Build `globalDb` only when a `.global()` table exists; otherwise the
    // binding (and the stub it falls back to) would be unused.
    const globalDbLine = hasGlobalTables ? `\n            const globalDb: DatabaseWriterLike = config.d1?.(env) ?? globalDbStub;` : "";

    const facadeBlock = hasTables
        ? `\n            const facade = db as unknown as Record<string, ReturnType<typeof bindTable>>;
${schema.tables
    .map(
        (table) =>
            `            facade[${JSON.stringify(table.name)}] = bindTable(${table.shardMode === "global" ? "globalDb" : "db"}, ${JSON.stringify(table.name)});`,
    )
    .join("\n")}
`
        : "";

    return `${GENERATED_HEADER}${importLines.join("\n")}

type FunctionKind = "action" | "mutation" | "query";

interface FunctionReference {
    __cirrusRef: string;
}

export interface ShardDOConfig {
    scheduler?: (env: Record<string, unknown>) => unknown;
    storage?: (env: Record<string, unknown>) => unknown;${vectorsConfigField}${d1ConfigField}
}

const schedulerStub = {
    cancel: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass \`scheduler\` to createShardDO().");
    },
    runAfter: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass \`scheduler\` to createShardDO().");
    },
    runAt: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass \`scheduler\` to createShardDO().");
    },
};

const storageStub = {
    delete: async () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
    download: async () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
    getSignedUrl: async () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
    getUrl: () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
    list: async () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
    upload: async () => {
        throw new Error("ctx.storage: no storage configured. Pass \`storage\` to createShardDO().");
    },
};
${globalDbStub}${vectorsStub}${bindTableHelper}
const dispatchRun = (expected: FunctionKind, functionPath: string, args: Record<string, unknown>, ctx: unknown): Promise<unknown> | unknown => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw new Error(\`unknown function: \${functionPath}\`);
    }

    if (registered.kind !== expected) {
        throw new Error(\`ctx.run\${expected[0]!.toUpperCase()}\${expected.slice(1)}: "\${functionPath}" is registered as a \${registered.kind}, not a \${expected}\`);
    }

    return registered.handler(ctx, args);
};

/**
 * Build the project's shard Durable Object. Export the result as \`ShardDO\`
 * from the worker entry so wrangler binds it by name.
 */
export const createShardDO = (config: ShardDOConfig = {}): new (state: ShardDOState, env: unknown) => ShardDOBase =>
    class extends ShardDOBase {
        private migrated = false;

        public override async handleRpc(functionPath: string, args: Record<string, unknown>): Promise<unknown> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            // Internal functions are reachable only server-side (\`ctx.run*\`),
            // never from a client. Report them as not-found so their existence
            // never leaks across the external RPC boundary.
            if (!registered || registered.visibility === "internal") {
                throw Object.assign(new Error(\`function not registered: \${functionPath}\`), {
                    name: "CirrusError",
                    code: "FUNCTION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            return registered.handler(this.buildCtx(), args);
        }

        protected override async executeSubscription(functionPath: string, args: Record<string, unknown>): Promise<{ result: unknown; tables: Set<string> } | null> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "query" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            const tables = new Set<string>();
            const ctx = this.buildCtx({ onRead: (table) => tables.add(table) });
            const result = await registered.handler(ctx, args);

            return { result, tables };
        }

        protected override async runShardDataMigration(args: RunShardMigrationArgs): Promise<MigrationRunResult> {
            const migration = CIRRUS_MIGRATIONS[args.id];

            if (!migration) {
                throw Object.assign(new Error(\`data migration "\${args.id}" is not registered\`), {
                    name: "CirrusError",
                    code: "MIGRATION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            return runDataMigration({
                batchSize: args.batchSize,
                direction: args.direction,
                dryRun: args.dryRun,
                maxBatches: args.maxBatches,
                migration: migration as unknown as DataMigrationLike,
                sql: this.sql as SqlExec,
                writer,
            });
        }

        private ensureMigrated(): void {
            if (this.migrated) {
                return;
            }

            runShardMigrations(this.sql as SqlExec, schema as unknown as SchemaLike);
            this.migrated = true;
        }

        private buildCtx(options: { onRead?: (table: string) => void } = {}): unknown {
            const env = (this.env ?? {}) as Record<string, unknown>;
            const userId = this.getCurrentUserId();
            const identity = this.getCurrentIdentity();
${vectorsBuild}
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const db: DatabaseWriterLike = createShardCtxDb(${dbOptions});${globalDbLine}
${facadeBlock}
            const ctx: Record<string, unknown> = {
                auth: {
                    getIdentity: async () => identity ?? null,
                    userId: userId ?? null,
                },
                db,
                fetch: globalThis.fetch.bind(globalThis),${ormCtxField}
                scheduler,
                storage: config.storage?.(env) ?? storageStub,${vectorsCtxField}
            };

            ctx.runAction = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("action", reference.__cirrusRef, fnArgs, ctx);
            ctx.runMutation = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("mutation", reference.__cirrusRef, fnArgs, ctx);
            ctx.runQuery = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("query", reference.__cirrusRef, fnArgs, ctx);

            return ctx;
        }
    };
`;
};

// ─── Drizzle schema emission ─────────────────────────────────────────────────

interface DrizzleColumn {
    /** Drizzle column constructor: "text" | "integer" | "real" | "blob". */
    builder: "blob" | "integer" | "real" | "text";
    /** Optional `{ mode: … }` arg to the column constructor. */
    mode?: "bigint" | "boolean" | "buffer" | "json";
    /** Tracks whether the column should carry `.notNull()`. */
    notNull: boolean;
    /** `.$type<…>()` annotation rendered after the constructor. */
    typeAnnotation?: string;
}

const validatorToDrizzleColumn = (validator: ValidatorIR): DrizzleColumn => {
    switch (validator.kind) {
        case "array":
        case "object":
        case "record":
        case "union": {
            return {
                builder: "text",
                mode: "json",
                notNull: true,
                typeAnnotation: validatorToType(validator),
            };
        }
        case "bigint": {
            return { builder: "blob", mode: "bigint", notNull: true };
        }
        case "boolean": {
            return { builder: "integer", mode: "boolean", notNull: true };
        }
        case "bytes": {
            return { builder: "blob", mode: "buffer", notNull: true };
        }
        case "date":
        case "timestamp": {
            // Stored as epoch-millisecond integers.
            return { builder: "integer", notNull: true };
        }
        case "id": {
            return { builder: "text", notNull: true };
        }
        case "literal": {
            const value = validator.literalValue ?? "";

            // String literals start with a quote; `true`/`false`/`null` are plain
            // keywords; everything else is numeric.
            if (value.startsWith('"') || value.startsWith("'")) {
                return { builder: "text", notNull: true };
            }

            if (value === "true" || value === "false") {
                return { builder: "integer", mode: "boolean", notNull: true };
            }

            if (value === "null") {
                return { builder: "text", notNull: true };
            }

            return { builder: "real", notNull: true };
        }
        case "null": {
            return { builder: "text", notNull: true };
        }
        case "number": {
            return { builder: "real", notNull: true };
        }
        case "optional": {
            const inner = validator.inner ? validatorToDrizzleColumn(validator.inner) : { builder: "text" as const, notNull: false };

            return { ...inner, notNull: false };
        }
        case "string": {
            return { builder: "text", notNull: true };
        }
        default: {
            return { builder: "text", notNull: true };
        }
    }
};

const renderDrizzleColumn = (name: string, validator: ValidatorIR, knownTables: ReadonlySet<string>): string => {
    const column = validatorToDrizzleColumn(validator);
    const isOptional = validator.kind === "optional";
    const innerValidator = isOptional && validator.inner ? validator.inner : validator;

    const modeArg = column.mode ? `, { mode: "${column.mode}" }` : "";
    let expression = `${column.builder}("${name}"${modeArg})`;

    if (column.typeAnnotation) {
        expression += `.$type<${column.typeAnnotation}>()`;
    }

    // v.id("targetTable") becomes a FK only when target lives in the same bucket;
    // cross-bucket FKs can't be enforced (different SQLite databases).
    if (innerValidator.kind === "id" && innerValidator.tableName && knownTables.has(innerValidator.tableName)) {
        expression += `.references(() => ${innerValidator.tableName}._id)`;
    }

    if (column.notNull) {
        expression += ".notNull()";
    }

    return expression;
};

const renderIndexEntry = (index: IndexIR): string => {
    const constructor = index.unique ? "uniqueIndex" : "index";
    const fields = index.fields.map((field) => `t.${field}`).join(", ");

    return `    ${index.name}: ${constructor}("${index.name}").on(${fields}),`;
};

const renderDrizzleTable = (table: TableIR, knownTables: ReadonlySet<string>): string => {
    const columns = [
        `    _id: text("_id").primaryKey(),`,
        `    _creationTime: integer("_creationTime").notNull(),`,
        ...Object.entries(table.shape).map(([fieldName, validator]) => `    ${fieldName}: ${renderDrizzleColumn(fieldName, validator, knownTables)},`),
    ].join("\n");

    const indexBody = table.indexes.length > 0 ? `, (t) => ({\n${table.indexes.map((index) => renderIndexEntry(index)).join("\n")}\n})` : "";

    return `export const ${table.name} = sqliteTable("${table.name}", {\n${columns}\n}${indexBody});`;
};

const usedImports = (tables: ReadonlyArray<TableIR>): { columns: string[]; indexes: string[] } => {
    const columns = new Set<string>();
    const indexes = new Set<string>();

    // `sqliteTable` is always needed. `_id` is always text, `_creationTime` is always integer.
    columns.add("text");
    columns.add("integer");
    columns.add("sqliteTable");

    for (const table of tables) {
        for (const validator of Object.values(table.shape)) {
            const column = validatorToDrizzleColumn(validator);

            columns.add(column.builder);
        }

        for (const index of table.indexes) {
            indexes.add(index.unique ? "uniqueIndex" : "index");
        }
    }

    return { columns: [...columns].sort(), indexes: [...indexes].sort() };
};

const renderDrizzleFile = (tables: ReadonlyArray<TableIR>): string => {
    if (tables.length === 0) {
        return `${GENERATED_HEADER}export {};\n`;
    }

    const { columns, indexes } = usedImports(tables);
    const importParts = [...indexes, ...columns].sort();
    const knownTables = new Set(tables.map((table) => table.name));

    const tableBlocks = tables.map((table) => renderDrizzleTable(table, knownTables)).join("\n\n");

    return `${GENERATED_HEADER}import { ${importParts.join(", ")} } from "@cirrus/server/drizzle";

${tableBlocks}
`;
};

/**
 * Emit drizzle `sqliteTable` definitions for the project schema, split into
 * `global` (D1-backed) and `shard` (DO-SQLite-backed) buckets. Tables marked
 * `.global()` go in the global file; everything else (default root + `.shardBy()`)
 * goes in the shard file.
 *
 * `searchIndexes` are intentionally not emitted — drizzle has no `sqliteTable`
 * abstraction for FTS5 virtual tables. FTS plumbing is handled by the runtime
 * outside of drizzle.
 */
export const emitDrizzleSchema = (schema: SchemaIR): { global: string; shard: string } => {
    const globalTables = schema.tables.filter((table) => table.shardMode === "global");
    const shardTables = schema.tables.filter((table) => table.shardMode !== "global");

    return {
        global: renderDrizzleFile(globalTables),
        shard: renderDrizzleFile(shardTables),
    };
};
