/**
 * Dart SDK target. Emits ONE pub package whose `lib/lunora_api.dart` is the
 * generated surface and whose `lib/lunora.dart` + `lib/src/` are a vendored copy
 * of the `sdks/dart` transport.
 *
 * ## Layout
 *
 * ```
 * <out>/pubspec.yaml           emitted (declares the package NAME, which is the identity)
 * <out>/lib/lunora.dart        vendored transport barrel
 * <out>/lib/src/               vendored transport (dart:convert / dart:typed_data only)
 * <out>/lib/lunora_api.dart    Api + one class per namespace; re-exports the transport
 * <out>/lib/models.dart        quicktype's data classes
 * ```
 *
 * One package, where Swift needs two targets and Python two sibling directories.
 * `import 'lunora.dart'` inside `lib/` is a FILE import, not a module import, so
 * the generated surface and the transport coexist in one package with no
 * boundary to cross. That in turn is why nothing in `sdks/dart/lib/` may name its
 * own package: the vendored copy resolves under whatever name the emitted
 * `pubspec.yaml` declares, and a `package:lunora/...` self-import would dangle.
 *
 * The consumer adds a path dependency and imports one file:
 *
 * ```yaml
 * dependencies:
 *   lunora_sdk:
 *     path: sdk/dart
 * ```
 *
 * ```dart
 * import 'package:lunora_sdk/lunora_api.dart';
 * ```
 *
 * Note the contrast with the Swift target, which has to spell the output
 * DIRECTORY's name because SwiftPM takes a path dependency's identity from the
 * last path component. pub takes it from the pubspec's `name:` field instead, so
 * the name below is the one a consumer writes regardless of where the SDK lands.
 *
 * ## Why quicktype's default renderer, with no `just-types`
 *
 * The two JVM targets emit their own models because quicktype's Java and Kotlin
 * backends rename properties and, under `just-types`, carry no mapping back to
 * the wire. The Dart backend renames properties too — a wire `2fa` becomes a
 * `the2Fa` field — but its DEFAULT output (that is, without `just-types`) writes
 * the exact wire key as a string literal in `fromJson`/`toJson`, and an enum
 * keeps its wire value in an `EnumValues` table. So the mapping is complete, and
 * it costs no dependency: the rendered file imports `dart:convert` and nothing
 * else. Measured against the same adversarial key set that defeated the JVM
 * backends (`2fa`, `ID`, `URLs`, `some-key`, `user_name`, `channelId`, and an
 * `image-url` enum); all seven survived.
 *
 * What that output gets WRONG is fixed here rather than by hand-rolling an
 * emitter — see {@link repairOptionals}, and `narrowBareExcept` in
 * `targets/python.ts` for the same pattern.
 */

import type { SdkMethod, SdkNamespace } from "../spec";
import { argsChoice, commentText, generatedHeaderLines, referencedModels, stringLiteral, toPascalCase } from "../spec";
import type { SdkRenderInput, SdkTarget } from "../target";

const GENERATED_HEADER = `${generatedHeaderLines("dart")
    .map((line) => `// ${line}`)
    .join("\n")}\n\n`;

/**
 * The emitted package manifest.
 *
 * The SDK constraint matches the transport's own `pubspec.yaml`: the vendored
 * sources are that package's, so a lower floor here would fail on whatever
 * language feature they use.
 */
const PUBSPEC = `# GENERATED by \`lunora sdk generate --lang dart\` — do not edit.
#
# The transport is vendored under lib/, so this package has no dependencies and
# nothing to fetch. Add it to a consuming app as a path dependency — pub takes a
# path dependency's identity from the "name" below, NOT from the directory, so
# this is the name you write no matter where you generated into:
#
#     dependencies:
#       lunora_sdk:
#         path: sdk/dart
#
#     import 'package:lunora_sdk/lunora_api.dart';
name: lunora_sdk
description: Generated Lunora SDK, transport included.
version: 0.0.0
publish_to: none

environment:
    sdk: ^3.6.0
`;

/**
 * Dart reserved words. Unlike Swift and Kotlin, Dart has no escape syntax for
 * one, so a colliding name takes a trailing underscore — the same shape the
 * Python target uses. A TRAILING underscore only; a leading one would make the
 * member private to the library and silently uncallable.
 */
const DART_KEYWORDS = new Set([
    "assert",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "else",
    "enum",
    "extends",
    "false",
    "final",
    "finally",
    "for",
    "if",
    "in",
    "is",
    "new",
    "null",
    "rethrow",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "var",
    "void",
    "while",
    "with",
]);

/** `list_messages` → `listMessages`; a reserved word takes a trailing underscore. */
const memberName = (raw: string): string => {
    const pascal = toPascalCase(raw);
    const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1);

    return DART_KEYWORDS.has(camel) ? `${camel}_` : camel;
};

/**
 * Escape a value for a Dart `"…"` literal.
 *
 * Dart interpolates `$`, exactly as Kotlin does, and `$` is a legal JavaScript
 * identifier character — so an export named `$client` would otherwise produce
 * `"billing:$client"`, which compiles, runs, and posts a variable's value as the
 * wire path. A wire KEY carries one just as easily, since it comes from a user's
 * own `v.object({ … })`.
 *
 * Layered ON TOP of `stringLiteral` rather than repeating its rules: escaping
 * backslashes in both would emit a literal that decodes to two of them. The
 * dollar pass runs last so the escape it inserts is not itself re-escaped.
 */
const dartLiteral = (value: string): string => stringLiteral(value).replaceAll("$", String.raw`\$`);

/**
 * Repair the two defects in quicktype's Dart output that would reach the wire.
 *
 * Both are unreachable by any renderer option, and both are the same shape as
 * bugs that already shipped in sibling ports and were caught only by a smoke
 * test that CALLED a generated method rather than merely compiling one.
 *
 * **1. An unset optional list is sent as `[]`.** quicktype renders
 * `field == null ? [] : List<dynamic>.from(field!.map(…))` in `toJson`, and the
 * mirror of it in `fromJson`. So `v.optional(v.array(…))` left unset arrives as
 * an empty array rather than as an absent key, and an absent key decodes to `[]`
 * rather than to null — so "the caller sent no list" and "the caller sent an
 * empty list" become indistinguishable in both directions. Rewritten to `null`,
 * which `LunoraClient.wireValue` then drops from the body.
 *
 * **2. An unset optional map THROWS.** quicktype renders `Map.from(field!)` for
 * a `v.record()` — a null-assertion on a field it just declared nullable — so
 * constructing or serialising a model whose optional record is unset dies with
 * "Null check operator used on a null value". Not a wire divergence: a hard
 * crash on the first call, in every generated Dart SDK whose schema has one.
 *
 * The `!` is what distinguishes the two cases, and it is quicktype's own
 * nullability marker rather than a guess: a REQUIRED record renders as
 * `Map.from(field)` with no `!` at all, so the rewrite cannot fire on one and
 * cannot introduce a null into a non-nullable field.
 */
const repairOptionals = (models: string): string =>
    models
        .replaceAll(" == null ? [] : List<", " == null ? null : List<")
        .replaceAll(/Map\.from\((?<source>[^()]*?)!\)/gu, "$<source> == null ? null : Map.from($<source>!)");

/** `wireValue` projects a generated model; an untyped argument is already a wire value. */
const dartPayload = (method: SdkMethod): string => argsChoice(method, { none: "null", typed: () => "LunoraClient.wireValue(args)", untyped: "args" });

/** The parameter list, before the trailing `{String? shardKey}` block. */
const dartParameters = (method: SdkMethod): string =>
    argsChoice(method, {
        none: "{String? shardKey}",
        // A function whose args no model can express (a `v.bigint()`/`v.bytes()`
        // schema, or a shape this backend could not name) still TAKES arguments —
        // wire-shaped ones. Dropping the parameter would make it uncallable.
        typed: (type) => `${type} args, {String? shardKey}`,
        untyped: "Object? args, {String? shardKey}",
    });

/** Rebuilds a typed result from the decoded wire value. */
const fromJson = (type: string, expression: string): string => `${type}.fromJson(${expression} as Map<String, dynamic>)`;

/** One function as a method posting the RPC envelope. */
const renderCall = (method: SdkMethod): string => {
    const call = `_client.${method.verb}("${dartLiteral(method.functionPath)}", args: ${dartPayload(method)}, shardKey: shardKey)`;

    if (method.resultType === undefined) {
        return [`  /// ${commentText(method.summary)}`, `  Future<Object?> ${memberName(method.functionName)}(${dartParameters(method)}) => ${call};`].join(
            "\n",
        );
    }

    return [
        `  /// ${commentText(method.summary)}`,
        `  Future<${method.resultType}> ${memberName(method.functionName)}(${dartParameters(method)}) async =>`,
        `      ${fromJson(method.resultType, `await ${call}`)};`,
    ].join("\n");
};

/**
 * A query's live-subscription methods. Only queries get them — the WS
 * `subscribe` frame names a query the server re-runs on every write to the
 * tables it read.
 *
 * Two of them, and the second is the reason this target exists at all: `watchX`
 * hands back a `Stream`, which is what a Flutter `StreamBuilder` consumes, so a
 * live query binds to a widget with no adapter and no lifecycle to manage — the
 * stream subscribes on first listen and unsubscribes when the widget is
 * disposed. `subscribeX` is the callback form every sibling port has, for a
 * value whose lifetime is not a widget's.
 */
const renderSubscribe = (method: SdkMethod): string => {
    // Two spellings of the same parameter rather than one trimmed at each use:
    // `subscribeX` takes a named block after it and `watchX` does not, so only
    // the first needs the trailing separator.
    const parameter = argsChoice(method, { none: "", typed: (type) => `${type} args`, untyped: "Object? args" });
    const leading = parameter === "" ? "" : `${parameter}, `;
    const payload = dartPayload(method);
    const path = `"${dartLiteral(method.functionPath)}"`;
    const watch = `_client.watch(${path}, args: ${payload})`;

    return [
        `  /// live ${commentText(method.summary)} — re-runs on every write to the tables it reads.`,
        `  LunoraUnsubscribe subscribe${toPascalCase(method.functionName)}(`,
        `    ${leading}{LunoraDataCallback? onData, LunoraErrorCallback? onError}`,
        `  ) => _client.subscribe(${path}, args: ${payload}, onData: onData, onError: onError);`,
        ``,
        `  /// live ${commentText(method.summary)}, as a Stream — bind it with StreamBuilder.`,
        method.resultType === undefined
            ? `  Stream<Object?> watch${toPascalCase(method.functionName)}(${parameter}) => ${watch};`
            : [
                  `  Stream<${method.resultType}> watch${toPascalCase(method.functionName)}(${parameter}) =>`,
                  `      ${watch}.map((raw) => ${fromJson(method.resultType, "raw")});`,
              ].join("\n"),
    ].join("\n");
};

const renderNamespaceClass = (namespace: SdkNamespace): string => {
    const typeName = `${toPascalCase(namespace.name)}Api`;

    const body = namespace.methods
        .map((method) => (method.verb === "query" ? `${renderCall(method)}\n\n${renderSubscribe(method)}` : renderCall(method)))
        .join("\n\n");

    return [
        `/// Functions declared in \`${commentText(namespace.name)}\`.`,
        `class ${typeName} {`,
        `  const ${typeName}(this._client);`,
        ``,
        `  final LunoraClient _client;`,
        ``,
        body,
        `}`,
    ].join("\n");
};

const render = ({ models, namespaces }: SdkRenderInput): Record<string, string> => {
    const fields = namespaces.map((namespace) => `  final ${toPascalCase(namespace.name)}Api ${memberName(namespace.name)};`).join("\n");
    const initialisers = namespaces.map((namespace) => `        ${memberName(namespace.name)} = ${toPascalCase(namespace.name)}Api(client)`).join(",\n");

    // Imported only when a model is actually referenced; `export` does not bring
    // the names into this library's own scope, so the two are not redundant.
    const modelImport = referencedModels(namespaces).length > 0 ? `import 'models.dart';\n` : "";

    const api = [
        GENERATED_HEADER,
        `/// The generated Lunora surface. Re-exports the vendored transport, so one\n`,
        `/// import gives a consumer the client, the wire types and the models.\n`,
        `library;\n`,
        `\n`,
        `export 'lunora.dart';\n`,
        `export 'models.dart';\n`,
        `\n`,
        `import 'lunora.dart';\n`,
        modelImport,
        `\n`,
        namespaces.map((namespace) => renderNamespaceClass(namespace)).join("\n\n"),
        namespaces.length > 0 ? `\n\n` : ``,
        `/// Typed entry point: \`Api(client).<namespace>.<function>(args)\`.\n`,
        `class Api {\n`,
        namespaces.length > 0 ? `  Api(LunoraClient client)\n      : ${initialisers.trimStart()};\n\n${fields}\n` : `  const Api(LunoraClient client);\n`,
        `}\n`,
    ].join("");

    return {
        "lib/lunora_api.dart": api,
        "lib/models.dart":
            models.length > 0
                ? `${GENERATED_HEADER}${repairOptionals(models)}\n`
                : `${GENERATED_HEADER}// No typed argument or result schemas in this deployment.\n`,
        "pubspec.yaml": PUBSPEC,
    };
};

const dartTarget: SdkTarget = {
    id: "dart",
    // No `just-types`: it strips the very `fromJson`/`toJson` pair that carries
    // the wire names, which is the whole reason this backend can be used at all
    // where Java's and Kotlin's could not. See the module comment.
    quicktype: { lang: "dart" },
    render,
    // Nothing. The transport imports only `dart:convert`, `dart:typed_data` and
    // `dart:async`, and quicktype's Dart models import only `dart:convert` — so
    // unlike the Ruby and Rust targets, the models add no dependency either.
    requires: [],
    // The whole `lib/` in one entry: the barrel and `src/` land at the same paths
    // they occupy here, and the generated files sit beside them.
    vendor: [{ from: "lib", to: "lib" }],
};

export { dartLiteral, dartTarget, memberName, repairOptionals };
