// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "@lunora/client";

export interface ApiTypes {
    usage: {
        callsSince: FunctionReference<"action", { since: string }, number>;
        count: FunctionReference<"query", {}, number>;
    };
}

export const api: ApiTypes = {
    usage: {
        callsSince: { __lunoraRef: "usage:callsSince" },
        count: { __lunoraRef: "usage:count" },
    },
};
