// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "@lunora/client";

export interface ApiTypes {
    notes: {
        add: FunctionReference<"mutation", { body: string; boardId: string }, import("@lunora/values").Id<"notes">>;
        list: FunctionReference<"query", { boardId: string }, import("./dataModel.js").Doc_notes[]>;
    };
}

export const api: ApiTypes = {
    notes: {
        add: { __lunoraRef: "notes:add" },
        list: { __lunoraRef: "notes:list" },
    },
};
