// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export type TableName = "notes" | "boards";

/**
 * The tables **this app declared** — every {@link TableName} except those an add-on
 * contributed through `defineSchema(...).extend(...)`.
 *
 * An add-on's tables are real tables and stay in `TableName` (they are queryable,
 * they appear in `DataModel`), but an app enumerating "my tables" should not have to
 * know they exist: an account-deletion sweep, an export, a migration allowlist, or a
 * helper generic over a table union is about the app's own data, and every add-on
 * added or removed would otherwise silently change the correct answer.
 *
 * ```ts
 * // Doesn't need to mention `ratelimit_buckets`, and won't drift when an add-on lands.
 * const EXPORTED: readonly AppTableName[] = ["nodes", "tagColors"];
 * ```
 */
export type AppTableName = "notes" | "boards";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_notes {
    _id: Id<"notes">;
    _creationTime: number;
    boardId: string;
    body: string;
    ownerId: string;
}

export interface Doc_boards {
    _id: Id<"boards">;
    _creationTime: number;
    name: string;
    ownerId: string;
}

export interface DataModel {
    notes: Doc_notes;
    boards: Doc_boards;
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. `never` for tables without secondary indexes.
 * Used by `TableReader.withIndex()` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
    notes: "by_board";
    boards: "by_owner";
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. `never` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
    notes: never;
    boards: never;
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Per-table rank-index name union. `never` for tables without a rankIndex. */
export interface RankIndexNamesByTable {
    notes: never;
    boards: never;
}

export type RankIndexName<T extends keyof DataModel> = RankIndexNamesByTable[T];

/** Per-table geo-index name union. `never` for tables without a geoIndex. */
export interface GeoIndexNamesByTable {
    notes: never;
    boards: never;
}

export type GeoIndexName<T extends keyof DataModel> = GeoIndexNamesByTable[T];

/** Union of declared vector index names. `never` when none are declared. */
export type VectorIndexName = never;

export interface Insert_notes {
    _id?: Id<"notes">;
    _creationTime?: number;
    boardId: string;
    body: string;
    ownerId: string;
}

export interface Insert_boards {
    _id?: Id<"boards">;
    _creationTime?: number;
    name: string;
    ownerId: string;
}

/** Per-table insert shape, accepted by `ctx.db.<table>.insert(...)`. */
export interface InsertModel {
    notes: Insert_notes;
    boards: Insert_boards;
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the `with` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. `{}` for tables with none. */
export interface Relations {
    notes: {};
    boards: {};
}

