// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, sqliteTable, text } from "@lunora/server/drizzle";

export const boards = sqliteTable("boards", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    name: text("name").notNull(),
    ownerId: text("ownerId").notNull(),
}, (t) => ({
    by_owner: index("by_owner").on(t.ownerId),
}));
