// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { blob, index, integer, real, sqliteTable, text, uniqueIndex } from "@lunora/server/drizzle";

export const cells = sqliteTable("cells", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cloudflareAccountId: text("cloudflareAccountId").notNull(),
    createdAt: real("createdAt").notNull(),
    dispatchNamespacePrefix: text("dispatchNamespacePrefix").notNull(),
    jurisdiction: text("jurisdiction"),
    name: text("name").notNull(),
    status: text("status").notNull(),
    usageReadAtMs: real("usageReadAtMs"),
}, (t) => ({
    by_name: uniqueIndex("by_name").on(t.name),
}));

export const organizations = sqliteTable("organizations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cellId: text("cellId").references(() => cells._id).notNull(),
    createdAt: real("createdAt").notNull(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    spendCapMinor: real("spendCapMinor"),
    suspendedAt: real("suspendedAt"),
    suspendedReason: text("suspendedReason"),
    paymentFailedAt: real("paymentFailedAt"),
    creditsAccountId: text("creditsAccountId"),
    deletionRequestedAt: real("deletionRequestedAt"),
}, (t) => ({
    by_slug: uniqueIndex("by_slug").on(t.slug),
}));

export const members = sqliteTable("members", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    role: text("role").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_org_user: index("by_org_user").on(t.organizationId, t.userId),
}));

export const projects = sqliteTable("projects", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    activeDeploymentId: text("activeDeploymentId"),
    activeScriptName: text("activeScriptName"),
    createdAt: real("createdAt").notNull(),
    framework: text("framework"),
    githubRepo: text("githubRepo"),
    name: text("name").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    slug: text("slug").notNull(),
}, (t) => ({
    by_org_slug: uniqueIndex("by_org_slug").on(t.organizationId, t.slug),
    by_github_repo: index("by_github_repo").on(t.githubRepo),
}));

export const deployments = sqliteTable("deployments", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    adminToken: text("adminToken"),
    alias: text("alias"),
    branch: text("branch"),
    cronSpecs: text("cronSpecs", { mode: "json" }).$type<Array<string>>(),
    bundleHash: text("bundleHash"),
    createdAt: real("createdAt").notNull(),
    createdBy: text("createdBy").notNull(),
    expiresAt: real("expiresAt"),
    kind: text("kind").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    projectId: text("projectId").references(() => projects._id).notNull(),
    scriptName: text("scriptName").notNull(),
    status: text("status").notNull(),
    updatedAt: real("updatedAt").notNull(),
    url: text("url"),
    version: real("version"),
    runtimeVersion: text("runtimeVersion"),
    queuedAt: real("queuedAt"),
    provisioningAt: real("provisioningAt"),
    verifyingAt: real("verifyingAt"),
    liveAt: real("liveAt"),
    supersededAt: real("supersededAt"),
    failedAt: real("failedAt"),
    destroyedAt: real("destroyedAt"),
    teardownAt: real("teardownAt"),
}, (t) => ({
    by_script: index("by_script").on(t.scriptName),
    by_project: index("by_project").on(t.projectId),
    by_kind: index("by_kind").on(t.kind),
    by_alias: index("by_alias").on(t.alias),
}));

export const deployKeys = sqliteTable("deployKeys", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    capability: text("capability", { mode: "json" }).$type<"deploy" | "ingest">(),
    createdAt: real("createdAt").notNull(),
    hashedKey: text("hashedKey").notNull(),
    lastUsedAt: real("lastUsedAt"),
    name: text("name").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    projectId: text("projectId").references(() => projects._id),
    revokedAt: real("revokedAt"),
    type: text("type").notNull(),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
    by_hash: uniqueIndex("by_hash").on(t.hashedKey),
}));

export const overageDebits = sqliteTable("overageDebits", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    debitedCredits: real("debitedCredits").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    periodStart: real("periodStart").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_org_period: uniqueIndex("by_org_period").on(t.organizationId, t.periodStart),
}));

export const tenantLogs = sqliteTable("tenantLogs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    fields: text("fields", { mode: "json" }).$type<Record<string, unknown>>(),
    functionPath: text("functionPath"),
    level: text("level", { mode: "json" }).$type<"trace" | "debug" | "info" | "log" | "warn" | "error" | "fatal">().notNull(),
    message: text("message").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    scriptName: text("scriptName").notNull(),
    shardKey: text("shardKey"),
    spanId: text("spanId"),
    traceId: text("traceId"),
    userId: text("userId"),
}, (t) => ({
    by_trace: index("by_trace").on(t.organizationId, t.traceId),
    by_script_time: index("by_script_time").on(t.scriptName, t.createdAt),
    by_org: index("by_org").on(t.organizationId),
}));

export const observations = sqliteTable("observations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    attributes: text("attributes", { mode: "json" }).$type<Record<string, string>>(),
    completionTokens: real("completionTokens"),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id),
    durationMs: real("durationMs").notNull(),
    endedAt: real("endedAt").notNull(),
    functionPath: text("functionPath"),
    input: text("input"),
    kind: text("kind", { mode: "json" }).$type<"container" | "generation" | "worker">().notNull(),
    level: text("level", { mode: "json" }).$type<"error" | "info">().notNull(),
    model: text("model"),
    name: text("name").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    output: text("output"),
    parentSpanId: text("parentSpanId"),
    promptTokens: real("promptTokens"),
    serviceName: text("serviceName"),
    spanId: text("spanId").notNull(),
    startedAt: real("startedAt").notNull(),
    statusMessage: text("statusMessage"),
    traceId: text("traceId").notNull(),
}, (t) => ({
    by_org_deployment_started: index("by_org_deployment_started").on(t.organizationId, t.deploymentId, t.startedAt),
    by_org_started: index("by_org_started").on(t.organizationId, t.startedAt),
    by_trace: index("by_trace").on(t.organizationId, t.traceId),
    by_org: index("by_org").on(t.organizationId),
}));

export const githubInstallations = sqliteTable("githubInstallations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    accountLogin: text("accountLogin").notNull(),
    claimedAt: real("claimedAt"),
    createdAt: real("createdAt").notNull(),
    installationId: real("installationId").notNull(),
    organizationId: text("organizationId").references(() => organizations._id),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
    by_installation: uniqueIndex("by_installation").on(t.installationId),
}));

export const builds = sqliteTable("builds", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    branch: text("branch").notNull(),
    bundleHash: text("bundleHash"),
    commitSha: text("commitSha").notNull(),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId"),
    error: text("error"),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    processingBy: text("processingBy"),
    processingStartedAt: real("processingStartedAt"),
    projectId: text("projectId").references(() => projects._id).notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "building" | "successful" | "failed">().notNull(),
    updatedAt: real("updatedAt").notNull(),
    buildingAt: real("buildingAt"),
    successfulAt: real("successfulAt"),
    failedAt: real("failedAt"),
}, (t) => ({
    by_project_commit: index("by_project_commit").on(t.projectId, t.commitSha),
    by_project: index("by_project").on(t.projectId),
}));

export const buildLogs = sqliteTable("buildLogs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    buildId: text("buildId").references(() => builds._id).notNull(),
    createdAt: real("createdAt").notNull(),
    level: text("level", { mode: "json" }).$type<"info" | "error">().notNull(),
    line: text("line").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
}, (t) => ({
    by_build: index("by_build").on(t.buildId),
}));

export const domains = sqliteTable("domains", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    customHostnameId: text("customHostnameId"),
    createdAt: real("createdAt").notNull(),
    hostname: text("hostname").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    projectId: text("projectId").references(() => projects._id).notNull(),
    redirectStatusCode: real("redirectStatusCode"),
    redirectTo: text("redirectTo"),
    txtToken: text("txtToken").notNull(),
    updatedAt: real("updatedAt").notNull(),
    verifiedAt: real("verifiedAt"),
}, (t) => ({
    by_project: index("by_project").on(t.projectId),
    by_hostname: uniqueIndex("by_hostname").on(t.hostname),
}));

export const auditLog = sqliteTable("auditLog", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action").notNull(),
    actorUserId: text("actorUserId").notNull(),
    createdAt: real("createdAt").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    target: text("target"),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
}));

export const invitations = sqliteTable("invitations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    email: text("email").notNull(),
    expiresAt: real("expiresAt").notNull(),
    invitedBy: text("invitedBy").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    role: text("role").notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "accepted" | "revoked">().notNull(),
    tokenHash: text("tokenHash").notNull(),
}, (t) => ({
    by_token: uniqueIndex("by_token").on(t.tokenHash),
    by_org: index("by_org").on(t.organizationId),
}));

export const platformUsage = sqliteTable("platformUsage", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id),
    kind: text("kind", { mode: "json" }).$type<"requests" | "cpuMs" | "storageBytes">().notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    periodStart: real("periodStart").notNull(),
    quantity: real("quantity").notNull(),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
}));

export const issues = sqliteTable("issues", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    count: real("count").notNull(),
    createdAt: real("createdAt").notNull(),
    culprit: text("culprit").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id),
    firstSeen: real("firstSeen").notNull(),
    hash: text("hash").notNull(),
    lastSeen: real("lastSeen").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    sampleMessage: text("sampleMessage").notNull(),
    status: text("status", { mode: "json" }).$type<"open" | "resolved">().notNull(),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_org_culprit: index("by_org_culprit").on(t.organizationId, t.culprit),
    by_org_hash: uniqueIndex("by_org_hash").on(t.organizationId, t.hash),
    by_org: index("by_org").on(t.organizationId),
}));

export const incidents = sqliteTable("incidents", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    closedAt: real("closedAt"),
    container: text("container"),
    count: real("count").notNull(),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id),
    hash: text("hash").notNull(),
    instance: text("instance"),
    kind: text("kind", { mode: "json" }).$type<"crash_loop" | "oom" | "error_spike">().notNull(),
    lastSeen: real("lastSeen").notNull(),
    openedAt: real("openedAt").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    status: text("status", { mode: "json" }).$type<"open" | "resolved">().notNull(),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_org_hash: uniqueIndex("by_org_hash").on(t.organizationId, t.hash),
    by_org: index("by_org").on(t.organizationId),
}));

export const alertRules = sqliteTable("alertRules", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    channel: text("channel", { mode: "json" }).$type<"email" | "webhook">().notNull(),
    createdAt: real("createdAt").notNull(),
    destination: text("destination").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull(),
    name: text("name").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    target: text("target", { mode: "json" }).$type<"issue" | "incident" | "uptime">().notNull(),
    threshold: real("threshold").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
}));

export const alerts = sqliteTable("alerts", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    body: text("body").notNull(),
    channel: text("channel", { mode: "json" }).$type<"email" | "webhook">().notNull(),
    createdAt: real("createdAt").notNull(),
    deliveredAt: real("deliveredAt"),
    destination: text("destination").notNull(),
    hash: text("hash").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    ruleId: text("ruleId").references(() => alertRules._id).notNull(),
    status: text("status", { mode: "json" }).$type<"firing" | "delivered" | "failed">().notNull(),
    subject: text("subject").notNull(),
    target: text("target", { mode: "json" }).$type<"issue" | "incident" | "uptime">().notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_org: index("by_org").on(t.organizationId),
}));

export const uptimeChecks = sqliteTable("uptimeChecks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id).notNull(),
    error: text("error"),
    latencyMs: real("latencyMs"),
    ok: integer("ok", { mode: "boolean" }).notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    statusCode: real("statusCode"),
}, (t) => ({
    by_org_deployment: index("by_org_deployment").on(t.organizationId, t.deploymentId),
    by_org: index("by_org").on(t.organizationId),
}));

export const uptimeState = sqliteTable("uptimeState", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    consecutiveFailures: real("consecutiveFailures").notNull(),
    createdAt: real("createdAt").notNull(),
    deploymentId: text("deploymentId").references(() => deployments._id).notNull(),
    lastCheckedAt: real("lastCheckedAt").notNull(),
    lastOk: integer("lastOk", { mode: "boolean" }).notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_org: index("by_org").on(t.organizationId),
    by_deployment: index("by_deployment").on(t.deploymentId),
}));

export const secrets = sqliteTable("secrets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    ciphertext: text("ciphertext").notNull(),
    createdAt: real("createdAt").notNull(),
    environment: text("environment", { mode: "json" }).$type<"all" | "production" | "preview" | "dev">().notNull(),
    iv: text("iv").notNull(),
    name: text("name").notNull(),
    organizationId: text("organizationId").references(() => organizations._id).notNull(),
    projectId: text("projectId").references(() => projects._id).notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_project_env_name: uniqueIndex("by_project_env_name").on(t.projectId, t.environment, t.name),
    by_project: index("by_project").on(t.projectId),
}));

export const customers = sqliteTable("customers", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    email: text("email"),
    provider: text("provider").notNull(),
    providerCustomerId: text("providerCustomerId").notNull(),
    referenceId: text("referenceId").notNull(),
}, (t) => ({
    by_reference: index("by_reference").on(t.referenceId),
    by_provider_customer: uniqueIndex("by_provider_customer").on(t.provider, t.providerCustomerId),
}));

export const events = sqliteTable("events", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    processedAt: real("processedAt").notNull(),
    provider: text("provider").notNull(),
    providerEventId: text("providerEventId").notNull(),
    type: text("type").notNull(),
}, (t) => ({
    by_provider_event: uniqueIndex("by_provider_event").on(t.provider, t.providerEventId),
}));

export const paymentSessions = sqliteTable("paymentSessions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    amountMinor: blob("amountMinor", { mode: "bigint" }).notNull(),
    capturedMinor: blob("capturedMinor", { mode: "bigint" }).notNull(),
    createdAt: real("createdAt").notNull(),
    currency: text("currency").notNull(),
    provider: text("provider").notNull(),
    providerSessionId: text("providerSessionId").notNull(),
    referenceId: text("referenceId").notNull(),
    refundedMinor: blob("refundedMinor", { mode: "bigint" }).notNull(),
    state: text("state").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_reference: index("by_reference").on(t.referenceId),
    by_provider_session: uniqueIndex("by_provider_session").on(t.provider, t.providerSessionId),
}));

export const subscriptions = sqliteTable("subscriptions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cancelAtPeriodEnd: integer("cancelAtPeriodEnd", { mode: "boolean" }).notNull(),
    createdAt: real("createdAt").notNull(),
    currentPeriodEnd: real("currentPeriodEnd"),
    currentPeriodStart: real("currentPeriodStart"),
    priceId: text("priceId").notNull(),
    provider: text("provider").notNull(),
    providerSubscriptionId: text("providerSubscriptionId").notNull(),
    quantity: real("quantity").notNull(),
    referenceId: text("referenceId").notNull(),
    state: text("state").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_reference: index("by_reference").on(t.referenceId),
    by_provider_subscription: uniqueIndex("by_provider_subscription").on(t.provider, t.providerSubscriptionId),
}));

export const usageEvents = sqliteTable("usageEvents", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    featureId: text("featureId").notNull(),
    idempotencyKey: text("idempotencyKey").notNull(),
    provider: text("provider").notNull(),
    quantity: real("quantity").notNull(),
    referenceId: text("referenceId").notNull(),
    reportedToProvider: integer("reportedToProvider", { mode: "boolean" }).notNull(),
}, (t) => ({
    by_reference_feature: index("by_reference_feature").on(t.referenceId, t.featureId),
    by_idempotency: uniqueIndex("by_idempotency").on(t.provider, t.idempotencyKey),
}));
