// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "@lunora/server/drizzle";

export const rateLimits = sqliteTable("rateLimits", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    prev: real("prev"),
    ts: real("ts").notNull(),
    value: real("value").notNull(),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));
