// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_alerts_0 from "../alerts.js";
import * as lunora_audit_log_1 from "../audit-log.js";
import * as lunora_billing_2 from "../billing.js";
import * as lunora_builds_3 from "../builds.js";
import * as lunora_cells_4 from "../cells.js";
import * as lunora_deploy_keys_5 from "../deploy-keys.js";
import * as lunora_deployments_6 from "../deployments.js";
import * as lunora_domains_7 from "../domains.js";
import * as lunora_fanout_8 from "../fanout.js";
import * as lunora_github_installations_9 from "../github-installations.js";
import * as lunora_incidents_10 from "../incidents.js";
import * as lunora_invitations_11 from "../invitations.js";
import * as lunora_issues_12 from "../issues.js";
import * as lunora_logs_13 from "../logs.js";
import * as lunora_members_14 from "../members.js";
import * as lunora_organizations_15 from "../organizations.js";
import * as lunora_projects_16 from "../projects.js";
import * as lunora_secrets_17 from "../secrets.js";
import * as lunora_telemetry_18 from "../telemetry.js";
import * as lunora_usage_19 from "../usage.js";

import { DEFER_VALIDATION as DEFER, installCompiledValidatorMap } from "@lunora/values";
import { LunoraError } from "@lunora/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";
import type { Id } from "./dataModel.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "alerts:createRule": lunora_alerts_0.createRule as unknown as RegisteredLunoraFunction,
    "alerts:deleteRule": lunora_alerts_0.deleteRule as unknown as RegisteredLunoraFunction,
    "alerts:list": lunora_alerts_0.list as unknown as RegisteredLunoraFunction,
    "alerts:markDelivered": lunora_alerts_0.markDelivered as unknown as RegisteredLunoraFunction,
    "alerts:rules": lunora_alerts_0.rules as unknown as RegisteredLunoraFunction,
    "alerts:setRuleEnabled": lunora_alerts_0.setRuleEnabled as unknown as RegisteredLunoraFunction,
    "audit_log:list": lunora_audit_log_1.list as unknown as RegisteredLunoraFunction,
    "audit_log:record": lunora_audit_log_1.record as unknown as RegisteredLunoraFunction,
    "billing:checkout": lunora_billing_2.checkout as unknown as RegisteredLunoraFunction,
    "billing:enforceDunning": lunora_billing_2.enforceDunning as unknown as RegisteredLunoraFunction,
    "billing:entitlements": lunora_billing_2.entitlements as unknown as RegisteredLunoraFunction,
    "billing:portal": lunora_billing_2.portal as unknown as RegisteredLunoraFunction,
    "billing:processWebhook": lunora_billing_2.processWebhook as unknown as RegisteredLunoraFunction,
    "billing:subscription": lunora_billing_2.subscription as unknown as RegisteredLunoraFunction,
    "builds:appendLog": lunora_builds_3.appendLog as unknown as RegisteredLunoraFunction,
    "builds:claimNext": lunora_builds_3.claimNext as unknown as RegisteredLunoraFunction,
    "builds:complete": lunora_builds_3.complete as unknown as RegisteredLunoraFunction,
    "builds:expireStale": lunora_builds_3.expireStale as unknown as RegisteredLunoraFunction,
    "builds:fail": lunora_builds_3.fail as unknown as RegisteredLunoraFunction,
    "builds:listByProject": lunora_builds_3.listByProject as unknown as RegisteredLunoraFunction,
    "builds:logs": lunora_builds_3.logs as unknown as RegisteredLunoraFunction,
    "builds:recordPush": lunora_builds_3.recordPush as unknown as RegisteredLunoraFunction,
    "cells:list": lunora_cells_4.list as unknown as RegisteredLunoraFunction,
    "cells:register": lunora_cells_4.register as unknown as RegisteredLunoraFunction,
    "deploy_keys:issue": lunora_deploy_keys_5.issue as unknown as RegisteredLunoraFunction,
    "deploy_keys:list": lunora_deploy_keys_5.list as unknown as RegisteredLunoraFunction,
    "deploy_keys:revoke": lunora_deploy_keys_5.revoke as unknown as RegisteredLunoraFunction,
    "deploy_keys:verify": lunora_deploy_keys_5.verify as unknown as RegisteredLunoraFunction,
    "deployments:activate": lunora_deployments_6.activate as unknown as RegisteredLunoraFunction,
    "deployments:adminTarget": lunora_deployments_6.adminTarget as unknown as RegisteredLunoraFunction,
    "deployments:cleanupExpiredPreviews": lunora_deployments_6.cleanupExpiredPreviews as unknown as RegisteredLunoraFunction,
    "deployments:create": lunora_deployments_6.create as unknown as RegisteredLunoraFunction,
    "deployments:listByProject": lunora_deployments_6.listByProject as unknown as RegisteredLunoraFunction,
    "deployments:planForScript": lunora_deployments_6.planForScript as unknown as RegisteredLunoraFunction,
    "deployments:pruneSuperseded": lunora_deployments_6.pruneSuperseded as unknown as RegisteredLunoraFunction,
    "deployments:rollback": lunora_deployments_6.rollback as unknown as RegisteredLunoraFunction,
    "deployments:routeForAlias": lunora_deployments_6.routeForAlias as unknown as RegisteredLunoraFunction,
    "deployments:updateStatus": lunora_deployments_6.updateStatus as unknown as RegisteredLunoraFunction,
    "domains:add": lunora_domains_7.add as unknown as RegisteredLunoraFunction,
    "domains:get": lunora_domains_7.get as unknown as RegisteredLunoraFunction,
    "domains:list": lunora_domains_7.list as unknown as RegisteredLunoraFunction,
    "domains:markVerified": lunora_domains_7.markVerified as unknown as RegisteredLunoraFunction,
    "domains:remove": lunora_domains_7.remove as unknown as RegisteredLunoraFunction,
    "domains:routeForHostname": lunora_domains_7.routeForHostname as unknown as RegisteredLunoraFunction,
    "fanout:tick": lunora_fanout_8.tick as unknown as RegisteredLunoraFunction,
    "github_installations:claim": lunora_github_installations_9.claim as unknown as RegisteredLunoraFunction,
    "github_installations:list": lunora_github_installations_9.list as unknown as RegisteredLunoraFunction,
    "github_installations:record": lunora_github_installations_9.record as unknown as RegisteredLunoraFunction,
    "github_installations:remove": lunora_github_installations_9.remove as unknown as RegisteredLunoraFunction,
    "incidents:list": lunora_incidents_10.list as unknown as RegisteredLunoraFunction,
    "incidents:setStatus": lunora_incidents_10.setStatus as unknown as RegisteredLunoraFunction,
    "incidents:triage": lunora_incidents_10.triage as unknown as RegisteredLunoraFunction,
    "invitations:accept": lunora_invitations_11.accept as unknown as RegisteredLunoraFunction,
    "invitations:invite": lunora_invitations_11.invite as unknown as RegisteredLunoraFunction,
    "invitations:list": lunora_invitations_11.list as unknown as RegisteredLunoraFunction,
    "invitations:revoke": lunora_invitations_11.revoke as unknown as RegisteredLunoraFunction,
    "issues:list": lunora_issues_12.list as unknown as RegisteredLunoraFunction,
    "issues:setStatus": lunora_issues_12.setStatus as unknown as RegisteredLunoraFunction,
    "logs:ingest": lunora_logs_13.ingest as unknown as RegisteredLunoraFunction,
    "logs:list": lunora_logs_13.list as unknown as RegisteredLunoraFunction,
    "logs:prune": lunora_logs_13.prune as unknown as RegisteredLunoraFunction,
    "members:add": lunora_members_14.add as unknown as RegisteredLunoraFunction,
    "members:list": lunora_members_14.list as unknown as RegisteredLunoraFunction,
    "members:remove": lunora_members_14.remove as unknown as RegisteredLunoraFunction,
    "members:setRole": lunora_members_14.setRole as unknown as RegisteredLunoraFunction,
    "organizations:cancelDeletion": lunora_organizations_15.cancelDeletion as unknown as RegisteredLunoraFunction,
    "organizations:create": lunora_organizations_15.create as unknown as RegisteredLunoraFunction,
    "organizations:getBySlug": lunora_organizations_15.getBySlug as unknown as RegisteredLunoraFunction,
    "organizations:linkCreditsAccount": lunora_organizations_15.linkCreditsAccount as unknown as RegisteredLunoraFunction,
    "organizations:list": lunora_organizations_15.list as unknown as RegisteredLunoraFunction,
    "organizations:purgeDeleted": lunora_organizations_15.purgeDeleted as unknown as RegisteredLunoraFunction,
    "organizations:rename": lunora_organizations_15.rename as unknown as RegisteredLunoraFunction,
    "organizations:requestDeletion": lunora_organizations_15.requestDeletion as unknown as RegisteredLunoraFunction,
    "projects:byGithubRepo": lunora_projects_16.byGithubRepo as unknown as RegisteredLunoraFunction,
    "projects:create": lunora_projects_16.create as unknown as RegisteredLunoraFunction,
    "projects:listByOrg": lunora_projects_16.listByOrg as unknown as RegisteredLunoraFunction,
    "projects:rename": lunora_projects_16.rename as unknown as RegisteredLunoraFunction,
    "secrets:list": lunora_secrets_17.list as unknown as RegisteredLunoraFunction,
    "secrets:listEncrypted": lunora_secrets_17.listEncrypted as unknown as RegisteredLunoraFunction,
    "secrets:remove": lunora_secrets_17.remove as unknown as RegisteredLunoraFunction,
    "secrets:store": lunora_secrets_17.store as unknown as RegisteredLunoraFunction,
    "telemetry:ingest": lunora_telemetry_18.ingest as unknown as RegisteredLunoraFunction,
    "usage:enforceSpendCaps": lunora_usage_19.enforceSpendCaps as unknown as RegisteredLunoraFunction,
    "usage:ingest": lunora_usage_19.ingest as unknown as RegisteredLunoraFunction,
    "usage:overageWatermark": lunora_usage_19.overageWatermark as unknown as RegisteredLunoraFunction,
    "usage:record": lunora_usage_19.record as unknown as RegisteredLunoraFunction,
    "usage:recordOverageDebit": lunora_usage_19.recordOverageDebit as unknown as RegisteredLunoraFunction,
    "usage:rollup": lunora_usage_19.rollup as unknown as RegisteredLunoraFunction,
    "usage:series": lunora_usage_19.series as unknown as RegisteredLunoraFunction,
    "usage:summary": lunora_usage_19.summary as unknown as RegisteredLunoraFunction,
};

/**
 * AOT-compiled argument validators (Worker-safe, no `eval`). Each is installed
 * onto its function's live `.args` object and consulted by the interpreted
 * parser as a zero-allocation fast path; anything it can't model is deferred.
 */
installCompiledValidatorMap(lunora_alerts_0.deleteRule.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_alerts_0.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_alerts_0.markDelivered.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["deployKey"] !== "string") return DEFER;
if (!Array.isArray(source["ids"])) return DEFER;
const __arr1 = new Array(source["ids"].length);
for (let __i1 = 0; __i1 < source["ids"].length; __i1++) {
const __e1 = source["ids"][__i1];
if (typeof __e1 !== "string") return DEFER;
__arr1[__i1] = __e1;
}
if (typeof source["organizationId"] !== "string") return DEFER;
return { "deployKey": source["deployKey"], "ids": __arr1, "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_alerts_0.rules.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_alerts_0.setRuleEnabled.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["enabled"] !== "boolean") return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "enabled": source["enabled"], "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_audit_log_1.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_audit_log_1.record.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["action"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
let __has1 = false;
let __val1;
if (source["target"] !== undefined) {
if (typeof source["target"] !== "string") return DEFER;
__val1 = source["target"];
__has1 = true;
}
return { "action": source["action"], "organizationId": source["organizationId"], ...(__has1 ? { "target": __val1 } : {}) };
});
installCompiledValidatorMap(lunora_billing_2.checkout.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["cancelUrl"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["priceId"] !== "string") return DEFER;
if (typeof source["successUrl"] !== "string") return DEFER;
return { "cancelUrl": source["cancelUrl"], "organizationId": source["organizationId"], "priceId": source["priceId"], "successUrl": source["successUrl"] };
});
installCompiledValidatorMap(lunora_billing_2.entitlements.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_billing_2.portal.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["returnUrl"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "returnUrl": source["returnUrl"] };
});
installCompiledValidatorMap(lunora_billing_2.processWebhook.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["body"] !== "string") return DEFER;
if (typeof source["signature"] !== "string") return DEFER;
return { "body": source["body"], "signature": source["signature"] };
});
installCompiledValidatorMap(lunora_billing_2.subscription.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_builds_3.claimNext.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["runnerId"] !== "string") return DEFER;
return { "runnerId": source["runnerId"] };
});
installCompiledValidatorMap(lunora_builds_3.complete.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["buildId"] !== "string") return DEFER;
if (typeof source["bundleHash"] !== "string") return DEFER;
let __has1 = false;
let __val1;
if (source["deploymentId"] !== undefined) {
if (typeof source["deploymentId"] !== "string") return DEFER;
__val1 = source["deploymentId"];
__has1 = true;
}
if (typeof source["runnerId"] !== "string") return DEFER;
return { "buildId": source["buildId"], "bundleHash": source["bundleHash"], ...(__has1 ? { "deploymentId": __val1 } : {}), "runnerId": source["runnerId"] };
});
installCompiledValidatorMap(lunora_builds_3.fail.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["buildId"] !== "string") return DEFER;
if (typeof source["error"] !== "string") return DEFER;
if (typeof source["runnerId"] !== "string") return DEFER;
return { "buildId": source["buildId"], "error": source["error"], "runnerId": source["runnerId"] };
});
installCompiledValidatorMap(lunora_builds_3.listByProject.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["projectId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "projectId": source["projectId"] };
});
installCompiledValidatorMap(lunora_builds_3.logs.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["afterCreatedAt"] !== undefined) {
if (typeof source["afterCreatedAt"] !== "number" || !Number.isFinite(source["afterCreatedAt"])) return DEFER;
__val1 = source["afterCreatedAt"];
__has1 = true;
}
if (typeof source["buildId"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { ...(__has1 ? { "afterCreatedAt": __val1 } : {}), "buildId": source["buildId"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_builds_3.recordPush.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["branch"] !== "string") return DEFER;
if (typeof source["commitSha"] !== "string") return DEFER;
if (typeof source["installationId"] !== "number" || !Number.isFinite(source["installationId"])) return DEFER;
if (typeof source["repository"] !== "string") return DEFER;
return { "branch": source["branch"], "commitSha": source["commitSha"], "installationId": source["installationId"], "repository": source["repository"] };
});
installCompiledValidatorMap(lunora_cells_4.register.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["cloudflareAccountId"] !== "string") return DEFER;
if (typeof source["dispatchNamespacePrefix"] !== "string") return DEFER;
let __has1 = false;
let __val1;
if (source["jurisdiction"] !== undefined) {
if (typeof source["jurisdiction"] !== "string") return DEFER;
__val1 = source["jurisdiction"];
__has1 = true;
}
if (typeof source["name"] !== "string") return DEFER;
return { "cloudflareAccountId": source["cloudflareAccountId"], "dispatchNamespacePrefix": source["dispatchNamespacePrefix"], ...(__has1 ? { "jurisdiction": __val1 } : {}), "name": source["name"] };
});
installCompiledValidatorMap(lunora_deploy_keys_5.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_deploy_keys_5.revoke.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_deploy_keys_5.verify.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["key"] !== "string") return DEFER;
return { "key": source["key"] };
});
installCompiledValidatorMap(lunora_deployments_6.activate.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["deployKey"] !== undefined) {
if (typeof source["deployKey"] !== "string") return DEFER;
__val1 = source["deployKey"];
__has1 = true;
}
if (typeof source["id"] !== "string") return DEFER;
return { ...(__has1 ? { "deployKey": __val1 } : {}), "id": source["id"] };
});
installCompiledValidatorMap(lunora_deployments_6.adminTarget.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["deploymentId"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "deploymentId": source["deploymentId"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_deployments_6.listByProject.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["projectId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "projectId": source["projectId"] };
});
installCompiledValidatorMap(lunora_deployments_6.planForScript.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["scriptName"] !== "string") return DEFER;
return { "scriptName": source["scriptName"] };
});
installCompiledValidatorMap(lunora_deployments_6.rollback.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["deployKey"] !== undefined) {
if (typeof source["deployKey"] !== "string") return DEFER;
__val1 = source["deployKey"];
__has1 = true;
}
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { ...(__has1 ? { "deployKey": __val1 } : {}), "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_deployments_6.routeForAlias.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["alias"] !== "string") return DEFER;
return { "alias": source["alias"] };
});
installCompiledValidatorMap(lunora_domains_7.add.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["hostname"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["projectId"] !== "string") return DEFER;
let __has1 = false;
let __val1;
if (source["redirectStatusCode"] !== undefined) {
if (typeof source["redirectStatusCode"] !== "number" || !Number.isFinite(source["redirectStatusCode"])) return DEFER;
__val1 = source["redirectStatusCode"];
__has1 = true;
}
let __has2 = false;
let __val2;
if (source["redirectTo"] !== undefined) {
if (typeof source["redirectTo"] !== "string") return DEFER;
__val2 = source["redirectTo"];
__has2 = true;
}
return { "hostname": source["hostname"], "organizationId": source["organizationId"], "projectId": source["projectId"], ...(__has1 ? { "redirectStatusCode": __val1 } : {}), ...(__has2 ? { "redirectTo": __val2 } : {}) };
});
installCompiledValidatorMap(lunora_domains_7.get.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_domains_7.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["projectId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "projectId": source["projectId"] };
});
installCompiledValidatorMap(lunora_domains_7.markVerified.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["customHostnameId"] !== undefined) {
if (typeof source["customHostnameId"] !== "string") return DEFER;
__val1 = source["customHostnameId"];
__has1 = true;
}
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["verified"] !== "boolean") return DEFER;
return { ...(__has1 ? { "customHostnameId": __val1 } : {}), "id": source["id"], "organizationId": source["organizationId"], "verified": source["verified"] };
});
installCompiledValidatorMap(lunora_domains_7.remove.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_domains_7.routeForHostname.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["hostname"] !== "string") return DEFER;
return { "hostname": source["hostname"] };
});
installCompiledValidatorMap(lunora_github_installations_9.claim.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["installationId"] !== "number" || !Number.isFinite(source["installationId"])) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "installationId": source["installationId"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_github_installations_9.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_github_installations_9.record.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["accountLogin"] !== "string") return DEFER;
if (typeof source["installationId"] !== "number" || !Number.isFinite(source["installationId"])) return DEFER;
return { "accountLogin": source["accountLogin"], "installationId": source["installationId"] };
});
installCompiledValidatorMap(lunora_github_installations_9.remove.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["installationId"] !== "number" || !Number.isFinite(source["installationId"])) return DEFER;
return { "installationId": source["installationId"] };
});
installCompiledValidatorMap(lunora_incidents_10.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_incidents_10.triage.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_invitations_11.accept.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["token"] !== "string") return DEFER;
return { "token": source["token"] };
});
installCompiledValidatorMap(lunora_invitations_11.invite.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["email"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "email": source["email"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_invitations_11.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_invitations_11.revoke.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_issues_12.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_logs_13.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["afterCreatedAt"] !== undefined) {
if (typeof source["afterCreatedAt"] !== "number" || !Number.isFinite(source["afterCreatedAt"])) return DEFER;
__val1 = source["afterCreatedAt"];
__has1 = true;
}
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["scriptName"] !== "string") return DEFER;
return { ...(__has1 ? { "afterCreatedAt": __val1 } : {}), "organizationId": source["organizationId"], "scriptName": source["scriptName"] };
});
installCompiledValidatorMap(lunora_members_14.add.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["userId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "userId": source["userId"] };
});
installCompiledValidatorMap(lunora_members_14.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_members_14.remove.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_organizations_15.cancelDeletion.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_organizations_15.getBySlug.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["slug"] !== "string") return DEFER;
return { "slug": source["slug"] };
});
installCompiledValidatorMap(lunora_organizations_15.linkCreditsAccount.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["creditsAccountId"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "creditsAccountId": source["creditsAccountId"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_organizations_15.rename.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["name"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "name": source["name"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_organizations_15.requestDeletion.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_projects_16.byGithubRepo.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["repository"] !== "string") return DEFER;
return { "repository": source["repository"] };
});
installCompiledValidatorMap(lunora_projects_16.create.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["framework"] !== undefined) {
if (typeof source["framework"] !== "string") return DEFER;
__val1 = source["framework"];
__has1 = true;
}
let __has2 = false;
let __val2;
if (source["githubRepo"] !== undefined) {
if (typeof source["githubRepo"] !== "string") return DEFER;
__val2 = source["githubRepo"];
__has2 = true;
}
if (typeof source["name"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["slug"] !== "string") return DEFER;
return { ...(__has1 ? { "framework": __val1 } : {}), ...(__has2 ? { "githubRepo": __val2 } : {}), "name": source["name"], "organizationId": source["organizationId"], "slug": source["slug"] };
});
installCompiledValidatorMap(lunora_projects_16.listByOrg.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_projects_16.rename.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["name"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "name": source["name"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_secrets_17.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["projectId"] !== "string") return DEFER;
return { "organizationId": source["organizationId"], "projectId": source["projectId"] };
});
installCompiledValidatorMap(lunora_secrets_17.remove.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["id"] !== "string") return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
return { "id": source["id"], "organizationId": source["organizationId"] };
});
installCompiledValidatorMap(lunora_usage_19.ingest.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["deployKey"] !== "string") return DEFER;
let __has1 = false;
let __val1;
if (source["deploymentId"] !== undefined) {
if (typeof source["deploymentId"] !== "string") return DEFER;
__val1 = source["deploymentId"];
__has1 = true;
}
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
if (typeof source["quantity"] !== "number" || !Number.isFinite(source["quantity"])) return DEFER;
return { "deployKey": source["deployKey"], ...(__has1 ? { "deploymentId": __val1 } : {}), "organizationId": source["organizationId"], "periodStart": source["periodStart"], "quantity": source["quantity"] };
});
installCompiledValidatorMap(lunora_usage_19.overageWatermark.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
return { "organizationId": source["organizationId"], "periodStart": source["periodStart"] };
});
installCompiledValidatorMap(lunora_usage_19.record.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
let __has1 = false;
let __val1;
if (source["deploymentId"] !== undefined) {
if (typeof source["deploymentId"] !== "string") return DEFER;
__val1 = source["deploymentId"];
__has1 = true;
}
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
if (typeof source["quantity"] !== "number" || !Number.isFinite(source["quantity"])) return DEFER;
return { ...(__has1 ? { "deploymentId": __val1 } : {}), "organizationId": source["organizationId"], "periodStart": source["periodStart"], "quantity": source["quantity"] };
});
installCompiledValidatorMap(lunora_usage_19.recordOverageDebit.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["debitedCredits"] !== "number" || !Number.isFinite(source["debitedCredits"])) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
return { "debitedCredits": source["debitedCredits"], "organizationId": source["organizationId"], "periodStart": source["periodStart"] };
});
installCompiledValidatorMap(lunora_usage_19.series.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
return { "organizationId": source["organizationId"], "periodStart": source["periodStart"] };
});
installCompiledValidatorMap(lunora_usage_19.summary.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (typeof source["periodStart"] !== "number" || !Number.isFinite(source["periodStart"])) return DEFER;
return { "organizationId": source["organizationId"], "periodStart": source["periodStart"] };
});

/**
 * Connection-lifecycle manifest: the function paths the generated ShardDO
 * dispatches when a client's WebSocket connects (`connect`) or disconnects
 * (`disconnect`). Each path also resolves through {@link LUNORA_FUNCTIONS}; the
 * DO runs every hook under the socket's verified identity via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[] } = {
    connect: [],
    disconnect: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    alerts: {
        createRule: (args: { channel: "email" | "webhook"; destination: string; name: string; organizationId: Id<"organizations">; target: "issue" | "incident"; threshold: number }) => Promise<Id<"alertRules">>;
        deleteRule: (args: { id: Id<"alertRules">; organizationId: Id<"organizations"> }) => Promise<Id<"alertRules">>;
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"alerts">; channel: "email" | "webhook"; createdAt: number; deliveredAt?: number; destination: string; status: "delivered" | "failed" | "firing"; subject: string; target: "incident" | "issue" }[]>;
        markDelivered: (args: { deployKey: string; ids: Array<Id<"alerts">>; organizationId: Id<"organizations"> }) => Promise<{ delivered: number; }>;
        rules: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"alertRules">; channel: "email" | "webhook"; createdAt: number; destination: string; enabled: boolean; name: string; organizationId: Id<"organizations">; target: "incident" | "issue"; threshold: number }[]>;
        setRuleEnabled: (args: { enabled: boolean; id: Id<"alertRules">; organizationId: Id<"organizations"> }) => Promise<Id<"alertRules">>;
    };
    audit_log: {
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"auditLog">; action: string; actorUserId: string; createdAt: number; organizationId: Id<"organizations">; target?: string }[]>;
        record: (args: { action: string; organizationId: Id<"organizations">; target?: string }) => Promise<Id<"auditLog">>;
    };
    billing: {
        checkout: (args: { cancelUrl: string; organizationId: Id<"organizations">; priceId: string; successUrl: string }) => Promise<{ url: string; }>;
        enforceDunning: (args?: {}) => Promise<{ graced: number; recovered: number; suspended: number; }>;
        entitlements: (args: { organizationId: Id<"organizations"> }) => Promise<{ features: string[]; limits: Record<"members" | "previewDeployments" | "projects", number>; plans: string[]; }>;
        portal: (args: { organizationId: Id<"organizations">; returnUrl: string }) => Promise<{ url: string; }>;
        processWebhook: (args: { body: string; signature: string }) => Promise<{ applied: boolean; status: number; }>;
        subscription: (args: { organizationId: Id<"organizations"> }) => Promise<{ cancelAtPeriodEnd?: false | true; currentPeriodEnd?: number; priceId: string; provider: string; referenceId: string; state: string }[]>;
    };
    builds: {
        appendLog: (args: { buildId: Id<"builds">; level: "info" | "error"; line: string; runnerId: string }) => Promise<void>;
        claimNext: (args: { runnerId: string }) => Promise<{ buildId: Id<"builds">; commitSha: string; projectId: Id<"projects">; } | null>;
        complete: (args: { buildId: Id<"builds">; bundleHash: string; deploymentId?: string; runnerId: string }) => Promise<void>;
        expireStale: (args?: {}) => Promise<{ expired: number; }>;
        fail: (args: { buildId: Id<"builds">; error: string; runnerId: string }) => Promise<void>;
        listByProject: (args: { organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<{ _id: Id<"builds">; branch: string; bundleHash?: string; commitSha: string; createdAt: number; organizationId: Id<"organizations">; processingBy?: string; processingStartedAt?: number; projectId: Id<"projects">; status: "failed" | "building" | "pending" | "successful" }[]>;
        logs: (args: { afterCreatedAt?: number; buildId: Id<"builds">; organizationId: Id<"organizations"> }) => Promise<{ createdAt: number; level: "error" | "info"; line: string; }[]>;
        recordPush: (args: { branch: string; commitSha: string; installationId: number; repository: string }) => Promise<{ buildId: Id<"builds">; reused: boolean; } | null>;
    };
    cells: {
        list: (args?: {}) => Promise<{ _id: Id<"cells">; cloudflareAccountId: string; createdAt: number; dispatchNamespacePrefix: string; jurisdiction?: string; name: string; status: "active" | "draining" | "suspended" }[]>;
        register: (args: { cloudflareAccountId: string; dispatchNamespacePrefix: string; jurisdiction?: string; name: string }) => Promise<Id<"cells">>;
    };
    deploy_keys: {
        issue: (args: { name: string; organizationId: Id<"organizations">; projectId?: Id<"projects">; type: "production" | "dev" | "preview" }) => Promise<{ id: Id<"deployKeys">; key: string; }>;
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"deployKeys">; createdAt: number; lastUsedAt?: number; name: string; organizationId: Id<"organizations">; projectId?: Id<"projects">; revokedAt?: number; type: "dev" | "preview" | "production" }[]>;
        revoke: (args: { id: Id<"deployKeys">; organizationId: Id<"organizations"> }) => Promise<void>;
        verify: (args: { key: string }) => Promise<{ deployKeyId: Id<"deployKeys">; organizationId: Id<"organizations">; projectId?: Id<"projects">; type: "dev" | "preview" | "production"; } | null>;
    };
    deployments: {
        activate: (args: { deployKey?: string; id: Id<"deployments"> }) => Promise<void>;
        adminTarget: (args: { deploymentId: Id<"deployments">; organizationId: Id<"organizations"> }) => Promise<{ adminToken: string; url: string; } | null>;
        cleanupExpiredPreviews: (args?: {}) => Promise<{ destroyed: number; }>;
        create: (args: { adminToken?: string; branch?: string; cronSpecs?: Array<string>; deployKey?: string; kind: "production" | "preview" | "dev"; organizationId: Id<"organizations">; projectId: Id<"projects">; runtimeVersion?: string; scriptName: string }) => Promise<{ deploymentId: Id<"deployments">; scriptName: string; version: number; }>;
        listByProject: (args: { organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<{ _id: Id<"deployments">; adminToken?: string; alias?: string; branch?: string; bundleHash?: string; createdAt: number; createdBy: string; expiresAt?: number; kind: "dev" | "preview" | "production"; organizationId: Id<"organizations">; projectId: Id<"projects">; scriptName: string; status: "failed" | "building" | "destroyed" | "live" | "provisioning" | "queued" | "superseded" | "verifying"; updatedAt: number; url?: string; version?: number }[]>;
        planForScript: (args: { scriptName: string }) => Promise<{ plan: string; }>;
        pruneSuperseded: (args?: {}) => Promise<{ pruned: number; }>;
        rollback: (args: { deployKey?: string; id: Id<"deployments">; organizationId: Id<"organizations"> }) => Promise<{ scriptName: string; version?: number; }>;
        routeForAlias: (args: { alias: string }) => Promise<{ scriptName: string; } | null>;
        updateStatus: (args: { bundleHash?: string; deployKey?: string; id: Id<"deployments">; status: "queued" | "provisioning" | "building" | "verifying" | "live" | "superseded" | "failed" | "destroyed"; url?: string }) => Promise<void>;
    };
    domains: {
        add: (args: { hostname: string; organizationId: Id<"organizations">; projectId: Id<"projects">; redirectStatusCode?: number; redirectTo?: string }) => Promise<{ id: Id<"domains">; txtName: string; txtToken: string; }>;
        get: (args: { id: Id<"domains">; organizationId: Id<"organizations"> }) => Promise<null | { _id: Id<"domains">; createdAt: number; customHostnameId?: string; hostname: string; organizationId: Id<"organizations">; projectId: Id<"projects">; redirectStatusCode?: number; redirectTo?: string; txtToken: string; updatedAt: number; verifiedAt?: number }>;
        list: (args: { organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<{ _id: Id<"domains">; createdAt: number; customHostnameId?: string; hostname: string; organizationId: Id<"organizations">; projectId: Id<"projects">; redirectStatusCode?: number; redirectTo?: string; txtToken: string; updatedAt: number; verifiedAt?: number }[]>;
        markVerified: (args: { customHostnameId?: string; id: Id<"domains">; organizationId: Id<"organizations">; verified: boolean }) => Promise<void>;
        remove: (args: { id: Id<"domains">; organizationId: Id<"organizations"> }) => Promise<void>;
        routeForHostname: (args: { hostname: string }) => Promise<{ redirectStatusCode?: number; redirectTo?: string; scriptName?: string; } | null>;
    };
    fanout: {
        tick: (args?: {}) => Promise<{ ok: true; }>;
    };
    github_installations: {
        claim: (args: { installationId: number; organizationId: Id<"organizations"> }) => Promise<void>;
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"githubInstallations">; accountLogin: string; claimedAt?: number; createdAt: number; installationId: number; organizationId?: Id<"organizations"> }[]>;
        record: (args: { accountLogin: string; installationId: number }) => Promise<Id<"githubInstallations">>;
        remove: (args: { installationId: number }) => Promise<void>;
    };
    incidents: {
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"incidents">; closedAt?: number; container?: string; count: number; instance?: string; kind: "crash_loop" | "error_spike" | "oom"; lastSeen: number; openedAt: number; organizationId: Id<"organizations">; status: "open" | "resolved"; title: string }[]>;
        setStatus: (args: { id: Id<"incidents">; organizationId: Id<"organizations">; status: unknown }) => Promise<Id<"incidents">>;
        triage: (args: { id: Id<"incidents">; organizationId: Id<"organizations"> }) => Promise<{ summary: string; }>;
    };
    invitations: {
        accept: (args: { token: string }) => Promise<{ organizationId: Id<"organizations">; }>;
        invite: (args: { email: string; organizationId: Id<"organizations"> }) => Promise<{ id: Id<"invitations">; token: string; }>;
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ organizationId: Id<"organizations">; email: string; status: "pending" | "accepted" | "revoked"; _id: Id<"invitations">; createdAt: number; expiresAt: number; invitedBy: string; role: "admin" | "member" | "owner" | "viewer" }[]>;
        revoke: (args: { id: Id<"invitations">; organizationId: Id<"organizations"> }) => Promise<void>;
    };
    issues: {
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"issues">; count: number; culprit: string; firstSeen: number; hash: string; lastSeen: number; organizationId: Id<"organizations">; sampleMessage: string; status: "open" | "resolved"; title: string }[]>;
        setStatus: (args: { id: Id<"issues">; organizationId: Id<"organizations">; status: unknown }) => Promise<Id<"issues">>;
    };
    logs: {
        ingest: (args: { deployKey: string; lines: Array<{ createdAt: number | undefined; level: "log" | "warn" | "error"; line: string }>; organizationId: Id<"organizations">; scriptName: string }) => Promise<{ ingested: number; }>;
        list: (args: { afterCreatedAt?: number; organizationId: Id<"organizations">; scriptName: string }) => Promise<{ createdAt: number; level: "error" | "log" | "warn"; line: string; }[]>;
        prune: (args?: {}) => Promise<{ pruned: number; }>;
    };
    members: {
        add: (args: { organizationId: Id<"organizations">; userId: string }) => Promise<Id<"members">>;
        list: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"members">; createdAt: number; organizationId: Id<"organizations">; role: "admin" | "member" | "owner" | "viewer"; userId: string }[]>;
        remove: (args: { id: Id<"members">; organizationId: Id<"organizations"> }) => Promise<void>;
        setRole: (args: { id: Id<"members">; organizationId: Id<"organizations">; role: "owner" | "admin" | "member" | "viewer" }) => Promise<void>;
    };
    organizations: {
        cancelDeletion: (args: { organizationId: Id<"organizations"> }) => Promise<void>;
        create: (args: { cellId?: Id<"cells">; jurisdiction?: string; name: string; plan?: "free" | "pro" | "enterprise"; slug: string }) => Promise<Id<"organizations">>;
        getBySlug: (args: { slug: string }) => Promise<null | { _id: Id<"organizations">; cellId: Id<"cells">; createdAt: number; name: string; plan: "enterprise" | "free" | "pro"; slug: string }>;
        linkCreditsAccount: (args: { creditsAccountId: string; organizationId: Id<"organizations"> }) => Promise<void>;
        list: (args?: {}) => Promise<{ _id: Id<"organizations">; cellId: Id<"cells">; createdAt: number; name: string; plan: "enterprise" | "free" | "pro"; slug: string }[]>;
        purgeDeleted: (args?: {}) => Promise<{ purged: number; }>;
        rename: (args: { name: string; organizationId: Id<"organizations"> }) => Promise<void>;
        requestDeletion: (args: { organizationId: Id<"organizations"> }) => Promise<void>;
    };
    projects: {
        byGithubRepo: (args: { repository: string }) => Promise<{ organizationId: Id<"organizations">; projectId: Id<"projects">; slug: string; } | null>;
        create: (args: { framework?: string; githubRepo?: string; name: string; organizationId: Id<"organizations">; slug: string }) => Promise<Id<"projects">>;
        listByOrg: (args: { organizationId: Id<"organizations"> }) => Promise<{ _id: Id<"projects">; createdAt: number; framework?: string; githubRepo?: string; name: string; organizationId: Id<"organizations">; slug: string }[]>;
        rename: (args: { id: Id<"projects">; name: string; organizationId: Id<"organizations"> }) => Promise<void>;
    };
    secrets: {
        list: (args: { organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<{ createdAt: number; environment: string; id: Id<"secrets">; name: string; updatedAt: number; }[]>;
        listEncrypted: (args: { deployKey?: string; environment?: "production" | "preview" | "dev"; organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<{ ciphertext: string; iv: string; name: string; }[]>;
        remove: (args: { id: Id<"secrets">; organizationId: Id<"organizations"> }) => Promise<void>;
        store: (args: { ciphertext: string; environment?: "all" | "production" | "preview" | "dev"; iv: string; name: string; organizationId: Id<"organizations">; projectId: Id<"projects"> }) => Promise<Id<"secrets">>;
    };
    telemetry: {
        ingest: (args: { deployKey: string; deploymentId?: Id<"deployments">; events: Array<unknown>; organizationId: Id<"organizations"> }) => Promise<{ alerts: { body: string; channel: "email" | "webhook"; destination: string; id: Id<"alerts">; subject: string; }[]; incidents: number; issues: number; }>;
    };
    usage: {
        enforceSpendCaps: (args?: {}) => Promise<{ suspended: number; unsuspended: number; }>;
        ingest: (args: { deployKey: string; deploymentId?: Id<"deployments">; organizationId: Id<"organizations">; periodStart: number; quantity: number }) => Promise<Id<"platformUsage">>;
        overageWatermark: (args: { organizationId: Id<"organizations">; periodStart: number }) => Promise<{ debitedCredits: number; }>;
        record: (args: { deploymentId?: Id<"deployments">; organizationId: Id<"organizations">; periodStart: number; quantity: number }) => Promise<Id<"platformUsage">>;
        recordOverageDebit: (args: { debitedCredits: number; organizationId: Id<"organizations">; periodStart: number }) => Promise<void>;
        rollup: (args?: {}) => Promise<{ compacted: number; }>;
        series: (args: { organizationId: Id<"organizations">; periodStart: number }) => Promise<{ cpuMs: number; day: number; requests: number; }[]>;
        summary: (args: { organizationId: Id<"organizations">; periodStart: number }) => Promise<Record<"requests" | "cpuMs" | "storageBytes", number>>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    alerts: {
        createRule: (args) => callRegistered(context, "alerts:createRule", args),
        deleteRule: (args) => callRegistered(context, "alerts:deleteRule", args),
        list: (args) => callRegistered(context, "alerts:list", args),
        markDelivered: (args) => callRegistered(context, "alerts:markDelivered", args),
        rules: (args) => callRegistered(context, "alerts:rules", args),
        setRuleEnabled: (args) => callRegistered(context, "alerts:setRuleEnabled", args),
    },
    audit_log: {
        list: (args) => callRegistered(context, "audit_log:list", args),
        record: (args) => callRegistered(context, "audit_log:record", args),
    },
    billing: {
        checkout: (args) => callRegistered(context, "billing:checkout", args),
        enforceDunning: (args) => callRegistered(context, "billing:enforceDunning", args),
        entitlements: (args) => callRegistered(context, "billing:entitlements", args),
        portal: (args) => callRegistered(context, "billing:portal", args),
        processWebhook: (args) => callRegistered(context, "billing:processWebhook", args),
        subscription: (args) => callRegistered(context, "billing:subscription", args),
    },
    builds: {
        appendLog: (args) => callRegistered(context, "builds:appendLog", args),
        claimNext: (args) => callRegistered(context, "builds:claimNext", args),
        complete: (args) => callRegistered(context, "builds:complete", args),
        expireStale: (args) => callRegistered(context, "builds:expireStale", args),
        fail: (args) => callRegistered(context, "builds:fail", args),
        listByProject: (args) => callRegistered(context, "builds:listByProject", args),
        logs: (args) => callRegistered(context, "builds:logs", args),
        recordPush: (args) => callRegistered(context, "builds:recordPush", args),
    },
    cells: {
        list: (args) => callRegistered(context, "cells:list", args),
        register: (args) => callRegistered(context, "cells:register", args),
    },
    deploy_keys: {
        issue: (args) => callRegistered(context, "deploy_keys:issue", args),
        list: (args) => callRegistered(context, "deploy_keys:list", args),
        revoke: (args) => callRegistered(context, "deploy_keys:revoke", args),
        verify: (args) => callRegistered(context, "deploy_keys:verify", args),
    },
    deployments: {
        activate: (args) => callRegistered(context, "deployments:activate", args),
        adminTarget: (args) => callRegistered(context, "deployments:adminTarget", args),
        cleanupExpiredPreviews: (args) => callRegistered(context, "deployments:cleanupExpiredPreviews", args),
        create: (args) => callRegistered(context, "deployments:create", args),
        listByProject: (args) => callRegistered(context, "deployments:listByProject", args),
        planForScript: (args) => callRegistered(context, "deployments:planForScript", args),
        pruneSuperseded: (args) => callRegistered(context, "deployments:pruneSuperseded", args),
        rollback: (args) => callRegistered(context, "deployments:rollback", args),
        routeForAlias: (args) => callRegistered(context, "deployments:routeForAlias", args),
        updateStatus: (args) => callRegistered(context, "deployments:updateStatus", args),
    },
    domains: {
        add: (args) => callRegistered(context, "domains:add", args),
        get: (args) => callRegistered(context, "domains:get", args),
        list: (args) => callRegistered(context, "domains:list", args),
        markVerified: (args) => callRegistered(context, "domains:markVerified", args),
        remove: (args) => callRegistered(context, "domains:remove", args),
        routeForHostname: (args) => callRegistered(context, "domains:routeForHostname", args),
    },
    fanout: {
        tick: (args) => callRegistered(context, "fanout:tick", args),
    },
    github_installations: {
        claim: (args) => callRegistered(context, "github_installations:claim", args),
        list: (args) => callRegistered(context, "github_installations:list", args),
        record: (args) => callRegistered(context, "github_installations:record", args),
        remove: (args) => callRegistered(context, "github_installations:remove", args),
    },
    incidents: {
        list: (args) => callRegistered(context, "incidents:list", args),
        setStatus: (args) => callRegistered(context, "incidents:setStatus", args),
        triage: (args) => callRegistered(context, "incidents:triage", args),
    },
    invitations: {
        accept: (args) => callRegistered(context, "invitations:accept", args),
        invite: (args) => callRegistered(context, "invitations:invite", args),
        list: (args) => callRegistered(context, "invitations:list", args),
        revoke: (args) => callRegistered(context, "invitations:revoke", args),
    },
    issues: {
        list: (args) => callRegistered(context, "issues:list", args),
        setStatus: (args) => callRegistered(context, "issues:setStatus", args),
    },
    logs: {
        ingest: (args) => callRegistered(context, "logs:ingest", args),
        list: (args) => callRegistered(context, "logs:list", args),
        prune: (args) => callRegistered(context, "logs:prune", args),
    },
    members: {
        add: (args) => callRegistered(context, "members:add", args),
        list: (args) => callRegistered(context, "members:list", args),
        remove: (args) => callRegistered(context, "members:remove", args),
        setRole: (args) => callRegistered(context, "members:setRole", args),
    },
    organizations: {
        cancelDeletion: (args) => callRegistered(context, "organizations:cancelDeletion", args),
        create: (args) => callRegistered(context, "organizations:create", args),
        getBySlug: (args) => callRegistered(context, "organizations:getBySlug", args),
        linkCreditsAccount: (args) => callRegistered(context, "organizations:linkCreditsAccount", args),
        list: (args) => callRegistered(context, "organizations:list", args),
        purgeDeleted: (args) => callRegistered(context, "organizations:purgeDeleted", args),
        rename: (args) => callRegistered(context, "organizations:rename", args),
        requestDeletion: (args) => callRegistered(context, "organizations:requestDeletion", args),
    },
    projects: {
        byGithubRepo: (args) => callRegistered(context, "projects:byGithubRepo", args),
        create: (args) => callRegistered(context, "projects:create", args),
        listByOrg: (args) => callRegistered(context, "projects:listByOrg", args),
        rename: (args) => callRegistered(context, "projects:rename", args),
    },
    secrets: {
        list: (args) => callRegistered(context, "secrets:list", args),
        listEncrypted: (args) => callRegistered(context, "secrets:listEncrypted", args),
        remove: (args) => callRegistered(context, "secrets:remove", args),
        store: (args) => callRegistered(context, "secrets:store", args),
    },
    telemetry: {
        ingest: (args) => callRegistered(context, "telemetry:ingest", args),
    },
    usage: {
        enforceSpendCaps: (args) => callRegistered(context, "usage:enforceSpendCaps", args),
        ingest: (args) => callRegistered(context, "usage:ingest", args),
        overageWatermark: (args) => callRegistered(context, "usage:overageWatermark", args),
        record: (args) => callRegistered(context, "usage:record", args),
        recordOverageDebit: (args) => callRegistered(context, "usage:recordOverageDebit", args),
        rollup: (args) => callRegistered(context, "usage:rollup", args),
        series: (args) => callRegistered(context, "usage:series", args),
        summary: (args) => callRegistered(context, "usage:summary", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
