// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    documents: {
        create: FunctionReference<"mutation", { title: string; body: string }, Id<"documents">>;
        list: FunctionReference<"query", {}, { _id: Id<"documents">; body: string; createdAt: number; ownerId: string; title: string }[]>;
    };
}

export const api: ApiTypes = {
    documents: {
        create: { __lunoraRef: "documents:create" },
        list: { __lunoraRef: "documents:list" },
    },
};
