// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_documents_0 from "../documents.js";

import { DEFER_VALIDATION as DEFER, installCompiledValidatorMap } from "lunorash/values";
import { LunoraError } from "lunorash/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";
import type { Id } from "./dataModel.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * Present on a `"stream"` declared `durable`: its run is persisted and
     * survives the socket that opened it. Absent on every other kind, and on an
     * ephemeral stream.
     */
    durable?: { ttlMs?: number };
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /**
     * The lifecycle moment a hook fires on, when this registration came from
     * `onConnect`/`onDisconnect`/`onShardInit`/`onQueryChange`. Read at
     * dispatch to decide whether the function runs system-trusted: `init` and
     * `reactor` have no caller identity, so RLS has no user to scope to.
     */
    lifecycle?: "connect" | "disconnect" | "init" | "reactor";
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "documents:create": lunora_documents_0.create as unknown as RegisteredLunoraFunction,
    "documents:list": lunora_documents_0.list as unknown as RegisteredLunoraFunction,
};

/**
 * AOT-compiled argument validators (Worker-safe, no `eval`). Each is installed
 * onto its function's live `.args` object and consulted by the interpreted
 * parser as a zero-allocation fast path; anything it can't model is deferred.
 */
installCompiledValidatorMap(lunora_documents_0.create.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (source["organizationId"].length > 128) return DEFER;
if (typeof source["title"] !== "string") return DEFER;
if (source["title"].length > 256) return DEFER;
if (typeof source["body"] !== "string") return DEFER;
if (source["body"].length > 100000) return DEFER;
return { "organizationId": source["organizationId"], "title": source["title"], "body": source["body"] };
});
installCompiledValidatorMap(lunora_documents_0.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["organizationId"] !== "string") return DEFER;
if (source["organizationId"].length > 128) return DEFER;
return { "organizationId": source["organizationId"] };
});

/**
 * Lifecycle manifest: the function paths the generated ShardDO dispatches when a
 * client's WebSocket connects (`connect`) or disconnects (`disconnect`), once
 * per Durable Object instance before any handler runs (`init`), and after a
 * write flush when a watched read's result changed (`reactor`). Each path also
 * resolves through {@link LUNORA_FUNCTIONS}. The socket sides run under the
 * socket's verified identity; `init` and `reactor` have no caller, so they run
 * anonymous — all via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[]; init: readonly string[]; reactor: readonly string[] } = {
    connect: [],
    disconnect: [],
    init: [],
    reactor: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    documents: {
        create: (args: { organizationId: string; title: string; body: string }) => Promise<Id<"documents">>;
        list: (args: { organizationId: string }) => Promise<{ _id: Id<"documents">; organizationId: string; ownerId: string; title: string; body: string; createdAt: number }[]>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    documents: {
        create: (args) => callRegistered(context, "documents:create", args),
        list: (args) => callRegistered(context, "documents:list", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
