// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export type TableName = "cursors";

/**
 * The tables **this app declared** — every {@link TableName} except those an add-on
 * contributed through `defineSchema(...).extend(...)`.
 *
 * An add-on's tables are real tables and stay in `TableName` (they are queryable,
 * they appear in `DataModel`), but an app enumerating "my tables" should not have to
 * know they exist: an account-deletion sweep, an export, a migration allowlist, or a
 * helper generic over a table union is about the app's own data, and every add-on
 * added or removed would otherwise silently change the correct answer.
 *
 * ```ts
 * // Doesn't need to mention `ratelimit_buckets`, and won't drift when an add-on lands.
 * const EXPORTED: readonly AppTableName[] = ["nodes", "tagColors"];
 * ```
 */
export type AppTableName = "cursors";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_cursors {
    _id: Id<"cursors">;
    _creationTime: number;
    roomId: string;
    sessionId: string;
    name: string;
    color: string;
    x: number;
    y: number;
    lastSeen: number;
}

export interface DataModel {
    cursors: Doc_cursors;
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. `never` for tables without secondary indexes.
 * Used by `TableReader.withIndex()` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
    cursors: "by_room_session";
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. `never` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
    cursors: never;
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Per-table rank-index name union. `never` for tables without a rankIndex. */
export interface RankIndexNamesByTable {
    cursors: never;
}

export type RankIndexName<T extends keyof DataModel> = RankIndexNamesByTable[T];

/** Per-table geo-index name union. `never` for tables without a geoIndex. */
export interface GeoIndexNamesByTable {
    cursors: never;
}

export type GeoIndexName<T extends keyof DataModel> = GeoIndexNamesByTable[T];

/** Union of declared vector index names. `never` when none are declared. */
export type VectorIndexName = never;

export interface Insert_cursors {
    _id?: Id<"cursors">;
    _creationTime?: number;
    roomId: string;
    sessionId: string;
    name: string;
    color: string;
    x: number;
    y: number;
    lastSeen: number;
}

/** Per-table insert shape, accepted by `ctx.db.<table>.insert(...)`. */
export interface InsertModel {
    cursors: Insert_cursors;
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the `with` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. `{}` for tables with none. */
export interface Relations {
    cursors: {};
}

