// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text, uniqueIndex } from "lunorash/server/drizzle";

export const cursors = sqliteTable("cursors", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    roomId: text("roomId").notNull(),
    sessionId: text("sessionId").notNull(),
    name: text("name").notNull(),
    color: text("color").notNull(),
    x: real("x").notNull(),
    y: real("y").notNull(),
    lastSeen: real("lastSeen").notNull(),
}, (t) => ({
    by_room_session: uniqueIndex("by_room_session").on(t.roomId, t.sessionId),
}));

export const ratelimit_buckets = sqliteTable("ratelimit_buckets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    value: real("value").notNull(),
    ts: real("ts").notNull(),
    prev: real("prev"),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));
