// The TanStack Start SSR handler `rsbuild build` emits. It only exists after a
// build — `rsbuild dev` renders in the dev server and runs `src/lunora.ts` — so
// this file is only bundled by `lunora deploy`.
// `@ts-ignore`, not `@ts-expect-error`: whether this specifier resolves depends on
// whether a build has run. Before the first build it does not (TS2307); after one
// it does, and `@ts-expect-error` then reports itself as unused (TS2578).
// @ts-ignore -- generated by `rsbuild build`
import start from "../dist/server/index.js";

import { lunora } from "./app";

/**
 * Single-worker entry for deploy. `.buildFrameworkWorker(...)` folds the Start
 * handler in as the framework host: the reserved `/_lunora/*` endpoints route
 * into Lunora and everything else — pages, server functions, SSR — goes to
 * TanStack Start. Static assets (`dist/client`) are served ahead of both.
 * `lunora deploy` bundles this file in place of `wrangler.jsonc` `main`.
 *
 * Only the request is forwarded: Start's second `fetch` parameter is its own
 * request options, not the Worker `env` a host handler would be handed.
 */
const app = lunora.buildFrameworkWorker((request: Request) => start.fetch(request));

export const ShardDO = app.ShardDO;
// Tracks which shards hold `.shardBy()` rows, for cross-shard export / CDC sync.
export { ShardRegistryDO } from "lunorash/do";
export default app;
