// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import {
    action as actionBase,
    internalAction as internalActionBase,
    internalMutation as internalMutationBase,
    internalQuery as internalQueryBase,
    mutation as mutationBase,
    query as queryBase,
    v as vBase,
} from "@cirrus/server";
import type {
    ActionCtx as ActionCtxBase,
    ArgsValidator,
    ColumnValidator,
    DatabaseReader,
    DatabaseWriter,
    InferArgs,
    MutationCtx as MutationCtxBase,
    QueryCtx as QueryCtxBase,
    RegisteredAction,
    RegisteredMutation,
    RegisteredQuery,
} from "@cirrus/server";

import type { DatabaseReaderFacade, DatabaseWriterFacade, Id as IdOfTable, OrmReader, OrmWriter, TableName } from "./dataModel.js";

export type { DataModel, Doc, Id, TableName } from "./dataModel.js";

/**
 * Project-typed contexts. The base contexts from `@cirrus/server` are
 * untyped against the schema; here `db` is widened to the generated per-table
 * facade (`ctx.db.<table>.findMany(...)`) while keeping the legacy structural
 * `db.get`/`db.query` surface for back-compat.
 */
export interface QueryCtx extends Omit<QueryCtxBase, "db"> {
    readonly db: DatabaseReader & DatabaseReaderFacade;
    readonly orm: OrmReader;
}

export interface MutationCtx extends Omit<MutationCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

export interface ActionCtx extends Omit<ActionCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

/** `query()` bound to this project's typed {@link QueryCtx}. */
export const query = queryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** `mutation()` bound to this project's typed {@link MutationCtx}. */
export const mutation = mutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** `action()` bound to this project's typed {@link ActionCtx}. */
export const action = actionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/** `internalQuery()` bound to this project's typed {@link QueryCtx} — never exposed on `api`. */
export const internalQuery = internalQueryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** `internalMutation()` bound to this project's typed {@link MutationCtx} — never exposed on `api`. */
export const internalMutation = internalMutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** `internalAction()` bound to this project's typed {@link ActionCtx} — never exposed on `api`. */
export const internalAction = internalActionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/**
 * The validator builder `v`, with `v.id(...)` constrained to THIS schema's
 * table names — so the argument autocompletes and returns a precise
 * `Id<"table">`. Identical to `@cirrus/server`'s `v` at runtime; the only
 * difference is the tightened `id` type.
 *
 * Import `v` from here (`./_generated/server`) in your queries/mutations/actions
 * to get table-name autocomplete. `cirrus/schema.ts` can't use it — it is the
 * file that defines the table names, so they aren't known yet there; pass the
 * names as string literals and the generated `Id<"table">` types still catch a
 * typo wherever the id is used.
 */
export const v = vBase as unknown as Omit<typeof vBase, "id"> & {
    id: <T extends TableName>(table: T) => ColumnValidator<IdOfTable<T>, IdOfTable<T>>;
};
