// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

/**
 * One vector index declared in `schema.ts` — an inline `.vectorize()` column
 * or a standalone `defineVectorIndex()`. `field` is the source column (absent
 * for a `select`-derived Shape B index); `metadata` lists the row fields
 * mirrored into Vectorize for filtering.
 */
export interface CirrusVectorIndex {
    dimensions?: number;
    field?: string;
    metadata?: ReadonlyArray<string>;
    metric?: "cosine" | "dot-product" | "euclidean";
    name: string;
    table: string;
}

/**
 * Static registry of every vector index in the schema, sorted by name.
 * Vectorize cannot enumerate indexes at runtime, so the worker passes this to
 * `createWorker({ vectorIntrospector })` to back the studio's vector browser.
 */
export const CIRRUS_VECTOR_INDEXES: ReadonlyArray<CirrusVectorIndex> = [
    { name: "posts_search", table: "posts", field: "body", metric: "cosine", metadata: ["title"] },
];
