/**
 * The Studio assistant's knowledge digest — GENERATED, do not edit.
 *
 * Written by `scripts/build-ai-knowledge.js` from `apps/docs/src/content/docs`,
 * so it cannot drift from the documentation: `pnpm run lint:generated` re-runs the
 * generator and fails if this file would change. Read `shared/ai-knowledge.ts` for
 * what the assistant does with it, and the generator's docblock for why the digest
 * is an index rather than the prose.
 */

/** One documentation page, as much of it as fits a tool result. */
export const DOC_TOPICS: ReadonlyArray<{
    /** The page's `##` headings, in document order. Largely API names in these docs. */
    readonly headings: ReadonlyArray<string>;
    /** Slug under `/docs/`, e.g. `concepts/indexes`. */
    readonly id: string;
    /** The page's frontmatter `description` — one reviewed sentence. */
    readonly summary: string;
    readonly title: string;
}> = [
    {
        headings: [
            "Vocabulary",
            "The mental model",
            "The components",
            "Request lifecycle",
            "The data tiers",
            "Compute tiers",
            "The consistency model",
            "The real-time engine",
        ],
        id: "architecture",
        summary: "The full picture — topology, request lifecycle, the data tiers, the consistency model, and the design decisions behind them.",
        title: "Architecture",
    },
    {
        headings: [
            "How telemetry reaches the cloud",
            "Traces",
            "Issues",
            "Logs",
            "Metrics",
            "Scoped ingest keys",
            "Bring your own OpenTelemetry",
            "Retention & scale",
        ],
        id: "cloud/monitoring",
        summary: "The Lunora cloud is a managed OpenTelemetry backend + control plane — deploy to it and your traces, logs, metrics, and AI generations flow i",
        title: "Monitoring",
    },
    {
        headings: ["When to use an action vs a mutation", "ActionCtx", "Calling queries and mutations from an action", "Scheduling follow-up work"],
        id: "concepts/actions",
        summary: "Non-deterministic functions for external APIs and side effects — the action builder and its ActionCtx.",
        title: "Actions",
    },
    {
        headings: [
            "Keep your session authority",
            "Declare ownership once",
            "Call Lunora from your own Worker",
            "Dev proxy: two silent failures",
            "Run both engines during the migration",
            "Test it without a worker",
            "When something is stuck",
        ],
        id: "concepts/adopt-in-an-existing-app",
        summary: "Add Lunora to a working product that already has its own auth, Worker, and data layer — without rewriting either.",
        title: "Adopt in an existing app",
    },
    {
        headings: ["Static lints", "Runtime lints", "Running advisors"],
        id: "concepts/advisors",
        summary: "Splinter-style lints that catch schema, performance, and security problems — many before you deploy.",
        title: "Advisors",
    },
    {
        headings: ["Agent skills", "Agent mode", "The docs server", "The local server", "The MCP server", "Keeping generated types honest"],
        id: "concepts/ai-tooling",
        summary: "Teach Claude Code, Cursor, and Copilot how to use Lunora — agent skills, agent-aware dev mode, the docs server, and the MCP server.",
        title: "AI coding agents",
    },
    {
        headings: [
            "What lands in your project",
            "Wire it up",
            "The cards",
            "Enabling the optional flows",
            "Password rules",
            "Username availability",
            "Being an OAuth provider",
            "Avatar and logo uploads",
        ],
        id: "concepts/auth-ui",
        summary: "Copy-in sign-in, settings, and organization screens for React, Vue, Svelte, Solid, and Angular — the code lands in your project and you own ",
        title: "Auth UI",
    },
    {
        headings: [
            "ctx.auth inside functions",
            "@lunora/auth on the server",
            "Routing /api/auth/*",
            "The client side",
            "Feeding row-level security",
            "See also",
        ],
        id: "concepts/authentication",
        summary: "How ctx.auth threads the signed-in user through queries, mutations, and actions — and feeds row-level security.",
        title: "Authentication",
    },
    {
        headings: ["Point-in-time recovery", "Snapshot backups", "Export and import", "Streaming data out continuously", "Practising a restore"],
        id: "concepts/backups",
        summary: "Snapshot a deployment, recover a shard to any moment in the last 30 days, and move data in and out as NDJSON.",
        title: "Backups, export & import",
    },
    {
        headings: ["Schema first", "Reads", "Writes", "Inputs and safety", "Scaling", "Lean on Advisors"],
        id: "concepts/best-practices",
        summary: "The opinionated idioms that keep a Lunora app fast, safe, and reactive.",
        title: "Best practices",
    },
    {
        headings: [
            "Enabling Workers Cache",
            "Declarative cache headers on httpRoute",
            "Programmatic cache purging",
            "Why only actions?",
            "Memoizing an expensive action result",
            "Scaffolding cache-aware routes",
            "Best practices",
        ],
        id: "concepts/caching",
        summary: "Edge caching with Cloudflare Workers Cache — declarative headers on HTTP routes and programmatic cache purging from actions.",
        title: "Caching",
    },
    {
        headings: ["Declaring it", "What _commitSeq guarantees", "Refreshed on every write", "Three things it is not", "When to reach for it"],
        id: "concepts/commit-ordering",
        summary: "Declare .commitOrdered() so every row carries _commitSeq — a per-shard sequence that orders commits, and the cursor a changefeed can page on",
        title: "Commit ordering",
    },
    {
        headings: ["Defining one", "Installing one", "What the namespace guarantees", "What a component does NOT get", "Migrations", "See also"],
        id: "concepts/components",
        summary: "Package backend features — tables, functions, and context — as an installable unit that cannot collide with the app that installs it.",
        title: "Components",
    },
    {
        headings: ["Constraint kinds", "Unique", "Non-null", "Foreign-key integrity", "Error codes"],
        id: "concepts/constraints",
        summary: "Unique, non-null and foreign-key integrity declared on the schema and enforced at write time.",
        title: "Constraints",
    },
    {
        headings: ["What it pins", "Set it once: changing it strands data", "Runbook: moving an app to a new jurisdiction"],
        id: "concepts/data-residency",
        summary: "Pin Durable Objects to a Cloudflare jurisdiction with .jurisdiction(), and the export→import runbook for moving regions.",
        title: "Data residency",
    },
    {
        headings: [
            "The type table",
            "Numbers, bigints, and dates",
            "Optional versus null",
            "Values that JSON cannot carry",
            "Size limits",
            "Types outside the schema",
        ],
        id: "concepts/data-types",
        summary: "The value types a Lunora document can hold, how each is stored, and which ones need the wire codec to survive JSON.",
        title: "Data types",
    },
    {
        headings: [
            "Start with lunora doctor",
            "Catch it before it runs",
            "The error overlay",
            "Structured logging with ctx.log",
            "The Studio",
            "Find the slow or failing function",
            "Watch production",
            "Debugging authentication",
        ],
        id: "concepts/debugging",
        summary: "The tools to reach for when something is broken — doctor, the error overlay, ctx.log, the Studio, insights, and live logs.",
        title: "Debugging",
    },
    {
        headings: [
            "How ids are minted",
            "Typing a reference with v.id",
            "Reading and following ids",
            "Validating an id that came from outside",
            "Ids in exports and imports",
        ],
        id: "concepts/document-ids",
        summary: "Every row carries an _id and a _creationTime — how they are minted, how v.id types a reference, and what an id does and does not guarantee.",
        title: "Document IDs",
    },
    {
        headings: ["Locally: .dev.vars", "In production: secrets and vars", "Accessing env inside your app", "The rule: never commit secrets"],
        id: "concepts/environment-variables",
        summary: "Configure secrets and vars — .dev.vars locally, wrangler secrets in production, env bindings inside functions.",
        title: "Environment variables",
    },
    {
        headings: [
            "Multiple environments",
            "Linking a checkout to a deployment",
            "Preview deployments",
            "Moving traffic between versions",
            "Build once, deploy many",
            "Custom domains",
            "Trying a deploy without an account",
            "Who changed what",
        ],
        id: "concepts/environments",
        summary: "Running staging next to production, shipping a preview per pull request, and rolling traffic back when something goes wrong.",
        title: "Environments & releases",
    },
    {
        headings: [
            "Throwing from a handler",
            "Expected vs. unexpected",
            "Reading error state on the client",
            "Optimistic updates roll back on rejection",
            "See also",
        ],
        id: "concepts/error-handling",
        summary: "Throwing inside handlers, how errors travel to the client, and reading error state without losing optimistic safety.",
        title: "Error handling",
    },
    {
        headings: ["Which contexts expose what", "Uploading", "Serving files", "Named buckets", "Deleting", "See also"],
        id: "concepts/file-storage",
        summary: "Typed R2 buckets exposed as ctx.storage — uploading, serving via signed URLs, and deleting files from your functions.",
        title: "File storage",
    },
    {
        headings: ["Where the work happens", "Choosing between them", "When a bare filter is fine", "How the advisors catch this", "Composing"],
        id: "concepts/filtering",
        summary: ".filter() is a JavaScript predicate applied after rows are loaded — when to use it, and when to reach for an index instead.",
        title: "Filtering",
    },
    {
        headings: ["The three context types", "Surfaces on every ctx", "ctx field matrix", "Add-on surfaces (codegen-wired)"],
        id: "concepts/function-context",
        summary: "The ctx object passed to every query, mutation, and action — and what each kind is allowed to do with it.",
        title: "Function context",
    },
    {
        headings: [
            "api.ts: function references",
            "server.ts: typed helpers",
            "dataModel.ts: Id and Doc",
            "Importing the generated code",
            "lunora/* vs @lunora/* imports",
            "Linting and formatting",
            "Regenerating",
        ],
        id: "concepts/generated-code",
        summary: "What @lunora/codegen emits from your schema.ts, and how api / Id / Doc keep server and client in sync.",
        title: "Generated code",
    },
    {
        headings: [
            "Declaring a point column and a geo index",
            '"Places near me": near(point, radiusMeters)',
            "Bounding box: within(box)",
            "Single-shard scope",
            "How the Advisors catch geo mistakes",
        ],
        id: "concepts/geospatial",
        summary: 'Store lat/lng points with v.geoPoint, index them with .geoIndex, and answer "places near me" and bounding-box reads with withGeoIndex.',
        title: "Geospatial",
    },
    {
        headings: ["httpAction", "HttpActionCtx", "Typed routes with httpRoute", "How routes mount in the worker"],
        id: "concepts/http-endpoints",
        summary: "Public HTTP routes with httpAction and the Hono-based httpRouter.",
        title: "HTTP endpoints",
    },
    {
        headings: [
            "Declaring an index",
            "Querying with withIndex",
            "Why every filtered read should hit an index",
            "How the Advisors catch unindexed reads",
            "Aggregate indexes",
        ],
        id: "concepts/indexes",
        summary: "Declare B-tree indexes on tables and query them with withIndex — every filtered read should hit one.",
        title: "Indexes",
    },
    {
        headings: ["Calling internal functions", "Internal functions and scheduling"],
        id: "concepts/internal-functions",
        summary: "internalQuery / internalMutation / internalAction — server-only functions never exposed to the client.",
        title: "Internal functions",
    },
    {
        headings: [
            "Why the DO topology fits",
            "Shapes — partial replication",
            "The poke diff protocol",
            "Custom mutators — optimistic, server-authoritative",
            "The client store",
            "Cross-shard joins — the one limit",
        ],
        id: "concepts/local-first",
        summary: "Shapes, the poke diff protocol, and custom mutators — the Zero-class sync engine.",
        title: "Local-first sync",
    },
    {
        headings: ["Strategies", "Roles and bypass", "What's masked, what isn't", "Tooling", "See also"],
        id: "concepts/masking",
        summary: "Column-level redaction on the read path — the companion to row-level security.",
        title: "Data masking",
    },
    {
        headings: [
            "The lifetime",
            "Rebuilding: onShardInit",
            "What .memory() buys, and what it does not",
            "Restrictions",
            "Choosing between .memory() and .ttl()",
        ],
        id: "concepts/memory-tables",
        summary: "Declare .memory() for state the shard rebuilds rather than remembers — presence, cursors, live counters — and onShardInit to bring it back a",
        title: "Memory tables",
    },
    {
        headings: ["Attaching middleware", "Augmenting ctx", "Composing concerns"],
        id: "concepts/middleware",
        summary: "Compose cross-cutting concerns — auth checks, rate limiting, logging — and augment ctx for downstream handlers.",
        title: "Middleware",
    },
    {
        headings: ["Schema migrations (global tables)", "Data migrations (sharded tables)", "Inspecting run-state in the Studio", "Resetting local state"],
        id: "concepts/migrations",
        summary: "Schema-change SQL for global tables and online, resumable data migrations.",
        title: "Migrations",
    },
    {
        headings: [
            "Running as one node in a dev graph",
            "Deploying from external IaC",
            "Consuming the generated API from a sibling package",
            "Calling the backend from a sibling Worker",
        ],
        id: "concepts/monorepos-and-iac",
        summary: "Running the Lunora worker as one node in a larger dev graph, deploying it from Terraform/Pulumi/Alchemy, and consuming its generated API fro",
        title: "Monorepos and external IaC",
    },
    {
        headings: ["The output is pinned to your CLI version", "Wiring it into your project", "What you get, and what you don't", "Conformance"],
        id: "concepts/non-js-sdks",
        summary: "Generate a typed, self-contained Lunora client for Python, Go, Ruby, Rust, Swift, Java, Kotlin or Dart/Flutter — vendored into your project ",
        title: "Non-JS SDKs",
    },
    {
        headings: [
            "Configure defineNotify",
            "VAPID / FCM config via .dev.vars",
            "Register a browser push subscription",
            "Send from an action",
            "Queue-backed fan-out",
        ],
        id: "concepts/notifications",
        summary: "Configure defineNotify in lunora/notify.ts for Web Push + FCM, register browser subscriptions, and send via ctx.notify / ctx.push from an ac",
        title: "Push notifications",
    },
    {
        headings: [
            "Sinks",
            "Structured logging with ctx.log",
            "Tracing sub-operations with ctx.trace",
            "Trace sampling",
            "Application metrics with ctx.metrics",
            "Container telemetry",
            "The wire contract",
            "Privacy",
        ],
        id: "concepts/observability",
        summary: "Ship Lunora's logs, traces, and metrics to any OTLP collector — the otlpSink worker option, ctx.log/ctx.trace/ctx.metrics, the zero-config c",
        title: "Observability",
    },
    {
        headings: [
            "Mutations are serialized, not retried",
            "Where conflicts still happen",
            "Handling a conflict on the client",
            "Diagnosing a persistent conflict",
            "Atomicity across shards",
            ".global() tables",
        ],
        id: "concepts/occ",
        summary: "Why mutations in one shard are serialized rather than retried, where optimistic-concurrency conflicts still arise, and what atomicity means ",
        title: "OCC & atomicity",
    },
    {
        headings: [
            "Enable persistent reads and writes",
            "What gets persisted",
            "Surviving a breaking deploy",
            "Multiple tabs",
            "Sync status",
            "Connection status UI",
            "Boot with no network (the app shell)",
            "The reconciliation model",
        ],
        id: "concepts/offline-first",
        summary: "Persist reads and writes to disk so the app boots, renders, and accepts edits with no network.",
        title: "Offline-first",
    },
    {
        headings: ["PaginationOptions", "PaginationResult", "Paging through a query", "Load more / infinite lists on the client"],
        id: "concepts/pagination",
        summary: "Keyset pagination with .paginate(options) — page through a query and build an infinite list on the client.",
        title: "Pagination",
    },
    {
        headings: ["ctx.db", "ctx.auth", "ctx.scheduler"],
        id: "concepts/queries-mutations",
        summary: "query / mutation / action — what each is for and how ctx is shaped.",
        title: "Queries & mutations",
    },
    {
        headings: [
            "How this differs from a trigger",
            "The convergence contract",
            "What the handler receives",
            "Execution and identity",
            "Reads that should not wake you",
            "Watching them work",
        ],
        id: "concepts/reactors",
        summary: "Declare onQueryChange to run server logic when a query's result changes — the actor pattern, with no client on the other end and nothing pol",
        title: "Reactors (server-side reactivity)",
    },
    {
        headings: ["Where a shard is created", "Replica reads", "Sockets near the client"],
        id: "concepts/read-replicas",
        summary: "Serve one-shot queries from a copy of the shard in the caller's region, pin where a shard is created, and terminate sockets near the client.",
        title: "Read replicas & placement",
    },
    {
        headings: ["Hibernation", "Delta routing", "Reconnect", "Durable streams", "Why no MQTT / Pub/Sub"],
        id: "concepts/realtime",
        summary: "How subscriptions, deltas, and hibernation fit together.",
        title: "Real-time",
    },
    {
        headings: ["Using items", "The manifest", "Validation", "Building the catalog", "Distributing"],
        id: "concepts/registry-items",
        summary: "Package a reusable capability — schema, functions, bindings and env vars — as a registry item others install with one command.",
        title: "Authoring registry items",
    },
    {
        headings: ["The two descriptors", "Index your foreign keys", "Querying across a relation"],
        id: "concepts/relations",
        summary: "Modeling many-to-one and one-to-many relationships with the one / many relation descriptors, foreign-key columns and indexed reads.",
        title: "Relations",
    },
    {
        headings: ["Default-closed", "URLs and methods", "Arguments", "Choosing a shard", "Authentication", "Rate limiting", "OpenAPI", "Observability"],
        id: "concepts/rest-api",
        summary: "Publish a query, mutation, or action as a plain REST endpoint with .expose({ rest: true }) — default-closed, routed through the procedure so",
        title: "Public REST API",
    },
    {
        headings: ["Policies", "Permissions and roles", "Relation predicates", "What's covered, what isn't", "Testing policies", "See also"],
        id: "concepts/rls",
        summary: "Server-side authorization that decides which rows a procedure can read or write.",
        title: "Row-level security",
    },
    {
        headings: ["Node compatibility", "Where the constraints bite", "Bundling", "The worker entry", "Build once, deploy many"],
        id: "concepts/runtime",
        summary: "Everything runs on the Workers runtime — what that means for Node APIs, dependencies, and the 10 MB bundle you have to fit into.",
        title: "Runtime & bundling",
    },
    {
        headings: ["Deferring a function", "Recurring jobs (Cron Triggers)", "How dispatch works", "See also"],
        id: "concepts/scheduling",
        summary: "Defer follow-up work with ctx.scheduler.runAfter / runAt, and run recurring jobs via Cron Triggers.",
        title: "Scheduling",
    },
    {
        headings: ["Validators", "Tier modifiers", "Indexes"],
        id: "concepts/schema",
        summary: "Declarative tables, validators, indexes and sharding.",
        title: "Schema",
    },
    {
        headings: [
            "Declaring a search index",
            "Language",
            "Running a search query",
            "Matching rules",
            "Filter fields",
            "Relevance ordering, .take(n) and pagination",
            "Limits",
            "Backfill and staged",
        ],
        id: "concepts/search",
        summary: "Declare a search index on a table and run relevance-ordered full-text queries.",
        title: "Full-text search",
    },
    {
        headings: [
            "The HTTP edge",
            "Auth, cookies, and secrets",
            "Protecting public procedures",
            "Securing sharded access",
            "Advisor catalog",
            "Config-time validation",
        ],
        id: "concepts/security",
        summary: "Lunora's secure-by-default posture — the protections you get for free, how to opt out, and the advisor lints that catch the gaps.",
        title: "Security",
    },
    {
        headings: ["From an SSR loader", "From a script", "From the terminal", "From Python", "From any language, over HTTP", "Writing a new SDK"],
        id: "concepts/server-clients",
        summary: "Calling a Lunora deployment without a live subscription — from SSR loaders, scripts, other languages, or plain HTTP.",
        title: "Server-side & non-reactive clients",
    },
    {
        headings: ["When to shard", "What stays in the root DO", "Going global", "Cross-shard reads", "Securing shard access"],
        id: "concepts/sharding",
        summary: "Default __root__ DO, opt-in .shardBy(), and .global() escape hatch.",
        title: "Sharding",
    },
    {
        headings: ["The one caveat that matters", "The read surface", "_scheduled_functions", "_storage"],
        id: "concepts/system-tables",
        summary: "Read pending scheduled jobs and stored file metadata through ctx.db.system — a read-only, eventually consistent view outside the mutation sn",
        title: "System tables",
    },
    {
        headings: ["The in-memory harness", "Asserting reactive results", "Mail-catcher helpers (E2E)", "Running in CI"],
        id: "concepts/testing",
        summary: "Unit-test queries, mutations, and actions in memory with lunoraTest — no worker, no network.",
        title: "Testing",
    },
    {
        headings: ["Declaring a TTL", "Sweep semantics: coarse, batched, bounded", "Interaction with soft delete", "How the Advisors catch TTL mistakes"],
        id: "concepts/ttl",
        summary: "Declare a table-level .ttl() so a DO alarm sweep auto-deletes expired rows — sessions, OTPs, and other ephemeral data.",
        title: "TTL & auto-expiry",
    },
    {
        headings: [
            "Where types come from",
            "Do not restate what is inferred",
            "Reach for Doc and Id",
            "Pin the client contract with .output()",
            "Optional versus null in types",
            "Bringing your own validators",
            "Project configuration",
            "Keeping types honest in CI",
        ],
        id: "concepts/typescript",
        summary: "Getting the most out of Lunora's end-to-end types — where types come from, what to annotate, and what to let inference do.",
        title: "TypeScript",
    },
    {
        headings: [
            "Job 1: column types in defineTable",
            "Job 2: argument and return validation",
            "Return-type inference to the client",
            "Common validators",
            "ValidationError",
        ],
        id: "concepts/validation",
        summary: "The v.* validators that type your columns and parse query / mutation / action inputs and outputs end to end.",
        title: "Validation",
    },
    {
        headings: ["Declaring an index", "Automatic write sync", "ctx.vectors", "RAG with @lunora/ai", "Binding & config wiring"],
        id: "concepts/vector-search",
        summary: "Typed Vectorize indexes on ctx.vectors — automatic write sync, similarity search, and RAG with embeddings.",
        title: "Vector search",
    },
    {
        headings: ["The specification", "Conformance fixtures", "SDKs built on it"],
        id: "concepts/wire-protocol",
        summary: "The language-independent Lunora client↔server wire protocol and the golden fixtures every SDK is tested against.",
        title: "Wire protocol",
    },
    {
        headings: ["wrangler.jsonc", "Secrets", "Containers", "Deploy", "Worker size", "Streaming logs", "Platform configuration", "Non-goals"],
        id: "deployment",
        summary: "Wrangler bindings, secrets, and the deploy flow.",
        title: "Deployment",
    },
    {
        headings: [
            "Request errors",
            "Data errors",
            "Authorization and privacy errors",
            "Dispatch errors",
            "Infrastructure errors",
            "Auth and email errors",
            "Internal errors",
            "Build-time errors",
        ],
        id: "errors",
        summary: "Every well-known Lunora error code — its HTTP status, what it means, and what to do about it.",
        title: "Errors & warnings reference",
    },
    {
        headings: ["Install", "Provide the client", "Live queries", "Mutations", "Connection status", "Reactive loaders"],
        id: "frameworks/angular",
        summary: "Use Lunora with Angular — provideLunora in your app config, signal-based liveQuery, imperative mutate, and a connectionStatus signal.",
        title: "Angular",
    },
    {
        headings: ["Install", "Exports", "The integration", "Single-worker composition with withLunora", "Reactive-loader server helpers", "Deploy"],
        id: "frameworks/astro",
        summary: "Compose Astro's @astrojs/cloudflare worker with Lunora realtime, plus reactive-loader server helpers for .astro frontmatter.",
        title: "Astro",
    },
    {
        headings: [
            "One worker, two dispatch flows",
            "Mount Lunora inside your framework",
            "The per-framework matrix",
            "Client adapters",
            "Scaffolding",
            "Vite composition",
        ],
        id: "frameworks/bring-your-framework",
        summary: "Compose any meta-framework's SSR with Lunora realtime in one Cloudflare Worker.",
        title: "Bring your framework",
    },
    {
        headings: [
            "One worker, two dispatch flows",
            "Class A: Lunora owns the worker entry",
            "Class B: the framework owns the CF adapter",
            "Class C: SPA / SSR-less",
            "Wrangler reconciliation",
        ],
        id: "frameworks/deploy",
        summary: "One worker, one deploy — how a composed Lunora + meta-framework app ships to Cloudflare.",
        title: "Deploy your framework",
    },
    {
        headings: [
            "Why two workers",
            "Wiring them together",
            "Client and server entry points",
            "Loading data in a Server Component",
            "Providing the client",
            "Developing",
            "Deploying",
        ],
        id: "frameworks/nextjs",
        summary: "Run Lunora alongside Next.js on Cloudflare with the two-worker split — RSC loaders that hydrate into live subscriptions.",
        title: "Next.js",
    },
    {
        headings: ["Install", "Setup", "How it works", "Reactive loaders", "Feature flags", "Verify before deploy", "Alternative: two-worker split"],
        id: "frameworks/nuxt",
        summary: "Run Lunora and Nuxt as one Cloudflare Worker — the @lunora/nuxt module mounts /_lunora/** into Nitro, plus reactive-loader server helpers.",
        title: "Nuxt",
    },
    {
        headings: [
            "Scaffold a new app",
            "Install",
            "Create the client",
            "Provide it",
            "Live queries and mutations",
            "Authentication (better-auth + Expo)",
            "How auth reaches the live socket",
            "API",
        ],
        id: "frameworks/react-native",
        summary: "Use Lunora in a React Native / Expo app — the same live hooks, plus an AsyncStorage-backed client and a better-auth Expo bridge.",
        title: "React Native / Expo",
    },
    {
        headings: ["Install", "Provide the client", "Live queries", "Mutations", "Auth", "Reactive loaders", "One worker, one deploy"],
        id: "frameworks/react",
        summary: "Use Lunora with React — a provider, live useQuery/useMutation hooks, and the SSR-seed → live reactive-loader handoff.",
        title: "React",
    },
    {
        headings: [
            "The problem with static loaders",
            "The handoff",
            "Why there's no flash",
            "Identity continuity (SSR → client)",
            "Sharding carries through",
            "Status",
        ],
        id: "frameworks/reactive-loaders",
        summary: "Your loaders are live — SSR data that hydrates into a real-time subscription with no flash.",
        title: "Reactive loaders",
    },
    {
        headings: ["Install", "Solid 1.x and Solid 2.0", "Provide the client", "Live queries", "Mutations", "Reactive loaders"],
        id: "frameworks/solid",
        summary: "Use Lunora with SolidJS — a provider, live createQuery/createMutation primitives, and the SSR-seed → live reactive-loader handoff.",
        title: "Solid",
    },
    {
        headings: ["Install", "Provide the client", "Live queries", "Mutations", "Reactive loaders", "One worker, one deploy"],
        id: "frameworks/svelte",
        summary: "Use Lunora with Svelte 5 / SvelteKit — context-provided client, live query/mutation stores, and the SSR-seed → live reactive-loader handoff.",
        title: "Svelte",
    },
    {
        headings: [
            "What you're proving",
            "1. Scaffold",
            "2. Dev",
            "3. Prove SSR preload (curl the raw HTML)",
            "4. Prove the live subscription attaches",
            "5. Prove live update (two tabs)",
            "Identity check (optional, with auth)",
            'What "pass" looks like',
        ],
        id: "frameworks/verify-live-loaders",
        summary: "How to actually prove live loaders work — scaffold, SSR-curl the preloaded value, two-tab live update.",
        title: "Manual end-to-end verification",
    },
    {
        headings: ["Install", "Provide the client", "Live queries", "Mutations", "Reactive loaders", "Worker composition"],
        id: "frameworks/vue",
        summary: "Use Lunora with Vue 3 — a client plugin, live useQuery/useMutation composables, and the SSR-seed → live reactive-loader handoff.",
        title: "Vue",
    },
    {
        headings: ["Requirements"],
        id: "getting-started",
        summary: "Scaffold a Lunora app and run the dev loop in under a minute.",
        title: "Getting started",
    },
    {
        headings: ["Durable Objects", "Statement limits (Durable Objects **and** D1)", "D1", "R2", "Workers", "Queues", "Pipelines", "Workers AI + Vectorize"],
        id: "limits",
        summary: "Cloudflare ceilings you should keep in your head.",
        title: "Limits",
    },
    {
        headings: [
            "Two translations, not one",
            "Schema: transposing the relation graph",
            "Procedures: the shape deltas",
            "Writes: .returning() does not survive",
            "Components decompose by hand",
        ],
        id: "migrating/from-a-convex-toolkit",
        summary: "The second translation step a Drizzle-style schema DSL and a tRPC-style procedure builder add on top of the raw Convex mapping.",
        title: "Migrating from a Convex toolkit",
    },
    {
        headings: ["Bump strategy", "Breaking changes already landed", "Recommended (non-breaking) follow-ups", "See also"],
        id: "migrating/from-alpha",
        summary: "How a 1.0.0-alpha.* app moves to stable — dependency bumps plus every breaking change already landed on the road to 1.0.",
        title: "Upgrading from alpha to 1.0",
    },
    {
        headings: ["At a glance", "Schema", "Queries, mutations, actions", "React", "Auth", "Scheduler", "File storage", "Subscriptions"],
        id: "migrating/from-convex",
        summary: "Side-by-side mapping — schema, queries, mutations, actions, React hooks.",
        title: "Migrating from Convex",
    },
    {
        headings: [
            "At a glance",
            "Schema",
            "Reads: onSnapshot → useQuery",
            "Writes: setDoc → mutation",
            "Cloud Functions → actions",
            "Auth",
            "File storage",
            "Scheduled work",
        ],
        id: "migrating/from-firebase",
        summary: "Side-by-side mapping — Firestore, Cloud Functions, Auth, Storage, and real-time listeners.",
        title: "Migrating from Firebase",
    },
    {
        headings: [
            "At a glance",
            "Schema",
            "Reads: supabase.from(...).select() → useQuery",
            "Writes: .insert() → mutation",
            "Row-level security",
            "Edge Functions → actions",
            "Auth",
            "File storage",
        ],
        id: "migrating/from-supabase",
        summary: "Side-by-side mapping — Postgres tables, RLS, Edge Functions, Auth, Storage, and Realtime.",
        title: "Migrating from Supabase",
    },
    {
        headings: [
            "No arbitrary external SQL or ad-hoc cross-dataset joins",
            "RPC-first, not REST-first",
            "Cross-shard writes are eventual, not atomic",
            "No data warehouse hosting in the framework",
            "No managed control plane as a hard dependency",
            "Also deliberately absent",
            "See also",
        ],
        id: "non-goals",
        summary: "The things Lunora deliberately does not do — each with the reason it's a boundary and the escape hatch when you need past it.",
        title: "Design boundaries",
    },
    {
        headings: ["Why Lunora", "Own it, or let us run it", "How Lunora compares", "Where it's rough", "What ships in v1.0.0-alpha.1", "Start building"],
        id: "overview",
        summary: "The Convex-style real-time backend that runs on your own Cloudflare account — typed end to end, live by default, ~$0 at idle.",
        title: "Overview",
    },
    {
        headings: [
            "Bindings and wrangler config",
            "Secrets",
            "LUNORA_ADMIN_TOKEN and the admin plane",
            "Rate limiting and abuse",
            "Auth and row-level security",
            "Migrations",
            "Observability",
            "Health and readiness endpoint",
        ],
        id: "production-checklist",
        summary: "Everything to verify before a Lunora app takes real traffic — bindings, secrets, admin tokens, rate limits, RLS, migrations, observability.",
        title: "Production checklist",
    },
    {
        headings: ["Pick a starting point", "Adding Lunora to an app you already have", "What you get either way", "Next steps"],
        id: "quickstarts",
        summary: "Every starting point Lunora scaffolds — pick your framework, run one command, and get a live backend wired to it.",
        title: "Quickstarts",
    },
    {
        headings: [
            "1. Scaffold",
            "2. Model the data",
            "3. Generate the migration",
            "4. Write the query",
            "5. Write the mutation",
            "6. Wire the React app",
            "7. Run the dev loop",
            "8. Deploy",
        ],
        id: "tutorial/realtime-chat",
        summary: "End-to-end Lunora walkthrough — schema, query, mutation, subscription, React, sharding.",
        title: "Build a real-time chat app in 15 minutes",
    },
    {
        headings: [
            "Know when to act",
            "Step 1: shard the messages",
            "Step 2: put identities in a global table",
            "Step 3: keep fan-out off the hot path",
            "Step 4: lock down shard access",
            "Step 5: migrate the data you already have",
            "Checking your work",
            "What you learned",
        ],
        id: "tutorial/scaling",
        summary: "Take the chat app from one Durable Object to many — shard by channel, put identities in a global table, and keep cross-shard reads off the h",
        title: "Tutorial: scaling the chat app",
    },
    {
        headings: ["Release channels", "What SemVer means here", "Stability tiers", 'What "experimental" means', "See also"],
        id: "versioning",
        summary: "What SemVer means for Lunora packages — release channels, stability tiers, and the experimental surface.",
        title: "Versioning & stability",
    },
];
