// GENERATED by `lunora sdk generate --lang java` — do not edit.
// Run the command again to regenerate.

package lunoraapi;

import java.util.Map;

public class MessagesSendArgs {
    private String channelID;
    private Kind kind;
    private Map<String, String> tags;
    private String text;

    /**
     * Id<"channels">
     */
    public String getChannelID() { return channelID; }
    public void setChannelID(String value) { this.channelID = value; }

    public Kind getKind() { return kind; }
    public void setKind(Kind value) { this.kind = value; }

    public Map<String, String> getTags() { return tags; }
    public void setTags(Map<String, String> value) { this.tags = value; }

    public String getText() { return text; }
    public void setText(String value) { this.text = value; }
}
