// GENERATED by `lunora sdk generate --lang java` — do not edit.
// Run the command again to regenerate.

package lunoraapi;

public class MessagesListArgs {
    private String channelID;
    private Double limit;

    /**
     * Id<"channels">
     */
    public String getChannelID() { return channelID; }
    public void setChannelID(String value) { this.channelID = value; }

    public Double getLimit() { return limit; }
    public void setLimit(Double value) { this.limit = value; }
}
