/**
 * `BoxSessionDO` in real workerd (plan 458 G11): the node suite drives the
 * session with a fake state and fake sockets, so what only the runtime can
 * show is checked here — `acceptWebSocket` and the hibernation handlers, the
 * attachment surviving between events, WebCrypto Ed25519 in workerd, the
 * object reaching the control-plane D1, and a dispatch crossing the namespace
 * binding as native RPC — its progress called back into the caller while the
 * socket answers it.
 */
import type { D1CtxDbOptions } from "@lunora/d1";
import { runD1GlobalTableMigrations } from "@lunora/d1";
import type { CloudMessage } from "@lunora/hostd/protocol";
import { challengeSigningPayload, decodeCloudMessage } from "@lunora/hostd/protocol";
import { env } from "cloudflare:test";
import { beforeAll, describe, expect, it } from "vitest";

import schema from "../../lunora/schema";
import { toBase64Url } from "../../src/boxes/encoding";
import { boxSession } from "../../src/boxes/session-client";
import { buildExec, controlPlaneDatabase } from "../../src/d1-store";

const HELLO = {
    fleets: [],
    protocol: 1,
    resources: { diskFreeMb: 40_960, memMb: 3891 },
    type: "hello",
    versions: { caddy: "v2.11.6", celld: "v0.6.0", hostd: "1.0.0" },
};

/** A box key pair, generated by workerd's own WebCrypto. */
const boxKey = async () => {
    const pair = await crypto.subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]);
    const raw = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey));

    return {
        publicKey: toBase64Url(raw),
        sign: async (payload: Uint8Array) =>
            toBase64Url(new Uint8Array(await crypto.subtle.sign({ name: "Ed25519" }, pair.privateKey, Uint8Array.from(payload)))),
    };
};

/** Open a socket to the box's session object and collect what the control plane sends. */
const connect = async (boxId: string) => {
    const stub = env.BOX_SESSION.get(env.BOX_SESSION.idFromName(boxId));
    const response = await stub.fetch(`https://box-session.internal/connect?box=${boxId}`, { headers: { upgrade: "websocket" } });
    const socket = response.webSocket;

    if (!socket) {
        throw new Error(`no socket: ${String(response.status)}`);
    }

    socket.accept();

    const received: CloudMessage[] = [];
    const closed: { code?: number }[] = [];

    socket.addEventListener("message", (event) => {
        const decoded = decodeCloudMessage(event.data as string);

        if (decoded.ok) {
            received.push(decoded.message);
        }
    });
    socket.addEventListener("close", (event) => {
        closed.push({ code: event.code });
    });

    /** The next frame of `type` the control plane sends. */
    const next = async <T extends CloudMessage["type"]>(type: T): Promise<Extract<CloudMessage, { type: T }>> => {
        for (let attempt = 0; attempt < 200; attempt += 1) {
            const found = received.find((frame) => frame.type === type);

            if (found) {
                received.splice(received.indexOf(found), 1);

                return found as Extract<CloudMessage, { type: T }>;
            }

            // eslint-disable-next-line no-await-in-loop -- polling the socket's inbox
            await new Promise((resolve) => {
                setTimeout(resolve, 10);
            });
        }

        throw new Error(`no ${type} frame; got ${JSON.stringify(received)}`);
    };

    return { closed, next, socket };
};

describe("the box session object in workerd", () => {
    const database = controlPlaneDatabase(env.DB);

    beforeAll(async () => {
        await runD1GlobalTableMigrations(buildExec(env.DB), schema as unknown as D1CtxDbOptions["schema"]);
    });

    const enrolledBox = async (publicKey: string): Promise<string> =>
        (await database.insert("boxes", {
            createdAt: Date.now(),
            name: "edge",
            organizationId: "org_1",
            publicKey,
            singleTrust: false,
            slug: `b${crypto.randomUUID().replaceAll("-", "").slice(0, 10)}`,
            status: "pending",
        })) as string;

    it("authenticates a box over a hibernatable socket, records it online, and runs a job end to end", async () => {
        const key = await boxKey();
        const boxId = await enrolledBox(key.publicKey);
        const { next, socket } = await connect(boxId);

        socket.send(JSON.stringify({ ...HELLO, boxId }));

        const challenge = await next("challenge");

        socket.send(JSON.stringify({ signature: await key.sign(challengeSigningPayload(challenge.nonce, boxId)), type: "auth" }));

        await expect(next("routes")).resolves.toStrictEqual({ table: [], type: "routes" });
        await expect(database.get(boxId, "boxes")).resolves.toMatchObject({ status: "online", versions: HELLO.versions });

        const lines: string[] = [];
        const running = boxSession(env.BOX_SESSION, boxId).dispatch({ kind: "diagnose" }, { onProgress: (line) => lines.push(line) });
        const job = await next("job");

        socket.send(JSON.stringify({ jobId: job.jobId, line: "celld diagnose: ok", type: "progress" }));
        socket.send(JSON.stringify({ jobId: job.jobId, ok: true, type: "result" }));

        await expect(running).resolves.toStrictEqual({ ok: true });
        expect(lines).toStrictEqual(["celld diagnose: ok"]);

        socket.close(1000, "done");
    });

    it("refuses a box that signs with the wrong key", async () => {
        const key = await boxKey();
        const intruder = await boxKey();
        const boxId = await enrolledBox(key.publicKey);
        const { next, socket } = await connect(boxId);

        socket.send(JSON.stringify({ ...HELLO, boxId }));

        const challenge = await next("challenge");

        socket.send(JSON.stringify({ signature: await intruder.sign(challengeSigningPayload(challenge.nonce, boxId)), type: "auth" }));

        await expect(next("error")).resolves.toMatchObject({ code: "AUTH_FAILED", type: "error" });
        await expect(database.get(boxId, "boxes")).resolves.toMatchObject({ status: "pending" });
    });

    it("fails a dispatch fast when no box is connected", async () => {
        const key = await boxKey();
        const boxId = await enrolledBox(key.publicKey);

        await expect(boxSession(env.BOX_SESSION, boxId).dispatch({ kind: "diagnose" })).resolves.toMatchObject({ error: { code: "BOX_OFFLINE" }, ok: false });
    });
});
