/*
 * Dev seed for the control plane.
 *
 * A cold `pnpm run dev` comes up empty, and empty is not a usable state here:
 * `organizations:create` places every new org on a **cell**, so with no cell in
 * the fleet the first thing a developer does after signing up fails. Recovering
 * by hand meant an `INSERT INTO cells` against the local D1 file — which writes
 * a row the app never validated and skips the code path that would have caught
 * the bug that motivated this script (`POST /v1/cells` returning 500 because a
 * route could not reach an `internal` function).
 *
 * So this seeds through the **real surfaces** — better-auth for the user, the
 * operator-gated HTTP route for the cell, public RPC for the org and project.
 * That keeps the seeded state indistinguishable from state a user could create,
 * and makes the script double as a smoke test of the paths a cold start needs.
 *
 * Usage — the dev server must already be running, since everything here is an
 * HTTP call against it:
 *
 * ```bash
 * pnpm run dev            # terminal 1
 * pnpm run seed           # terminal 2
 * ```
 *
 * Re-running is safe. Every step checks for what it would create first, because
 * none of the underlying mutations dedupe: `cells:register` inserts blindly, so
 * an unconditional seed would grow a fresh cell on every run.
 */

/* eslint-disable no-console -- a terminal script: its progress report to stdout is the deliverable, not a stray debug statement. */

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

/** Where the dev server is listening. Vite falls back to 5175+ when 5174 is taken. */
const BASE_URL = process.env["LUNORA_SEED_URL"] ?? "http://localhost:5174";

/** The account the seed signs in as, and prints at the end for the developer to reuse. */
const DEV_EMAIL = process.env["LUNORA_SEED_EMAIL"] ?? "dev@lunora.local";
// eslint-disable-next-line sonarjs/no-hardcoded-passwords -- a published default for a throwaway local account, overridable via LUNORA_SEED_PASSWORD; it authenticates nothing beyond a developer's own miniflare state.
const DEV_PASSWORD = process.env["LUNORA_SEED_PASSWORD"] ?? "dev-password-1234";
const DEV_NAME = "Dev User";

const CELL_NAME = "dev-cell";
const ORG_NAME = "Acme Dev";
const ORG_SLUG = "acme-dev";
const PROJECT_NAME = "Web";
const PROJECT_SLUG = "web";

/**
 * `KEY=value` for the one key the seed needs out of `.dev.vars`. Deliberately not
 * a full dotenv parser: the file is generated by `@lunora/config`.
 */
const ADMIN_TOKEN_PATTERN = /^LUNORA_ADMIN_TOKEN=(.*)$/m;

/**
 * The `LUNORA_ADMIN_TOKEN` guarding `POST /v1/cells`. Read from the environment
 * when set, else from `.dev.vars` — the same file the dev worker loads, so the
 * seed uses whatever the running server is actually enforcing rather than a
 * second copy that can drift.
 */
const readAdminToken = async (): Promise<string> => {
    const fromEnvironment = process.env["LUNORA_ADMIN_TOKEN"];

    if (fromEnvironment !== undefined && fromEnvironment !== "") {
        return fromEnvironment;
    }

    const devVariablesPath = fileURLToPath(new URL("../.dev.vars", import.meta.url));

    let contents: string;

    try {
        contents = await readFile(devVariablesPath, "utf8");
    } catch {
        throw new Error(`no LUNORA_ADMIN_TOKEN in the environment and no .dev.vars at ${devVariablesPath} — run \`pnpm run dev\` once to generate it`);
    }

    const match = ADMIN_TOKEN_PATTERN.exec(contents);
    const value = match?.[1]?.trim().replaceAll(/^["']|["']$/gu, "");

    if (value === undefined || value === "") {
        throw new Error("`.dev.vars` has no LUNORA_ADMIN_TOKEN entry");
    }

    return value;
};

/** A Lunora RPC error surfaces as `{ error: { code, message } }` rather than a non-2xx. */
interface RpcEnvelope {
    error?: { code?: string; message?: string };
    result?: unknown;
}

/**
 * Call a Lunora function over the public RPC endpoint as the signed-in user.
 *
 * `origin` is not optional here. The runtime's `enforceOrigin` CSRF guard rejects
 * any unsafe-method request that carries a cookie but names no `Origin`/`Referer`,
 * and a bare `fetch` sends neither — so without this every seeded RPC 403s before
 * it is routed, no matter how correct the args are.
 */
const rpc = async <R>(cookie: string, functionPath: string, args: Record<string, unknown> = {}): Promise<R> => {
    const response = await fetch(`${BASE_URL}/_lunora/rpc`, {
        body: JSON.stringify({ args, functionPath }),
        headers: { "content-type": "application/json", cookie, origin: BASE_URL },
        method: "POST",
    });

    const payload: RpcEnvelope = await response.json();

    if (payload.error) {
        throw new Error(`${functionPath}: ${payload.error.message ?? "RPC failed"}${payload.error.code ? ` (${payload.error.code})` : ""}`);
    }

    if (!response.ok) {
        throw new Error(`${functionPath}: HTTP ${String(response.status)}`);
    }

    return payload.result as R;
};

/** Collect the `set-cookie` values into one request-shaped `Cookie` header. */
const cookieHeaderFrom = (response: Response): string =>
    response.headers
        .getSetCookie()
        .map((entry) => entry.split(";")[0])
        .filter((entry) => entry !== "")
        .join("; ");

/**
 * Sign the dev user in, creating the account on first run.
 *
 * Sign-up is attempted first and a failure is *not* fatal — the common case on a
 * re-run is "user already exists", which is a success for our purposes. Whether
 * the account is new or not, the session comes from the explicit sign-in below,
 * so this does not depend on better-auth's auto-sign-in-after-sign-up behaviour.
 */
const signIn = async (): Promise<string> => {
    await fetch(`${BASE_URL}/api/auth/sign-up/email`, {
        body: JSON.stringify({ email: DEV_EMAIL, name: DEV_NAME, password: DEV_PASSWORD }),
        headers: { "content-type": "application/json", origin: BASE_URL },
        method: "POST",
    });

    const response = await fetch(`${BASE_URL}/api/auth/sign-in/email`, {
        body: JSON.stringify({ email: DEV_EMAIL, password: DEV_PASSWORD }),
        headers: { "content-type": "application/json", origin: BASE_URL },
        method: "POST",
    });

    if (!response.ok) {
        throw new Error(`sign-in failed: HTTP ${String(response.status)} ${await response.text()}`);
    }

    const cookie = cookieHeaderFrom(response);

    if (cookie === "") {
        throw new Error("sign-in returned no session cookie");
    }

    return cookie;
};

/**
 * Ensure the fleet has at least one cell, returning its id.
 *
 * Registration goes through the operator route rather than `ctx.db`, so it
 * exercises the `LUNORA_ADMIN_TOKEN` boundary and the internal-function dispatch
 * that an org placement depends on.
 */
const ensureCell = async (cookie: string): Promise<string> => {
    const existing = await rpc<{ _id: string; name: string }[]>(cookie, "cells:list");
    // `.at()` rather than `[0]`, so the empty-fleet case is a type the compiler
    // makes us handle (this app disables `noUncheckedIndexedAccess`).
    const found = existing.at(0);

    if (found !== undefined) {
        console.info(`  cell        ${found.name} (exists)`);

        return found._id;
    }

    const response = await fetch(`${BASE_URL}/v1/cells`, {
        body: JSON.stringify({ cloudflareAccountId: "dev-account", dispatchNamespacePrefix: "lunora-dev", name: CELL_NAME }),
        headers: { authorization: `Bearer ${await readAdminToken()}`, "content-type": "application/json", origin: BASE_URL },
        method: "POST",
    });

    if (!response.ok) {
        throw new Error(`POST /v1/cells: HTTP ${String(response.status)} ${await response.text()}`);
    }

    const { cellId }: { cellId: string } = await response.json();

    console.info(`  cell        ${CELL_NAME} (created)`);

    return cellId;
};

/** Ensure the dev user owns an organization, returning its id. */
const ensureOrganization = async (cookie: string, cellId: string): Promise<string> => {
    const existing = await rpc<{ _id: string; slug: string } | null>(cookie, "organizations:getBySlug", { slug: ORG_SLUG });

    if (existing !== null) {
        console.info(`  org         ${ORG_SLUG} (exists)`);

        return existing._id;
    }

    const organizationId = await rpc<string>(cookie, "organizations:create", { cellId, name: ORG_NAME, plan: "pro", slug: ORG_SLUG });

    console.info(`  org         ${ORG_SLUG} (created)`);

    return organizationId;
};

/** Ensure that organization has a project, so the dashboard renders something. */
const ensureProject = async (cookie: string, organizationId: string): Promise<void> => {
    const existing = await rpc<{ page: { slug: string }[] } | { slug: string }[]>(cookie, "projects:listByOrg", { organizationId });
    const projects = Array.isArray(existing) ? existing : existing.page;

    if (projects.some((project) => project.slug === PROJECT_SLUG)) {
        console.info(`  project     ${PROJECT_SLUG} (exists)`);

        return;
    }

    await rpc<string>(cookie, "projects:create", { framework: "vite", name: PROJECT_NAME, organizationId, slug: PROJECT_SLUG });

    console.info(`  project     ${PROJECT_SLUG} (created)`);
};

const main = async (): Promise<void> => {
    console.info(`seeding ${BASE_URL}\n`);

    const cookie = await signIn();

    console.info(`  user        ${DEV_EMAIL}`);

    const cellId = await ensureCell(cookie);
    const organizationId = await ensureOrganization(cookie, cellId);

    await ensureProject(cookie, organizationId);

    console.info(`\ndone — sign in at ${BASE_URL}/login with ${DEV_EMAIL} / ${DEV_PASSWORD}`);
};

try {
    await main();
} catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);

    console.error(`\nseed failed: ${message}`);
    console.error(`\nis the dev server running on ${BASE_URL}? start it with \`pnpm run dev\`, or point the seed elsewhere with LUNORA_SEED_URL.`);
    process.exitCode = 1;
}
