/* eslint-disable no-console -- a terminal script: the files it wrote are the deliverable, and it says which. */
/*
 * Vendor the release-manifest translation into the build box.
 *
 * The box's `runtime: "worker"` path turns a plain Worker's wrangler config into
 * the same release a Lunora project's `lunora cloud deploy --out` writes: the
 * binding manifest (`buildBindingManifest`, `@lunora/config`) and the static
 * assets (`collectAssets`, `@lunora/cli`). A plain Worker has no Lunora CLI in
 * its lockfile to run them, and the box installs nothing at image build, so the
 * two functions are bundled from their SOURCE into one zero-dependency ESM file:
 *
 * ```bash
 * node --experimental-strip-types apps/cloud/scripts/vendor-release-manifest.ts
 * ```
 *
 * Bundled rather than copied because `collectAssets` walks the tree with
 * `@visulima/fs` (and through it picomatch); their licences ride beside the
 * bundle. `__tests__/build-box-worker-vendor.test.ts` re-runs this bundle in
 * memory and fails while the committed copy differs — so a change to either
 * source, or an esbuild / dependency bump, is: run this script, commit both files.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const VENDOR = join(REPO, "apps/cloud/containers/build/vendor");

/** The two sources, repo-relative so the bundle's region comments do not depend on where the checkout lives. */
const ENTRY = [
    'export { buildBindingManifest } from "./packages/config/src/cloudflare/binding-manifest.ts";',
    'export { collectAssets } from "./packages/cli/src/util/cloud-client.ts";',
].join("\n");

const BANNER = [
    // Type-checked at its source; the bundle's minified dependencies are not this repo's to check.
    "// @ts-nocheck",
    "// Generated by apps/cloud/scripts/vendor-release-manifest.ts from",
    "// packages/config/src/cloudflare/binding-manifest.ts (buildBindingManifest) and",
    "// packages/cli/src/util/cloud-client.ts (collectAssets). Do not edit: re-run the script.",
    "// Third-party licences: release-manifest.LICENSES beside this file.",
].join("\n");

/** `node_modules/&lt;name>` or `node_modules/@scope/&lt;name>` — the package an input file belongs to. */
const PACKAGE_DIRECTORY = /^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//u;

/** `LICENSE`, `LICENCE.md`, `license.txt`, … */
const LICENSE_FILE = /^licen[cs]e/iu;

/** The licence text of every third-party package the bundle inlines, sorted by package name. */
const thirdPartyLicenses = (inputs: ReadonlyArray<string>): string => {
    const directories = new Map<string, string>();

    for (const input of inputs) {
        const directory = PACKAGE_DIRECTORY.exec(input)?.[1];

        if (directory !== undefined) {
            const { name, version } = JSON.parse(readFileSync(join(REPO, directory, "package.json"), "utf8")) as { name: string; version: string };

            directories.set(`${name}@${version}`, join(REPO, directory));
        }
    }

    return [...directories.entries()]
        .toSorted(([a], [b]) => a.localeCompare(b))
        .map(([name, directory]) => {
            const file = readdirSync(directory).find((entry) => LICENSE_FILE.test(entry));

            if (file === undefined) {
                throw new Error(`${name} ships no licence file; it cannot be vendored`);
            }

            return `${name}\n${"=".repeat(name.length)}\n\n${readFileSync(join(directory, file), "utf8").trim()}\n`;
        })
        .join("\n");
};

/**
 * Bundle the translation, in memory. Exported for the freshness test, which
 * compares this output with the committed files byte for byte.
 */
const bundleReleaseManifest = async (): Promise<{ licenses: string; module: string }> => {
    const result = await build({
        // Repo-relative paths in the bundle's comments, wherever the checkout is.
        absWorkingDir: REPO,
        banner: { js: BANNER },
        bundle: true,
        format: "esm",
        legalComments: "none",
        metafile: true,
        platform: "node",
        stdin: { contents: ENTRY, loader: "ts", resolveDir: REPO, sourcefile: "release-manifest-entry.ts" },
        target: "node22",
        write: false,
    });
    const output = result.outputFiles.at(0);

    if (output === undefined) {
        throw new Error("esbuild produced no output");
    }

    return { licenses: thirdPartyLicenses(Object.keys(result.metafile.inputs)), module: output.text };
};

const invoked = process.argv.at(1);

if (invoked !== undefined && resolve(invoked) === fileURLToPath(import.meta.url)) {
    const { licenses, module } = await bundleReleaseManifest();

    writeFileSync(join(VENDOR, "release-manifest.mjs"), module);
    writeFileSync(join(VENDOR, "release-manifest.LICENSES"), licenses);
    console.log(`wrote ${join(VENDOR, "release-manifest.mjs")} (${String(module.length)} bytes) and its licences`);
}

export default bundleReleaseManifest;
