/**
 * `vis generate cirrus-collections` — scaffold `cirrus/collections.ts`, a
 * `@cirrus/db` `defineCollections` call pre-filled from the schema (+ the
 * generated `api.ts` when present).
 *
 * Reads are wired by convention (`api.<table>.list`) and sharded tables get a
 * `scopeBy`. When the generated `api.ts` is available, a table whose namespace
 * has a conventional insert mutation (`create`/`send`/`add`/`insert`) gets a
 * complete, compiling `insert` binding — `toArgs` mapped from the mutation's real
 * arguments, `optimistic` typed as `Omit<Doc, meta>`. Without `api.ts` (codegen
 * not yet run) the `insert` is emitted as a commented template to complete.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { createTemplate } from "@visulima/vis/generate";

import type { ApiNamespace } from "./_helpers/parse-api.js";
import { parseApiNamespaces } from "./_helpers/parse-api.js";
import type { SchemaTable } from "./_helpers/parse-schema.js";
import { parseSchemaTables } from "./_helpers/parse-schema.js";

/** Mutation names that, by convention, persist a new row into their table. */
const INSERT_MUTATION_NAMES = new Set(["add", "create", "insert", "send"]);

/** Build the `toArgs` body from an insert mutation's argument names (`id` → `row._id`). */
const renderToArgs = (args: string[]): string => {
    const pairs = args.map((argument) => (argument === "id" ? "id: row._id" : `${argument}: row.${argument}`));

    return `{ ${pairs.join(", ")} }`;
};

/** Render one table's entry, using the api namespace (when known) to wire writes. */
const renderTable = (table: SchemaTable, namespace: ApiNamespace | undefined): string => {
    const lines: string[] = [`        ${table.name}: {`, `            list: api.${table.name}.list,`];

    if (table.shardBy !== undefined) {
        lines.push(`            scopeBy: ${JSON.stringify(table.shardBy)},`);
    }

    const insertMutation = namespace?.functions.find((function_) => function_.kind === "mutation" && INSERT_MUTATION_NAMES.has(function_.name));

    if (insertMutation) {
        // We know the mutation and its real args — emit a complete, typed binding.
        lines.push(
            `            insert: {`,
            `                mutation: api.${table.name}.${insertMutation.name},`,
            `                optimistic: (input: Omit<Doc<${JSON.stringify(table.name)}>, "_id" | "_creationTime">, id) => ({`,
            `                    _id: id as Id<${JSON.stringify(table.name)}>,`,
            `                    _creationTime: Date.now(),`,
            `                    ...input,`,
            `                }),`,
            `                toArgs: (row) => (${renderToArgs(insertMutation.args)}),`,
            `            },`,
        );
    } else if (namespace === undefined) {
        // No api.ts yet — emit a template listing the table's columns.
        const inputColumns = table.columns.length > 0 ? table.columns.join(", ") : "/* … */";

        lines.push(
            `            // To make ${table.name} writable, run codegen then re-generate, or fill in:`,
            `            // insert: {`,
            `            //     mutation: api.${table.name}.create,`,
            `            //     optimistic: (input: { ${inputColumns} }, id) => ({ _id: id as Id<${JSON.stringify(table.name)}>, _creationTime: Date.now(), ...input }),`,
            `            //     toArgs: (row) => ({ id: row._id /* , …the fields the mutation accepts */ }),`,
            `            // },`,
        );
    }

    lines.push(`        },`);

    return lines.join("\n");
};

const renderCollectionsFile = (tables: SchemaTable[], namespaces: ApiNamespace[]): string => {
    const byName = new Map(namespaces.map((namespace) => [namespace.name, namespace]));
    const entries = tables.map((table) => renderTable(table, byName.get(table.name))).join("\n");

    return `import { defineCollections } from "@cirrus/db";
import type { CirrusClient } from "@cirrus/react";

import { api } from "./_generated/api.js";
// eslint-disable-next-line unicorn/prevent-abbreviations -- "Doc"/"Id" are generated dataModel type names; aliasing them breaks codegen
import type { Doc, Id } from "./_generated/dataModel.js";

/**
 * Generated by \`vis generate cirrus-collections\` — edit freely.
 *
 * Reads are wired from each table's \`list\` query; sharded tables expose a
 * \`scopeBy\`. Writable tables carry an \`insert\` binding through the offline
 * outbox. Pass your \`CirrusClient\` (from the provider) to get the live
 * collections + actions.
 */
export const createCollections = (client: CirrusClient) =>
    defineCollections(client, {
${entries}
    });
`;
};

export default createTemplate({
    about: {
        description: "Scaffold cirrus/collections.ts (a @cirrus/db defineCollections call) from schema.ts",
        name: "cirrus-collections",
    },
    options: {},
    produce: ({ builtins }) => {
        const schemaPath = join(builtins.dest_dir, "cirrus", "schema.ts");

        if (!existsSync(schemaPath)) {
            throw new Error(`no cirrus/schema.ts found at ${schemaPath} — create a schema first (vis generate cirrus-table).`);
        }

        const tables = parseSchemaTables(readFileSync(schemaPath, "utf8"));

        if (tables.length === 0) {
            throw new Error(`no tables found in ${schemaPath} — is it a defineSchema({ … }) with table entries?`);
        }

        const apiPath = join(builtins.dest_dir, "cirrus", "_generated", "api.ts");
        const namespaces = existsSync(apiPath) ? parseApiNamespaces(readFileSync(apiPath, "utf8")) : [];

        const writable = tables.filter((table) =>
            namespaces
                .find((namespace) => namespace.name === table.name)
                ?.functions.some((function_) => function_.kind === "mutation" && INSERT_MUTATION_NAMES.has(function_.name)),
        );

        return {
            files: { cirrus: { "collections.ts": renderCollectionsFile(tables, namespaces) } },
            filesMeta: { "cirrus/collections.ts": { force: true } },
            suggestions: [
                `Scaffolded cirrus/collections.ts for ${tables.length} table(s): ${tables.map((table) => table.name).join(", ")}.`,
                namespaces.length === 0
                    ? "Run `cirrus codegen` then re-generate to auto-wire write actions from your mutations."
                    : `Wired write actions for: ${writable.map((table) => table.name).join(", ") || "(none — no conventional insert mutations found)"}.`,
                "Then call `createCollections(client)` from your app.",
            ],
        };
    },
});
