/**
 * `vis generate cirrus-collections` — scaffold `cirrus/collections.ts`, a
 * `@cirrus/db` `defineCollections` call pre-filled from the schema.
 *
 * Reads are wired by convention (`api.<table>.list`) and sharded tables get a
 * `scopeBy`, both derived from `schema.ts`. The app-specific `insert` binding
 * (which mutation persists the row, and how the optimistic row maps to its args)
 * is emitted as a commented template per writable table, since codegen can't
 * safely guess a mutation's auth-scoped argument shape.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { createTemplate } from "@visulima/vis/generate";

import { parseSchemaTables, type SchemaTable } from "./_helpers/parse-schema.js";

/** Render one table's entry in the `defineCollections({ … })` object. */
const renderTable = (table: SchemaTable): string => {
    const lines: string[] = [`        ${table.name}: {`, `            list: api.${table.name}.list,`];

    if (table.shardBy !== undefined) {
        lines.push(`            scopeBy: ${JSON.stringify(table.shardBy)},`);
    }

    // A commented `insert` template — uncomment + adjust which fields the mutation
    // actually accepts (server-derived columns like `userId`/`createdAt` usually
    // come from auth/defaults, not the action input).
    const inputColumns = table.columns.length > 0 ? table.columns.join(", ") : "/* … */";

    lines.push(
        `            // To make ${table.name} writable through the offline outbox, fill in:`,
        `            // insert: {`,
        `            //     mutation: api.${table.name}.create,`,
        `            //     optimistic: (input: { ${inputColumns} }, id) => ({`,
        `            //         _id: id as Id<${JSON.stringify(table.name)}>,`,
        `            //         _creationTime: Date.now(),`,
        ...table.columns.map((column) => `            //         ${column}: input.${column},`),
        `            //     }),`,
        `            //     toArgs: (row) => ({ id: row._id /* , …the fields the mutation accepts */ }),`,
        `            // },`,
        `        },`,
    );

    return lines.join("\n");
};

const renderCollectionsFile = (tables: SchemaTable[]): string => {
    const entries = tables.map((table) => renderTable(table)).join("\n");

    return `import { defineCollections } from "@cirrus/db";
import type { CirrusClient } from "@cirrus/react";

import { api } from "./_generated/api.js";
// eslint-disable-next-line unicorn/prevent-abbreviations -- "Doc"/"Id" are generated dataModel type names; aliasing them breaks codegen
import type { Doc, Id } from "./_generated/dataModel.js";

/**
 * Generated by \`vis generate cirrus-collections\` — edit freely.
 *
 * Reads are wired by convention (\`api.<table>.list\`); sharded tables expose a
 * \`scopeBy\`. Uncomment + complete an \`insert\` binding to make a table writable
 * through the offline outbox. Pass your \`CirrusClient\` (from the provider).
 */
export const createCollections = (client: CirrusClient) =>
    defineCollections(client, {
${entries}
    });
`;
};

export default createTemplate({
    about: {
        description: "Scaffold cirrus/collections.ts (a @cirrus/db defineCollections call) from schema.ts",
        name: "cirrus-collections",
    },
    options: {},
    produce: ({ builtins }) => {
        const schemaPath = join(builtins.dest_dir, "cirrus", "schema.ts");

        if (!existsSync(schemaPath)) {
            throw new Error(`no cirrus/schema.ts found at ${schemaPath} — create a schema first (vis generate cirrus-table).`);
        }

        const tables = parseSchemaTables(readFileSync(schemaPath, "utf8"));

        if (tables.length === 0) {
            throw new Error(`no tables found in ${schemaPath} — is it a defineSchema({ … }) with table entries?`);
        }

        return {
            files: { cirrus: { "collections.ts": renderCollectionsFile(tables) } },
            filesMeta: { "cirrus/collections.ts": { force: true } },
            suggestions: [
                `Scaffolded cirrus/collections.ts for ${tables.length} table(s): ${tables.map((table) => table.name).join(", ")}.`,
                "Uncomment + complete the `insert` blocks for tables you write to, then call `createCollections(client)`.",
            ],
        };
    },
});
