/**
 * `vis generate cirrus-collections` — scaffold `cirrus/collections.ts`, a
 * `@cirrus/db` `defineCollections` call pre-filled from the schema + functions.
 *
 * Reads are wired from each table's `list` query; sharded tables get a `scopeBy`.
 * The insert mutation for each table is attributed by **behavior** — the function
 * that calls `ctx.db.insert("<table>", …)` (see `discover-inserts`) — not by
 * naming convention. When the generated `api.ts` is present, that mutation's real
 * argument names produce a complete, compiling `insert` binding; otherwise the
 * binding is emitted as a commented template referencing the discovered mutation.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { discoverInserts } from "@cirrus/codegen";
import { createTemplate } from "@visulima/vis/generate";
import { Project } from "ts-morph";

import type { ApiNamespace } from "./_helpers/parse-api.js";
import { parseApiNamespaces } from "./_helpers/parse-api.js";
import type { SchemaTable } from "./_helpers/parse-schema.js";
import { parseSchemaTables } from "./_helpers/parse-schema.js";

/** A table's attributed insert mutation: the function (and its file = api namespace) that inserts into it. */
interface InsertMutationRef {
    name: string;
    namespace: string;
}

type InsertPlan = { args: string[]; kind: "active"; ref: InsertMutationRef } | { kind: "template"; ref: InsertMutationRef } | undefined;

/** Build the `toArgs` body from an insert mutation's argument names (`id` → `row._id`). */
const renderToArgs = (args: string[]): string => {
    const pairs = args.map((argument) => (argument === "id" ? "id: row._id" : `${argument}: row.${argument}`));

    return `{ ${pairs.join(", ")} }`;
};

/** Render one table's entry, wiring its write action from the attributed insert mutation. */
const renderTable = (table: SchemaTable, insert: InsertPlan): string => {
    const lines: string[] = [`        ${table.name}: {`, `            list: api.${table.name}.list,`];

    if (table.shardBy !== undefined) {
        lines.push(`            scopeBy: ${JSON.stringify(table.shardBy)},`);
    }

    if (insert?.kind === "active") {
        lines.push(
            `            insert: {`,
            `                mutation: api.${insert.ref.namespace}.${insert.ref.name},`,
            `                optimistic: (input: Omit<Doc<${JSON.stringify(table.name)}>, "_id" | "_creationTime">, id) => ({`,
            `                    _id: id as Id<${JSON.stringify(table.name)}>,`,
            `                    _creationTime: Date.now(),`,
            `                    ...input,`,
            `                }),`,
            `                toArgs: (row) => (${renderToArgs(insert.args)}),`,
            `            },`,
        );
    } else if (insert?.kind === "template") {
        const inputColumns = table.columns.length > 0 ? table.columns.join(", ") : "/* … */";

        lines.push(
            `            // ${insert.ref.namespace}.${insert.ref.name} inserts into ${table.name}. Run codegen + re-generate to`,
            `            // wire this automatically, or complete the binding:`,
            `            // insert: {`,
            `            //     mutation: api.${insert.ref.namespace}.${insert.ref.name},`,
            `            //     optimistic: (input: { ${inputColumns} }, id) => ({ _id: id as Id<${JSON.stringify(table.name)}>, _creationTime: Date.now(), ...input }),`,
            `            //     toArgs: (row) => ({ id: row._id /* , …the fields the mutation accepts */ }),`,
            `            // },`,
        );
    }

    lines.push(`        },`);

    return lines.join("\n");
};

const renderCollectionsFile = (tables: SchemaTable[], plans: Map<string, InsertPlan>): string => {
    const entries = tables.map((table) => renderTable(table, plans.get(table.name))).join("\n");

    return `import { defineCollections } from "@cirrus/db";
import type { CirrusClient } from "@cirrus/react";

import { api } from "./_generated/api.js";
// eslint-disable-next-line unicorn/prevent-abbreviations -- "Doc"/"Id" are generated dataModel type names; aliasing them breaks codegen
import type { Doc, Id } from "./_generated/dataModel.js";

/**
 * Generated by \`vis generate cirrus-collections\` — edit freely.
 *
 * Reads are wired from each table's \`list\` query; sharded tables expose a
 * \`scopeBy\`. Writable tables carry an \`insert\` binding through the offline
 * outbox. Pass your \`CirrusClient\` (from the provider) to get the live
 * collections + actions.
 */
export const createCollections = (client: CirrusClient) =>
    defineCollections(client, {
${entries}
    });
`;
};

/** Resolve each table's write plan: the attributed insert mutation + its args (if api.ts is present). */
const planInserts = (tables: SchemaTable[], inserts: Map<string, InsertMutationRef>, namespaces: ApiNamespace[]): Map<string, InsertPlan> => {
    const plans = new Map<string, InsertPlan>();

    for (const table of tables) {
        const ref = inserts.get(table.name);

        if (ref === undefined) {
            continue;
        }

        const args = namespaces.find((namespace) => namespace.name === ref.namespace)?.functions.find((function_) => function_.name === ref.name)?.args;

        plans.set(table.name, args === undefined ? { kind: "template", ref } : { args, kind: "active", ref });
    }

    return plans;
};

export default createTemplate({
    about: {
        description: "Scaffold cirrus/collections.ts (a @cirrus/db defineCollections call) from schema.ts",
        name: "cirrus-collections",
    },
    options: {},
    produce: ({ builtins }) => {
        const cirrusDir = join(builtins.dest_dir, "cirrus");
        const schemaPath = join(cirrusDir, "schema.ts");

        if (!existsSync(schemaPath)) {
            throw new Error(`no cirrus/schema.ts found at ${schemaPath} — create a schema first (vis generate cirrus-table).`);
        }

        const tables = parseSchemaTables(readFileSync(schemaPath, "utf8"));

        if (tables.length === 0) {
            throw new Error(`no tables found in ${schemaPath} — is it a defineSchema({ … }) with table entries?`);
        }

        const apiPath = join(cirrusDir, "_generated", "api.ts");
        const namespaces = existsSync(apiPath) ? parseApiNamespaces(readFileSync(apiPath, "utf8")) : [];

        // Attribute each table's insert mutation by behavior (which exported
        // function calls `ctx.db.insert("<table>", …)`) via @cirrus/codegen's
        // first-class discovery; first inserter for a table wins.
        const inserts = new Map<string, InsertMutationRef>();

        for (const write of discoverInserts(new Project({ skipAddingFilesFromTsConfig: true, useInMemoryFileSystem: false }), cirrusDir)) {
            if (write.table !== "" && !inserts.has(write.table)) {
                inserts.set(write.table, { name: write.exportName, namespace: write.file });
            }
        }

        const plans = planInserts(tables, inserts, namespaces);

        const wired = [...plans.entries()].filter(([, plan]) => plan?.kind === "active").map(([table]) => table);

        return {
            files: { cirrus: { "collections.ts": renderCollectionsFile(tables, plans) } },
            filesMeta: { "cirrus/collections.ts": { force: true } },
            suggestions: [
                `Scaffolded cirrus/collections.ts for ${tables.length} table(s): ${tables.map((table) => table.name).join(", ")}.`,
                wired.length > 0
                    ? `Wired write actions (attributed by ctx.db.insert calls) for: ${wired.join(", ")}.`
                    : "Run `cirrus codegen` then re-generate to auto-wire write actions from your mutations.",
                "Then call `createCollections(client)` from your app.",
            ],
        };
    },
});
