/**
 * `vis generate lunora-collections` — scaffold `lunora/collections.ts`, a
 * `@lunora/db` `defineCollections` call pre-filled from the schema + functions.
 *
 * Reads are wired from each table's `list` query; sharded tables get a `scopeBy`.
 * The insert mutation for each table is attributed by **behavior** — the function
 * that calls `ctx.db.insert("<table>", …)` (see `discover/inserts`) — not by
 * naming convention. When the generated `api.ts` is present, that mutation's real
 * argument names produce a complete, compiling `insert` binding; otherwise the
 * binding is emitted as a commented template referencing the discovered mutation.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { InsertWriteIR } from "@lunora/codegen";
import { discoverInserts } from "@lunora/codegen";
import { createTemplate } from "@visulima/vis/generate";
import { Project } from "ts-morph";

import type { ApiNamespace } from "./_helpers/parse-api.js";
import { parseApiNamespaces } from "./_helpers/parse-api.js";
import type { SchemaTable } from "./_helpers/parse-schema.js";
import { parseSchemaTables } from "./_helpers/parse-schema.js";

/** A table's attributed insert mutation: the function (and its file = api namespace) that inserts into it. */
interface InsertMutationRef {
    name: string;
    namespace: string;
}

type InsertPlan = { args: string[]; kind: "active"; ref: InsertMutationRef } | { kind: "template"; ref: InsertMutationRef } | undefined;

/** Build the `toArgs` body from an insert mutation's argument names (`id` → `row._id`). */
const renderToArgs = (args: string[]): string => {
    const pairs = args.map((argument) => (argument === "id" ? "id: row._id" : `${argument}: row.${argument}`));

    return `{ ${pairs.join(", ")} }`;
};

/** Render one table's entry, wiring its write action from the attributed insert mutation. */
const renderTable = (table: SchemaTable, insert: InsertPlan): string => {
    const lines: string[] = [`        ${table.name}: {`, `            list: api.${table.name}.list,`];

    if (table.shardBy !== undefined) {
        lines.push(`            scopeBy: ${JSON.stringify(table.shardBy)},`);
    }

    if (insert?.kind === "active") {
        lines.push(
            `            insert: {`,
            `                mutation: api.${insert.ref.namespace}.${insert.ref.name},`,
            `                optimistic: (input: Omit<Doc<${JSON.stringify(table.name)}>, "_id" | "_creationTime">, id) => ({`,
            `                    _id: id as Id<${JSON.stringify(table.name)}>,`,
            `                    _creationTime: Date.now(),`,
            `                    ...input,`,
            `                }),`,
            `                toArgs: (row) => (${renderToArgs(insert.args)}),`,
            `            },`,
        );
    } else if (insert?.kind === "template") {
        const inputColumns = table.columns.length > 0 ? table.columns.join(", ") : "/* … */";

        lines.push(
            `            // ${insert.ref.namespace}.${insert.ref.name} inserts into ${table.name}. Run codegen + re-generate to`,
            `            // wire this automatically, or complete the binding:`,
            `            // insert: {`,
            `            //     mutation: api.${insert.ref.namespace}.${insert.ref.name},`,
            `            //     optimistic: (input: { ${inputColumns} }, id) => ({ _id: id as Id<${JSON.stringify(table.name)}>, _creationTime: Date.now(), ...input }),`,
            `            //     toArgs: (row) => ({ id: row._id /* , …the fields the mutation accepts */ }),`,
            `            // },`,
        );
    }

    lines.push(`        },`);

    return lines.join("\n");
};

const renderCollectionsFile = (tables: SchemaTable[], plans: Map<string, InsertPlan>): string => {
    const entries = tables.map((table) => renderTable(table, plans.get(table.name))).join("\n");

    return `import { defineCollections } from "@lunora/db";
import type { LunoraClient } from "@lunora/react";

import { api } from "./_generated/api.js";
// eslint-disable-next-line unicorn/prevent-abbreviations -- "Doc"/"Id" are generated dataModel type names; aliasing them breaks codegen
import type { Doc, Id } from "./_generated/dataModel.js";

/**
 * Generated by \`vis generate lunora-collections\` — edit freely.
 *
 * Reads are wired from each table's \`list\` query; sharded tables expose a
 * \`scopeBy\`. Writable tables carry an \`insert\` binding through the offline
 * outbox. Pass your \`LunoraClient\` (from the provider) to get the live
 * collections + actions.
 */
export const createCollections = (client: LunoraClient) =>
    defineCollections(client, {
${entries}
    });
`;
};

/**
 * The exported functions an insert site runs on behalf of — the ones a
 * collection can call as its insert mutation: the export the insert sits in, or
 * every export calling the helper it sits in. An insert at module scope, or in a
 * helper no export calls, has none: there is no function to wire.
 */
const insertCallers = (scope: InsertWriteIR["scope"]): readonly string[] => {
    switch (scope.kind) {
        case "export": {
            return [scope.name];
        }
        case "helper": {
            return scope.callers;
        }
        default: {
            return [];
        }
    }
};

/**
 * Each table's candidate insert mutations, in discovery order: every exported
 * function that reaches a `ctx.db.insert("<table>", …)`, directly or through a
 * same-file helper.
 */
const insertCandidates = (writes: readonly InsertWriteIR[]): Map<string, InsertMutationRef[]> => {
    const candidates = new Map<string, InsertMutationRef[]>();

    for (const write of writes) {
        if (write.table === "") {
            continue;
        }

        const known = candidates.get(write.table) ?? [];
        const added = insertCallers(write.scope)
            .filter((name) => !known.some((ref) => ref.name === name && ref.namespace === write.file))
            .map((name) => {
                return { name, namespace: write.file };
            });

        candidates.set(write.table, [...known, ...added]);
    }

    return candidates;
};

/**
 * Resolve each table's write plan. The first candidate `api.ts` lists (so its
 * args are known) is wired; failing that — no `api.ts`, or a helper's callers
 * that are not registered mutations — the first candidate is left as a template.
 */
const planInserts = (tables: SchemaTable[], inserts: Map<string, InsertMutationRef[]>, namespaces: ApiNamespace[]): Map<string, InsertPlan> => {
    const plans = new Map<string, InsertPlan>();
    const argsOf = (ref: InsertMutationRef): string[] | undefined =>
        namespaces.find((namespace) => namespace.name === ref.namespace)?.functions.find((function_) => function_.name === ref.name)?.args;

    for (const table of tables) {
        const refs = inserts.get(table.name) ?? [];
        const active = refs.find((ref) => argsOf(ref) !== undefined);
        const [first] = refs;

        if (active !== undefined) {
            plans.set(table.name, { args: argsOf(active) ?? [], kind: "active", ref: active });
        } else if (first !== undefined) {
            plans.set(table.name, { kind: "template", ref: first });
        }
    }

    return plans;
};

export default createTemplate({
    about: {
        description: "Scaffold lunora/collections.ts (a @lunora/db defineCollections call) from schema.ts",
        name: "lunora-collections",
    },
    options: {},
    produce: ({ builtins }) => {
        const lunoraDir = join(builtins.dest_dir, "lunora");
        const schemaPath = join(lunoraDir, "schema.ts");

        if (!existsSync(schemaPath)) {
            throw new Error(`no lunora/schema.ts found at ${schemaPath} — create a schema first (vis generate lunora-table).`);
        }

        const tables = parseSchemaTables(readFileSync(schemaPath, "utf8"));

        if (tables.length === 0) {
            throw new Error(`no tables found in ${schemaPath} — is it a defineSchema({ … }) with table entries?`);
        }

        const apiPath = join(lunoraDir, "_generated", "api.ts");
        const namespaces = existsSync(apiPath) ? parseApiNamespaces(readFileSync(apiPath, "utf8")) : [];

        // Attribute each table's insert mutation by behavior (which exported
        // function reaches `ctx.db.insert("<table>", …)`, directly or through a
        // same-file helper) via @lunora/codegen's first-class discovery.
        const inserts = insertCandidates(discoverInserts(new Project({ skipAddingFilesFromTsConfig: true, useInMemoryFileSystem: false }), lunoraDir));

        const plans = planInserts(tables, inserts, namespaces);

        const wired = [...plans.entries()].filter(([, plan]) => plan?.kind === "active").map(([table]) => table);

        return {
            files: { lunora: { "collections.ts": renderCollectionsFile(tables, plans) } },
            filesMeta: { "lunora/collections.ts": { force: true } },
            suggestions: [
                `Scaffolded lunora/collections.ts for ${tables.length} table(s): ${tables.map((table) => table.name).join(", ")}.`,
                wired.length > 0
                    ? `Wired write actions (attributed by ctx.db.insert calls) for: ${wired.join(", ")}.`
                    : "Run `lunora codegen` then re-generate to auto-wire write actions from your mutations.",
                "Then call `createCollections(client)` from your app.",
            ],
        };
    },
});
