// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { FunctionReference } from "lunorash/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    todos: {
        add: FunctionReference<"mutation", { text: string }, Id<"todos">>;
        list: FunctionReference<"query", {}, { _id: Id<"todos">; createdAt: number; done: boolean; text: string }[]>;
        remove: FunctionReference<"mutation", { id: Id<"todos"> }, void>;
        toggle: FunctionReference<"mutation", { id: Id<"todos">; done: boolean }, void>;
    };
}

export const api: ApiTypes = {
    todos: {
        add: { __lunoraRef: "todos:add" },
        list: { __lunoraRef: "todos:list" },
        remove: { __lunoraRef: "todos:remove" },
        toggle: { __lunoraRef: "todos:toggle" },
    },
};
