// swift-tools-version:5.9

import PackageDescription

// The Lunora Swift client.
//
// Deliberately dependency-free — Foundation only. The HTTP poster and the
// WebSocket frame sender are injected by the caller, so the conformance suite
// runs offline and a consumer picks its own networking stack rather than
// inheriting ours.
let package = Package(
    name: "Lunora",
    platforms: [.macOS(.v12), .iOS(.v15)],
    products: [
        .library(name: "Lunora", targets: ["Lunora"])
    ],
    targets: [
        .target(name: "Lunora"),
        // Proves the generated surface still builds against the runtime, a
        // coupling the target contract deliberately keeps out of itself.
        // Regenerated by CI; the committed copy is a sample.
        .target(name: "GeneratedCheck", dependencies: ["Lunora"]),
        .testTarget(name: "LunoraTests", dependencies: ["Lunora"]),
        // Not compile-only: building proved the shapes line up while a generated
        // call still threw on first use in two other languages.
        .testTarget(name: "GeneratedCheckTests", dependencies: ["GeneratedCheck", "Lunora"]),
    ]
)
