// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import { anyApi } from "@cirrus/server/types";
import type { FunctionReference } from "@cirrus/client";

import type { Id } from "./dataModel.js";

export interface ApiTypes {
    messages: {
        list: FunctionReference<"query", { channelId: Id<"channels">; limit?: number }, unknown>;
        send: FunctionReference<"mutation", { channelId: Id<"channels">; text: string; kind: "text" | "image"; tags: Record<string, string> }, unknown>;
    };
}

export const api = anyApi as unknown as ApiTypes;
