// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export const openRpcSpec: Record<string, unknown> = {
    "info": {
        "description": "Auto-generated from @lunora/values-typed functions by @lunora/codegen. Do not edit — run `lunora codegen` to regenerate.",
        "title": "Lunora RPC",
        "version": "0.0.0"
    },
    "methods": [
        {
            "description": "Invoke the `query` `messages:list` over the Lunora RPC envelope (POST /_lunora/rpc, body `{ \"functionPath\": \"messages:list\", \"args\": { … } }`).",
            "errors": [
                {
                    "code": -32000,
                    "data": {
                        "code": "BAD_REQUEST"
                    },
                    "message": "BAD_REQUEST"
                },
                {
                    "code": -32001,
                    "data": {
                        "code": "CONFLICT"
                    },
                    "message": "CONFLICT"
                },
                {
                    "code": -32002,
                    "data": {
                        "code": "COUNT_RLS_UNSUPPORTED"
                    },
                    "message": "COUNT_RLS_UNSUPPORTED"
                },
                {
                    "code": -32003,
                    "data": {
                        "code": "FORBIDDEN"
                    },
                    "message": "FORBIDDEN"
                },
                {
                    "code": -32004,
                    "data": {
                        "code": "FUNCTION_NOT_FOUND"
                    },
                    "message": "FUNCTION_NOT_FOUND"
                },
                {
                    "code": -32005,
                    "data": {
                        "code": "INTERNAL"
                    },
                    "message": "INTERNAL"
                },
                {
                    "code": -32006,
                    "data": {
                        "code": "INTERNAL_SERVER_ERROR"
                    },
                    "message": "INTERNAL_SERVER_ERROR"
                },
                {
                    "code": -32007,
                    "data": {
                        "code": "METHOD_NOT_ALLOWED"
                    },
                    "message": "METHOD_NOT_ALLOWED"
                },
                {
                    "code": -32008,
                    "data": {
                        "code": "NOT_FOUND"
                    },
                    "message": "NOT_FOUND"
                },
                {
                    "code": -32009,
                    "data": {
                        "code": "NOT_IMPLEMENTED"
                    },
                    "message": "NOT_IMPLEMENTED"
                },
                {
                    "code": -32010,
                    "data": {
                        "code": "PAYLOAD_TOO_LARGE"
                    },
                    "message": "PAYLOAD_TOO_LARGE"
                },
                {
                    "code": -32011,
                    "data": {
                        "code": "TOO_MANY_REQUESTS"
                    },
                    "message": "TOO_MANY_REQUESTS"
                },
                {
                    "code": -32012,
                    "data": {
                        "code": "UNAUTHORIZED"
                    },
                    "message": "UNAUTHORIZED"
                },
                {
                    "code": -32013,
                    "data": {
                        "code": "UNPROCESSABLE"
                    },
                    "message": "UNPROCESSABLE"
                },
                {
                    "code": -32014,
                    "data": {
                        "code": "VALIDATION_ERROR"
                    },
                    "message": "VALIDATION_ERROR"
                }
            ],
            "name": "messages:list",
            "params": [
                {
                    "description": "The function's argument object (the RPC envelope's `args`).",
                    "name": "args",
                    "required": true,
                    "schema": {
                        "properties": {
                            "channelId": {
                                "description": "Id<\"channels\">",
                                "type": "string",
                                "x-lunora-table": "channels"
                            },
                            "limit": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "channelId"
                        ],
                        "type": "object"
                    }
                }
            ],
            "result": {
                "name": "result",
                "schema": {
                    "description": "Result is TS-inferred from the function's return type (no `.output()` declared); best-effort — any JSON."
                }
            },
            "summary": "query: messages:list",
            "x-lunora-function-kind": "query",
            "x-tags": [
                {
                    "name": "messages"
                }
            ]
        },
        {
            "description": "Invoke the `mutation` `messages:send` over the Lunora RPC envelope (POST /_lunora/rpc, body `{ \"functionPath\": \"messages:send\", \"args\": { … } }`).",
            "errors": [
                {
                    "code": -32000,
                    "data": {
                        "code": "BAD_REQUEST"
                    },
                    "message": "BAD_REQUEST"
                },
                {
                    "code": -32001,
                    "data": {
                        "code": "CONFLICT"
                    },
                    "message": "CONFLICT"
                },
                {
                    "code": -32002,
                    "data": {
                        "code": "COUNT_RLS_UNSUPPORTED"
                    },
                    "message": "COUNT_RLS_UNSUPPORTED"
                },
                {
                    "code": -32003,
                    "data": {
                        "code": "FORBIDDEN"
                    },
                    "message": "FORBIDDEN"
                },
                {
                    "code": -32004,
                    "data": {
                        "code": "FUNCTION_NOT_FOUND"
                    },
                    "message": "FUNCTION_NOT_FOUND"
                },
                {
                    "code": -32005,
                    "data": {
                        "code": "INTERNAL"
                    },
                    "message": "INTERNAL"
                },
                {
                    "code": -32006,
                    "data": {
                        "code": "INTERNAL_SERVER_ERROR"
                    },
                    "message": "INTERNAL_SERVER_ERROR"
                },
                {
                    "code": -32007,
                    "data": {
                        "code": "METHOD_NOT_ALLOWED"
                    },
                    "message": "METHOD_NOT_ALLOWED"
                },
                {
                    "code": -32008,
                    "data": {
                        "code": "NOT_FOUND"
                    },
                    "message": "NOT_FOUND"
                },
                {
                    "code": -32009,
                    "data": {
                        "code": "NOT_IMPLEMENTED"
                    },
                    "message": "NOT_IMPLEMENTED"
                },
                {
                    "code": -32010,
                    "data": {
                        "code": "PAYLOAD_TOO_LARGE"
                    },
                    "message": "PAYLOAD_TOO_LARGE"
                },
                {
                    "code": -32011,
                    "data": {
                        "code": "TOO_MANY_REQUESTS"
                    },
                    "message": "TOO_MANY_REQUESTS"
                },
                {
                    "code": -32012,
                    "data": {
                        "code": "UNAUTHORIZED"
                    },
                    "message": "UNAUTHORIZED"
                },
                {
                    "code": -32013,
                    "data": {
                        "code": "UNPROCESSABLE"
                    },
                    "message": "UNPROCESSABLE"
                },
                {
                    "code": -32014,
                    "data": {
                        "code": "VALIDATION_ERROR"
                    },
                    "message": "VALIDATION_ERROR"
                }
            ],
            "name": "messages:send",
            "params": [
                {
                    "description": "The function's argument object (the RPC envelope's `args`).",
                    "name": "args",
                    "required": true,
                    "schema": {
                        "properties": {
                            "channelId": {
                                "description": "Id<\"channels\">",
                                "type": "string",
                                "x-lunora-table": "channels"
                            },
                            "text": {
                                "type": "string"
                            },
                            "kind": {
                                "anyOf": [
                                    {
                                        "const": "text",
                                        "type": "string"
                                    },
                                    {
                                        "const": "image",
                                        "type": "string"
                                    }
                                ]
                            },
                            "tags": {
                                "additionalProperties": {
                                    "type": "string"
                                },
                                "propertyNames": {
                                    "type": "string"
                                },
                                "type": "object"
                            }
                        },
                        "required": [
                            "channelId",
                            "text",
                            "kind",
                            "tags"
                        ],
                        "type": "object"
                    }
                }
            ],
            "result": {
                "name": "result",
                "schema": {
                    "description": "Result is TS-inferred from the function's return type (no `.output()` declared); best-effort — any JSON."
                }
            },
            "summary": "mutation: messages:send",
            "x-lunora-function-kind": "mutation",
            "x-tags": [
                {
                    "name": "messages"
                }
            ]
        }
    ],
    "openrpc": "1.3.2"
};
