// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import * as cirrus_messages_0 from "../messages.js";
import * as cirrus_migrations_1 from "../migrations.js";

import {
    action as actionBase,
    internalAction as internalActionBase,
    internalMutation as internalMutationBase,
    internalQuery as internalQueryBase,
    mutation as mutationBase,
    query as queryBase,
} from "@cirrus/server";
import type {
    ActionCtx as ActionCtxBase,
    ArgsValidator,
    DatabaseReader,
    DatabaseWriter,
    InferArgs,
    MutationCtx as MutationCtxBase,
    QueryCtx as QueryCtxBase,
    RegisteredAction,
    RegisteredMutation,
    RegisteredQuery,
} from "@cirrus/server";

import type { DatabaseReaderFacade, DatabaseWriterFacade, Id, OrmReader, OrmWriter } from "./dataModel.js";

export type { DataModel, Doc, Id } from "./dataModel.js";

/**
 * Project-typed contexts. The base contexts from `@cirrus/server` are
 * untyped against the schema; here `db` is widened to the generated per-table
 * facade (`ctx.db.<table>.findMany(...)`) while keeping the legacy structural
 * `db.get`/`db.query` surface for back-compat.
 */
export interface QueryCtx extends Omit<QueryCtxBase, "db"> {
    readonly db: DatabaseReader & DatabaseReaderFacade;
    readonly orm: OrmReader;
}

export interface MutationCtx extends Omit<MutationCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

export interface ActionCtx extends Omit<ActionCtxBase, "db"> {
    readonly db: DatabaseWriter & DatabaseWriterFacade;
    readonly orm: OrmWriter;
}

/** `query()` bound to this project's typed {@link QueryCtx}. */
export const query = queryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** `mutation()` bound to this project's typed {@link MutationCtx}. */
export const mutation = mutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** `action()` bound to this project's typed {@link ActionCtx}. */
export const action = actionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/** `internalQuery()` bound to this project's typed {@link QueryCtx} — never exposed on `api`. */
export const internalQuery = internalQueryBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: QueryCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredQuery<A, R>;

/** `internalMutation()` bound to this project's typed {@link MutationCtx} — never exposed on `api`. */
export const internalMutation = internalMutationBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: MutationCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredMutation<A, R>;

/** `internalAction()` bound to this project's typed {@link ActionCtx} — never exposed on `api`. */
export const internalAction = internalActionBase as unknown as <A extends ArgsValidator, R>(definition: {
    args: A;
    handler: (context: ActionCtx, args: InferArgs<A>) => Promise<R> | R;
}) => RegisteredAction<A, R>;

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredCirrusFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__cirrusRef` the client
 * emits (`api[namespace][fn].__cirrusRef === "namespace:fn"`).
 */
export const CIRRUS_FUNCTIONS: Record<string, RegisteredCirrusFunction> = {
    "messages:list": cirrus_messages_0.list as unknown as RegisteredCirrusFunction,
    "messages:purge": cirrus_messages_0.purge as unknown as RegisteredCirrusFunction,
    "messages:send": cirrus_messages_0.send as unknown as RegisteredCirrusFunction,
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * CirrusError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchCirrusFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw Object.assign(new Error(`function not registered: ${functionPath}`), {
            name: "CirrusError",
            code: "FUNCTION_NOT_FOUND",
            status: 404,
        });
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    messages: {
        list: (args: { channelId: Id<"channels">; limit?: number }) => Promise<unknown>;
        purge: (args: { channelId: Id<"channels"> }) => Promise<unknown>;
        send: (args: { channelId: Id<"channels">; text: string; kind: "text" | "image"; tags: Record<string, string> }) => Promise<unknown>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw Object.assign(new Error(`function not registered: ${functionPath}`), {
            name: "CirrusError",
            code: "FUNCTION_NOT_FOUND",
            status: 404,
        });
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    messages: {
        list: (args) => callRegistered(context, "messages:list", args),
        purge: (args) => callRegistered(context, "messages:purge", args),
        send: (args) => callRegistered(context, "messages:send", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const CIRRUS_MIGRATIONS: Record<string, RegisteredDataMigration> = {
    "backfill-read-by": cirrus_migrations_1.backfillReadBy as unknown as RegisteredDataMigration,
};
