// GENERATED by @cirrus/codegen — do not edit.
// Run `cirrus codegen` to regenerate.

import type { AggregateOptions, GroupByOptions, DatabaseWriterLike, DataMigrationLike, MigrationRunResult, QueryArgs, RankOptions, RankPageOptions, RestrictableQueryOptions, RunShardMigrationArgs, SchedulerLike, SchemaLike, ShardDOState, SqlExec, WhereInput } from "@cirrus/do";
import { createShardCtxDb, runDataMigration, runShardMigrations, ShardDO as ShardDOBase } from "@cirrus/do";

import schema from "../schema.js";
import { CIRRUS_FUNCTIONS, CIRRUS_MIGRATIONS } from "./server.js";

type FunctionKind = "action" | "mutation" | "query";

interface FunctionReference {
    __cirrusRef: string;
}

export interface ShardDOConfig {
    scheduler?: (env: Record<string, unknown>) => unknown;
    storage?: (env: Record<string, unknown>) => unknown;
    d1?: (env: Record<string, unknown>) => DatabaseWriterLike;
}

const schedulerStub = {
    cancel: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAfter: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAt: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
};

const storageStub = {
    delete: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    download: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getSignedUrl: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getUrl: () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    list: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    upload: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
};

const globalDbStub: DatabaseWriterLike = {
    aggregate: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    count: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    delete: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    findFirst: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    findFirstOrThrow: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    findMany: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    get: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    groupBy: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    insert: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    patch: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    query: () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
    replace: async () => {
        throw new Error("ctx.db.<globalTable>: no D1 binding configured. Pass `d1` to createShardDO().");
    },
};

const bindTable = (writer: DatabaseWriterLike, tableName: string) => ({
    aggregate: (options: AggregateOptions) => writer.aggregate(tableName, options),
    count: (where?: RestrictableQueryOptions | WhereInput) => writer.count(tableName, where),
    delete: (id: string) => writer.delete(id),
    findFirst: (args?: QueryArgs) => writer.findFirst(tableName, args),
    findFirstOrThrow: (args?: QueryArgs) => writer.findFirstOrThrow(tableName, args),
    findMany: (args?: QueryArgs) => writer.findMany(tableName, args),
    get: (id: string) => writer.get(id),
    groupBy: (options: GroupByOptions) => writer.groupBy(tableName, options),
    insert: (values: Record<string, unknown>) => writer.insert(tableName, values),
    patch: (id: string, values: Record<string, unknown>) => writer.patch(id, values),
    rank: (indexName: string, options: RankOptions) => writer.rank(tableName, indexName, options),
    rankPage: (indexName: string, options?: RankPageOptions) => writer.rankPage(tableName, indexName, options),
    replace: (id: string, values: Record<string, unknown>) => writer.replace(id, values),
});

const bindOrm = (facade: Record<string, ReturnType<typeof bindTable>>) => {
    const resolve = (table: string): ReturnType<typeof bindTable> => {
        const bound = facade[table];

        if (!bound) {
            throw new Error(`unknown table: ${table}`);
        }

        return bound;
    };

    return {
        delete: (table: string, id: string) => resolve(table).delete(id),
        insert: (table: string) => ({ values: (values: Record<string, unknown>) => resolve(table).insert(values) }),
        query: facade,
        replace: (table: string, id: string) => ({ with: (values: Record<string, unknown>) => resolve(table).replace(id, values) }),
        update: (table: string, id: string) => ({ set: (values: Record<string, unknown>) => resolve(table).patch(id, values) }),
    };
};

const dispatchRun = (expected: FunctionKind, functionPath: string, args: Record<string, unknown>, ctx: unknown): Promise<unknown> | unknown => {
    const registered = CIRRUS_FUNCTIONS[functionPath];

    if (!registered) {
        throw new Error(`unknown function: ${functionPath}`);
    }

    if (registered.kind !== expected) {
        throw new Error(`ctx.run${expected[0]!.toUpperCase()}${expected.slice(1)}: "${functionPath}" is registered as a ${registered.kind}, not a ${expected}`);
    }

    return registered.handler(ctx, args);
};

/**
 * Build the project's shard Durable Object. Export the result as `ShardDO`
 * from the worker entry so wrangler binds it by name.
 */
export const createShardDO = (config: ShardDOConfig = {}): new (state: ShardDOState, env: unknown) => ShardDOBase =>
    class extends ShardDOBase {
        private migrated = false;

        public override async handleRpc(functionPath: string, args: Record<string, unknown>): Promise<unknown> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            // Internal functions are reachable only server-side (`ctx.run*`),
            // never from a client. Report them as not-found so their existence
            // never leaks across the external RPC boundary.
            if (!registered || registered.visibility === "internal") {
                throw Object.assign(new Error(`function not registered: ${functionPath}`), {
                    name: "CirrusError",
                    code: "FUNCTION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            return registered.handler(this.buildCtx(), args);
        }

        protected override async executeSubscription(functionPath: string, args: Record<string, unknown>): Promise<{ result: unknown; tables: Set<string> } | null> {
            const registered = CIRRUS_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "query" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            const tables = new Set<string>();
            const ctx = this.buildCtx({ onRead: (table) => tables.add(table) });
            const result = await registered.handler(ctx, args);

            return { result, tables };
        }

        protected override async runShardDataMigration(args: RunShardMigrationArgs): Promise<MigrationRunResult> {
            const migration = CIRRUS_MIGRATIONS[args.id];

            if (!migration) {
                throw Object.assign(new Error(`data migration "${args.id}" is not registered`), {
                    name: "CirrusError",
                    code: "MIGRATION_NOT_FOUND",
                    status: 404,
                });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            return runDataMigration({
                batchSize: args.batchSize,
                direction: args.direction,
                dryRun: args.dryRun,
                maxBatches: args.maxBatches,
                migration: migration as unknown as DataMigrationLike,
                sql: this.sql as SqlExec,
                writer,
            });
        }

        private ensureMigrated(): void {
            if (this.migrated) {
                return;
            }

            runShardMigrations(this.sql as SqlExec, schema as unknown as SchemaLike);
            this.migrated = true;
        }

        private buildCtx(options: { onRead?: (table: string) => void } = {}): unknown {
            const env = (this.env ?? {}) as Record<string, unknown>;
            const userId = this.getCurrentUserId();
            const identity = this.getCurrentIdentity();

            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const db: DatabaseWriterLike = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                onRead: options.onRead,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });
            const globalDb: DatabaseWriterLike = config.d1?.(env) ?? globalDbStub;

            const facade = db as unknown as Record<string, ReturnType<typeof bindTable>>;
            facade["messages"] = bindTable(db, "messages");
            facade["users"] = bindTable(globalDb, "users");
            facade["attachments"] = bindTable(globalDb, "attachments");

            const ctx: Record<string, unknown> = {
                auth: {
                    getIdentity: async () => identity ?? null,
                    userId: userId ?? null,
                },
                db,
                fetch: globalThis.fetch.bind(globalThis),
                orm: bindOrm(facade),
                scheduler,
                storage: config.storage?.(env) ?? storageStub,
            };

            ctx.runAction = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("action", reference.__cirrusRef, fnArgs, ctx);
            ctx.runMutation = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("mutation", reference.__cirrusRef, fnArgs, ctx);
            ctx.runQuery = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("query", reference.__cirrusRef, fnArgs, ctx);

            return ctx;
        }
    };
