// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type {
    DatabaseReaderFacade as DatabaseReaderFacadeOf,
    DatabaseWriterFacade as DatabaseWriterFacadeOf,
    LoadWith as LoadWithOf,
    TableReaderFacade as TableReaderFacadeOf,
    TableWriterFacade as TableWriterFacadeOf,
    WithArg as WithArgOf,
} from "lunorash/server/data-model";

export type {
    AggregateOp,
    GroupByEntry,
    OrderBy,
    QueryArgs,
    QueryPage,
    RankPage,
    RankResult,
    RestrictableQueryOptions,
    RestrictableQueryOptionsOf,
    SearchFilterBuilder,
    SearchReader,
    TableAggregateOptions,
    TableAggregateOptionsOf,
    TableGroupByOptions,
    TableGroupByOptionsOf,
    TableRankOptions,
    TableRankPageOptions,
    Where,
    WhereOf,
    WhereOperators,
} from "lunorash/server/data-model";

export type TableName = "profiles" | "channels" | "messages" | "presence" | "ratelimit_buckets";

/**
 * The tables **this app declared** — every {@link TableName} except those an add-on
 * contributed through `defineSchema(...).extend(...)`.
 *
 * An add-on's tables are real tables and stay in `TableName` (they are queryable,
 * they appear in `DataModel`), but an app enumerating "my tables" should not have to
 * know they exist: an account-deletion sweep, an export, a migration allowlist, or a
 * helper generic over a table union is about the app's own data, and every add-on
 * added or removed would otherwise silently change the correct answer.
 *
 * ```ts
 * // Doesn't need to mention `ratelimit_buckets`, and won't drift when an add-on lands.
 * const EXPORTED: readonly AppTableName[] = ["nodes", "tagColors"];
 * ```
 */
export type AppTableName = "profiles" | "channels" | "messages" | "presence";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_profiles {
    _id: Id<"profiles">;
    _creationTime: number;
    userId: string;
    name: string;
    avatarKey?: string;
}

export interface Doc_channels {
    _id: Id<"channels">;
    _creationTime: number;
    name: string;
    createdBy: string;
}

export interface Doc_messages {
    _id: Id<"messages">;
    _creationTime: number;
    channelId: string;
    authorId: string;
    content: string;
    attachmentKey?: string;
    attachmentName?: string;
}

export interface Doc_presence {
    _id: Id<"presence">;
    _creationTime: number;
    channelId: string;
    sessionId: string;
    userId: string;
    name: string;
    lastSeen: number;
}

export interface Doc_ratelimit_buckets {
    _id: Id<"ratelimit_buckets">;
    _creationTime: number;
    key: string;
    value: number;
    ts: number;
    prev?: number;
}

export interface DataModel {
    profiles: Doc_profiles;
    channels: Doc_channels;
    messages: Doc_messages;
    presence: Doc_presence;
    ratelimit_buckets: Doc_ratelimit_buckets;
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. `never` for tables without secondary indexes.
 * Used by `TableReader.withIndex()` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
    profiles: "by_user";
    channels: "by_name";
    messages: "by_channel";
    presence: "by_channel_session";
    ratelimit_buckets: "by_key";
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. `never` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
    profiles: never;
    channels: never;
    messages: "search_content";
    presence: never;
    ratelimit_buckets: never;
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Per-table rank-index name union. `never` for tables without a rankIndex. */
export interface RankIndexNamesByTable {
    profiles: never;
    channels: never;
    messages: never;
    presence: never;
    ratelimit_buckets: never;
}

export type RankIndexName<T extends keyof DataModel> = RankIndexNamesByTable[T];

/** Per-table geo-index name union. `never` for tables without a geoIndex. */
export interface GeoIndexNamesByTable {
    profiles: never;
    channels: never;
    messages: never;
    presence: never;
    ratelimit_buckets: never;
}

export type GeoIndexName<T extends keyof DataModel> = GeoIndexNamesByTable[T];

/** Union of declared vector index names. `never` when none are declared. */
export type VectorIndexName = never;

export interface Insert_profiles {
    _id?: Id<"profiles">;
    _creationTime?: number;
    userId: string;
    name: string;
    avatarKey?: string;
}

export interface Insert_channels {
    _id?: Id<"channels">;
    _creationTime?: number;
    name: string;
    createdBy: string;
}

export interface Insert_messages {
    _id?: Id<"messages">;
    _creationTime?: number;
    channelId: string;
    authorId: string;
    content: string;
    attachmentKey?: string;
    attachmentName?: string;
}

export interface Insert_presence {
    _id?: Id<"presence">;
    _creationTime?: number;
    channelId: string;
    sessionId: string;
    userId: string;
    name: string;
    lastSeen: number;
}

export interface Insert_ratelimit_buckets {
    _id?: Id<"ratelimit_buckets">;
    _creationTime?: number;
    key: string;
    value: number;
    ts: number;
    prev?: number;
}

/** Per-table insert shape, accepted by `ctx.db.<table>.insert(...)`. */
export interface InsertModel {
    profiles: Insert_profiles;
    channels: Insert_channels;
    messages: Insert_messages;
    presence: Insert_presence;
    ratelimit_buckets: Insert_ratelimit_buckets;
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the `with` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. `{}` for tables with none. */
export interface Relations {
    profiles: {};
    channels: {};
    messages: {};
    presence: {};
    ratelimit_buckets: {};
}

/** The `with` argument for table `T` — see `@lunora/server/data-model`. */
export type WithArg<T extends keyof DataModel> = WithArgOf<DataModel, Relations, T>;

/** `Doc<T>` narrowed to exactly the relations requested in the with-arg `W`. */
export type LoadWith<T extends keyof DataModel, W> = LoadWithOf<DataModel, Relations, T, W>;

/** Read-only typed table accessor exposed on `QueryCtx.db.<table>`. */
export type TableReaderFacade<T extends keyof DataModel> = TableReaderFacadeOf<DataModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, T, GeoIndexNamesByTable>;

/** Read-write typed table accessor exposed on `MutationCtx.db.<table>` / `ActionCtx.db.<table>`. */
export type TableWriterFacade<T extends keyof DataModel> = TableWriterFacadeOf<DataModel, InsertModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, T, GeoIndexNamesByTable>;

/** Per-table read facade — `ctx.db.<table>` on a `QueryCtx`. */
export type DatabaseReaderFacade = DatabaseReaderFacadeOf<DataModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, GeoIndexNamesByTable>;

/** Per-table read-write facade — `ctx.db.<table>` on a `MutationCtx` / `ActionCtx`. */
export type DatabaseWriterFacade = DatabaseWriterFacadeOf<DataModel, InsertModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, GeoIndexNamesByTable>;

/** Insert builder returned by `ctx.orm.insert(table)`. */
export interface OrmInsertBuilder<T extends keyof DataModel> {
    values: (values: Insert<T>) => Promise<Id<T>>;
}

/** Replace builder returned by `ctx.orm.replace(table, id)` — swaps the whole document. */
export interface OrmReplaceBuilder<T extends keyof DataModel> {
    with: (values: Insert<T>) => Promise<void>;
}

/** Update builder returned by `ctx.orm.update(table, id)` — patches the named fields. */
export interface OrmUpdateBuilder<T extends keyof DataModel> {
    set: (values: Partial<Insert<T>>) => Promise<void>;
}

/** Read-only ORM surface — `ctx.orm` on a `QueryCtx`. Mirrors `ctx.db` reads under a kitcn-style `query` namespace. */
export interface OrmReader {
    query: DatabaseReaderFacade;
}

/** Read-write ORM surface — `ctx.orm` on a `MutationCtx` / `ActionCtx`. Writes are addressed by id, like `ctx.db`. */
export interface OrmWriter extends OrmReader {
    delete: <T extends keyof DataModel>(table: T, id: Id<T>) => Promise<void>;
    insert: <T extends keyof DataModel>(table: T) => OrmInsertBuilder<T>;
    replace: <T extends keyof DataModel>(table: T, id: Id<T>) => OrmReplaceBuilder<T>;
    update: <T extends keyof DataModel>(table: T, id: Id<T>) => OrmUpdateBuilder<T>;
}
