// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_channels_0 from "../channels.js";
import * as lunora_messages_1 from "../messages.js";
import * as lunora_presence_2 from "../presence.js";
import * as lunora_profiles_3 from "../profiles.js";

import { DEFER_VALIDATION as DEFER, installCompiledValidatorMap } from "lunorash/values";
import { LunoraError } from "lunorash/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";
import type { Id } from "./dataModel.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * Present on a `"stream"` declared `durable`: its run is persisted and
     * survives the socket that opened it. Absent on every other kind, and on an
     * ephemeral stream.
     */
    durable?: { ttlMs?: number };
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /**
     * The lifecycle moment a hook fires on, when this registration came from
     * `onConnect`/`onDisconnect`/`onShardInit`/`onQueryChange`. Read at
     * dispatch to decide whether the function runs system-trusted: `init` and
     * `reactor` have no caller identity, so RLS has no user to scope to.
     */
    lifecycle?: "connect" | "disconnect" | "init" | "reactor";
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "channels:create": lunora_channels_0.create as unknown as RegisteredLunoraFunction,
    "channels:list": lunora_channels_0.list as unknown as RegisteredLunoraFunction,
    "messages:attachmentUrl": lunora_messages_1.attachmentUrl as unknown as RegisteredLunoraFunction,
    "messages:list": lunora_messages_1.list as unknown as RegisteredLunoraFunction,
    "messages:requestAttachmentUpload": lunora_messages_1.requestAttachmentUpload as unknown as RegisteredLunoraFunction,
    "messages:search": lunora_messages_1.search as unknown as RegisteredLunoraFunction,
    "messages:send": lunora_messages_1.send as unknown as RegisteredLunoraFunction,
    "presence:heartbeat": lunora_presence_2.heartbeat as unknown as RegisteredLunoraFunction,
    "presence:leave": lunora_presence_2.leave as unknown as RegisteredLunoraFunction,
    "presence:list": lunora_presence_2.list as unknown as RegisteredLunoraFunction,
    "profiles:avatarUrl": lunora_profiles_3.avatarUrl as unknown as RegisteredLunoraFunction,
    "profiles:list": lunora_profiles_3.list as unknown as RegisteredLunoraFunction,
    "profiles:requestAvatarUpload": lunora_profiles_3.requestAvatarUpload as unknown as RegisteredLunoraFunction,
    "profiles:save": lunora_profiles_3.save as unknown as RegisteredLunoraFunction,
};

/**
 * AOT-compiled argument validators (Worker-safe, no `eval`). Each is installed
 * onto its function's live `.args` object and consulted by the interpreted
 * parser as a zero-allocation fast path; anything it can't model is deferred.
 */
installCompiledValidatorMap(lunora_channels_0.create.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["name"] !== "string") return DEFER;
if (source["name"].length > 64) return DEFER;
return { "name": source["name"] };
});
installCompiledValidatorMap(lunora_messages_1.attachmentUrl.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["key"] !== "string") return DEFER;
if (source["key"].length > 512) return DEFER;
return { "channelId": source["channelId"], "key": source["key"] };
});
installCompiledValidatorMap(lunora_messages_1.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
return { "channelId": source["channelId"] };
});
installCompiledValidatorMap(lunora_messages_1.requestAttachmentUpload.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["contentType"] !== "string") return DEFER;
if (source["contentType"].length > 128) return DEFER;
return { "channelId": source["channelId"], "contentType": source["contentType"] };
});
installCompiledValidatorMap(lunora_messages_1.search.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["text"] !== "string") return DEFER;
if (source["text"].length > 200) return DEFER;
return { "channelId": source["channelId"], "text": source["text"] };
});
installCompiledValidatorMap(lunora_messages_1.send.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["content"] !== "string") return DEFER;
if (source["content"].length > 4096) return DEFER;
let __has1 = false;
let __val1;
if (source["attachmentKey"] !== undefined) {
if (typeof source["attachmentKey"] !== "string") return DEFER;
if (source["attachmentKey"].length > 512) return DEFER;
__val1 = source["attachmentKey"];
__has1 = true;
}
let __has2 = false;
let __val2;
if (source["attachmentName"] !== undefined) {
if (typeof source["attachmentName"] !== "string") return DEFER;
if (source["attachmentName"].length > 256) return DEFER;
__val2 = source["attachmentName"];
__has2 = true;
}
return { "channelId": source["channelId"], "content": source["content"], ...(__has1 ? { "attachmentKey": __val1 } : {}), ...(__has2 ? { "attachmentName": __val2 } : {}) };
});
installCompiledValidatorMap(lunora_presence_2.heartbeat.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["sessionId"] !== "string") return DEFER;
if (source["sessionId"].length > 64) return DEFER;
if (typeof source["name"] !== "string") return DEFER;
if (source["name"].length > 80) return DEFER;
return { "channelId": source["channelId"], "sessionId": source["sessionId"], "name": source["name"] };
});
installCompiledValidatorMap(lunora_presence_2.leave.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
if (typeof source["sessionId"] !== "string") return DEFER;
if (source["sessionId"].length > 64) return DEFER;
return { "channelId": source["channelId"], "sessionId": source["sessionId"] };
});
installCompiledValidatorMap(lunora_presence_2.list.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["channelId"] !== "string") return DEFER;
if (source["channelId"].length > 128) return DEFER;
return { "channelId": source["channelId"] };
});
installCompiledValidatorMap(lunora_profiles_3.avatarUrl.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["key"] !== "string") return DEFER;
if (source["key"].length > 512) return DEFER;
return { "key": source["key"] };
});
installCompiledValidatorMap(lunora_profiles_3.requestAvatarUpload.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["contentType"] !== "string") return DEFER;
if (source["contentType"].length > 128) return DEFER;
return { "contentType": source["contentType"] };
});
installCompiledValidatorMap(lunora_profiles_3.save.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (Object.getPrototypeOf(source) !== Object.prototype && Object.getPrototypeOf(source) !== null) return DEFER;
if (typeof source["name"] !== "string") return DEFER;
if (source["name"].length > 80) return DEFER;
let __has1 = false;
let __val1;
if (source["avatarKey"] !== undefined) {
if (typeof source["avatarKey"] !== "string") return DEFER;
if (source["avatarKey"].length > 512) return DEFER;
__val1 = source["avatarKey"];
__has1 = true;
}
return { "name": source["name"], ...(__has1 ? { "avatarKey": __val1 } : {}) };
});

/**
 * Lifecycle manifest: the function paths the generated ShardDO dispatches when a
 * client's WebSocket connects (`connect`) or disconnects (`disconnect`), once
 * per Durable Object instance before any handler runs (`init`), and after a
 * write flush when a watched read's result changed (`reactor`). Each path also
 * resolves through {@link LUNORA_FUNCTIONS}. The socket sides run under the
 * socket's verified identity; `init` and `reactor` have no caller, so they run
 * anonymous — all via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[]; init: readonly string[]; reactor: readonly string[] } = {
    connect: [],
    disconnect: [],
    init: [],
    reactor: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    channels: {
        create: (args: { name: string }) => Promise<Id<"channels">>;
        list: (args?: {}) => Promise<import("./dataModel.js").Doc_channels[]>;
    };
    messages: {
        attachmentUrl: (args: { channelId: string; key: string }) => Promise<string>;
        list: (args: { channelId: string }) => Promise<import("./dataModel.js").Doc_messages[]>;
        requestAttachmentUpload: (args: { channelId: string; contentType: string }) => Promise<{ key: string; url: string; }>;
        search: (args: { channelId: string; text: string }) => Promise<import("./dataModel.js").Doc_messages[]>;
        send: (args: { channelId: string; content: string; attachmentKey?: string; attachmentName?: string }) => Promise<Id<"messages">>;
    };
    presence: {
        heartbeat: (args: { channelId: string; sessionId: string; name: string }) => Promise<void>;
        leave: (args: { channelId: string; sessionId: string }) => Promise<void>;
        list: (args: { channelId: string }) => Promise<import("./dataModel.js").Doc_presence[]>;
    };
    profiles: {
        avatarUrl: (args: { key: string }) => Promise<string>;
        list: (args?: {}) => Promise<import("./dataModel.js").Doc_profiles[]>;
        requestAvatarUpload: (args: { contentType: string }) => Promise<{ key: string; url: string; }>;
        save: (args: { name: string; avatarKey?: string }) => Promise<Id<"profiles">>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    channels: {
        create: (args) => callRegistered(context, "channels:create", args),
        list: (args) => callRegistered(context, "channels:list", args),
    },
    messages: {
        attachmentUrl: (args) => callRegistered(context, "messages:attachmentUrl", args),
        list: (args) => callRegistered(context, "messages:list", args),
        requestAttachmentUpload: (args) => callRegistered(context, "messages:requestAttachmentUpload", args),
        search: (args) => callRegistered(context, "messages:search", args),
        send: (args) => callRegistered(context, "messages:send", args),
    },
    presence: {
        heartbeat: (args) => callRegistered(context, "presence:heartbeat", args),
        leave: (args) => callRegistered(context, "presence:leave", args),
        list: (args) => callRegistered(context, "presence:list", args),
    },
    profiles: {
        avatarUrl: (args) => callRegistered(context, "profiles:avatarUrl", args),
        list: (args) => callRegistered(context, "profiles:list", args),
        requestAvatarUpload: (args) => callRegistered(context, "profiles:requestAvatarUpload", args),
        save: (args) => callRegistered(context, "profiles:save", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
